### ISSUE TITLE
RGB calibration

### ISSUE THREAD

**Issue by Jozefiel** [OpenKinect/libfreenect2#1000]
Hi :-)
Can I ask you, how to get extrinsic calibration constants for RGB (Freenect2Device::ColorCameraParams). 

float | shift_d 
float | shift_m
float | mx_x3y0
float | mx_x0y3
...
I have calibration outputs for IR and RGB from Matlab StereoCalibration Toolbox.
Thanks

**Comment by floe** [comment]
The internal color camera params are for a Kinect-specific calibration algorithm that's replicated in registration.cpp. Unfortunately, there's no easy way to convert these to "regular" extrinsic parameters.

**Comment by remmel** [comment]
That repo is using "regular" extrinsics https://github.com/code-iai/iai_kinect2
