### ISSUE TITLE
Recoding audio with Kinect

### ISSUE THREAD

**Issue by sharpriy** [OpenKinect/libfreenect2#1006]
Do pylibfreenect2 provides any interface to record audio stream from Kinect. I have gone through some of the forums and there are some where Kinect SDK is being used for this. One of them is https://social.msdn.microsoft.com/Forums/sqlserver/en-US/f4e79a9f-76c8-4013-a33c-c2b0958806c9/recording-a-continuous-kinect-audiostream-using-cnet?forum=kinectsdk

**Comment by xlz** [comment]
https://github.com/OpenKinect/libfreenect2/wiki/Linux-USB-Notes#usb-audio
