### ISSUE TITLE
Multiple kinects connection & coding

### ISSUE THREAD

**Issue by ShaminiKoravuna** [OpenKinect/libfreenect2#1007]
Hello Everyone!

I'am working on a project where I'am using two kinects for windows v2 for 3d Scene reconstruction. I want to implement it using libfreenect2. This is first time am working with kinects. I have few doubts and I need some help regarding programming the kinects.

First thing if we don't have different USB host controllers, can we connect it to the same PC? If yes? How can we connect it? Can we use external USB controllers?

If anyone has done any projects using multiple kinects could you please share the relevant documentation and source code with me.

Any help will be highly appreciated!

Thanks in advance!

Shamini

**Comment by floe** [comment]
Most people who use multiple Kinects connect PCI-Express addon card with additional USB3 controllers and use one per device. See also here: https://github.com/OpenKinect/libfreenect2#requirements-for-multiple-kinects and discussion at #320 .

**Comment by ShaminiKoravuna** [comment]
Thanks for that. I have checked it. 

And do we have any sample code for working with two kinects, for creating a 3d point cloud?

**Comment by floe** [comment]
See here: https://github.com/steppobeck

**Comment by ShaminiKoravuna** [comment]
Thank you!
