### ISSUE TITLE
Dependencies are not installed with `make install`

### ISSUE THREAD

**Issue by wiedemeyer** [OpenKinect/libfreenect2#101]
Dependencies in the `depends` folders are not installed with 'make install'.
Could be fixed by adding the following lines to the end of [CMakeLists.txt](https://github.com/OpenKinect/libfreenect2/blob/master/examples/protonect/CMakeLists.txt):
```
install_files(/ FILES "${MY_DIR}/../../depends/glew/")
install_files(/ FILES "${MY_DIR}/../../depends/libusb/")
```
or maybe by installing them from the `install_deps.sh` script.

**Comment by christiankerl** [comment]
@wiedemeyer how did you deal with undefined references to udev functions?

**Comment by wiedemeyer** [comment]
This can be fixed by adding `udev` to `target_link_libraries`.
I don't know where it comes from. On my machine (14.04) it is working without this undefined references to udev. Could it be that this problem only occurs on 12.04 but not on 14.04?

**Comment by christiankerl** [comment]
maybe its 12.04. Meanwhile, I found another solution to use the custom build of libusb. This requires the following changes to CmakeLists.txt.

change libusb setup, somehow it is important to have an absolute path
```cmake
# LibUSB
GET_FILENAME_COMPONENT(LIBUSB_DIR "${MY_DIR}/../../depends/libusb/" REALPATH)

INCLUDE_DIRECTORIES("${LIBUSB_DIR}/include/libusb-1.0/")
LINK_DIRECTORIES("${LIBUSB_DIR}/lib/")
```
and add:
```cmake
SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
```
afterwards ldd of the installed libfreenect2.so will point to the correct libusb.

**Comment by wiedemeyer** [comment]
that's also fine.

**Comment by wiedemeyer** [comment]
@christiankerl: will you add those changes to the upstream any time soon?

**Comment by christiankerl** [comment]
I'm not sure if this solution works, if libfreenect2 is not built locally from source (e.g. if you want to create a ros debian package, including libfreenect2)

**Comment by Edwinzero** [comment]
Hey guys, I think actually glew path that set in the .sh file doesn't contains the src files.
It will give error when you run the .sh file.
