### ISSUE TITLE
Build make error

### ISSUE THREAD

**Issue by SSTTTAY** [OpenKinect/libfreenect2#1015]
Overview Description:
when I run the Build command , it raises this error:
![2018-08-10 15-59-22](https://user-images.githubusercontent.com/26354625/43946272-57b3fdf4-9cb7-11e8-8bc1-74ec0ca7c14a.png)
Can you tell what's wrong with that?

**Comment by xlz** [comment]
If you `grep -r XRRSetCrtcGamma /usr/lib` you may find the libraries that are missing for linking.
