### ISSUE TITLE
No device connected!!

### ISSUE THREAD

**Issue by patilaum** [OpenKinect/libfreenect2#1017]
I'm using Ubuntu 16.04 and Xbox kinect
I installed libfreenect2 as given and alos updated udev file( hence permission given).
However ./Protonect gives following error.

I'm interested in running kinect using opencv and hence installed libfreenect but later found out in its README that libfreenect2 works for xbox one.

please help. 

./Protonect OUTPUT
Version: 0.2.0
Environment variables: LOGFILE=<protonect.log>
Usage: ./Protonect [-gpu=<id>] [gl | cl | clkde | cuda | cudakde | cpu] [<device serial>]
        [-noviewer] [-norgb | -nodepth] [-help] [-version]
        [-frames <number of frames to process>]
To pause and unpause: pkill -USR1 Protonect
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 8 usb devices connected
[Info] [Freenect2Impl] found 0 devices
no device connected!
 
lsusb OUTPUT (I've connected kinect in USB 3) 

Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
Bus 001 Device 043: ID 045e:02ae Microsoft Corp. Xbox NUI Camera
Bus 001 Device 041: ID 045e:02b0 Microsoft Corp. Xbox NUI Motor
Bus 001 Device 042: ID 045e:02ad Microsoft Corp. Xbox NUI Audio
Bus 001 Device 040: ID 0409:005a NEC Corp. HighSpeed Hub
Bus 001 Device 003: ID 8087:0aa7 Intel Corp. 
Bus 001 Device 039: ID 046d:c534 Logitech, Inc. Unifying Receiver
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

lsusb -t OUTPUT

/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/6p, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/12p, 480M
    |__ Port 2: Dev 39, If 0, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 2: Dev 39, If 1, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 5: Dev 3, If 0, Class=Wireless, Driver=btusb, 12M
    |__ Port 5: Dev 3, If 1, Class=Wireless, Driver=btusb, 12M
    |__ Port 6: Dev 40, If 0, Class=Hub, Driver=hub/3p, 480M
        |__ Port 2: Dev 41, If 0, Class=Vendor Specific Class, Driver=, 12M
        |__ Port 3: Dev 43, If 0, Class=Vendor Specific Class, Driver=, 480M
        |__ Port 1: Dev 42, If 0, Class=Vendor Specific Class, Driver=, 480M
    |__ Port 8: Dev 4, If 0, Class=Vendor Specific Class, Driver=rtsx_usb, 480M

lspci | grep USB OUTPUT

00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)

**Comment by floe** [comment]
```
Bus 001 Device 043: ID 045e:02ae Microsoft Corp. Xbox NUI Camera
Bus 001 Device 041: ID 045e:02b0 Microsoft Corp. Xbox NUI Motor
Bus 001 Device 042: ID 045e:02ad Microsoft Corp. Xbox NUI Audio
```

This device is the old Kinect, hence you need https://github.com/OpenKinect/libfreenect (without the 2).
