### ISSUE TITLE
Cannot Install OpenNi2 Mac OS

### ISSUE THREAD

**Issue by sdewailly** [OpenKinect/libfreenect2#1019]
Overview Description:

I am trying to install openni2 to develop an application using the Kinect V2.
[openni2.txt](https://github.com/OpenKinect/libfreenect2/files/2376294/openni2.txt)

Version, Platform, and Hardware Bug Found:

1. `git log -1 --oneline`
2. `uname -a`
3. `lsusb -t`
4. `lspci -nn`
N/A

Steps to Reproduce:

1. brew tap brewsci/homebrew-science
2. brew install openni2
3. 

Actual Results:
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)

Expected Results: pass

Reproducibility: I believe you only have to follow the steps above.

Additional Information: Is there an alternative way to install this API because I am stuck?

**Comment by xlz** [comment]
The error shows something about the homebrew tool itself.
