### ISSUE TITLE
How to find the equivalent depth pixel from a RGB pixel

### ISSUE THREAD

**Issue by AAcquier** [OpenKinect/libfreenect2#1021]
Hello,

I would like to know if it is possible to find the corresponding coordinate of RGB point (in 1920x1080  format) in the depth map (512x424) in term of pixels (not real world distance).
I know that I can get the real world distance using getPointXYZ and the undistorted map but can I work something out from there?

**Comment by xlz** [comment]
You can use the apply method in http://openkinect.github.io/libfreenect2/classlibfreenect2_1_1Registration.html.
