### ISSUE TITLE
GLFW error 65543 WGL: Failed to create OpenGL context

### ISSUE THREAD

**Issue by YANGYU106** [OpenKinect/libfreenect2#1025]
Hello there,

I run Win 10 on the Parallels desktop 13 on my Mac OS X system and build the libfreenect2 driver in virtual Win 10 system. I can successfully installed and made the driver but when I tested program Protonect.exe or OpenNI2, I got the error "GLFW error 65543 WGL: Failed to create OpenGL context":

Version: 0.2.0
Environment variables: LOGFILE=<protonect.log>
Usage: .\install\bin\Protonect.exe [-gpu=<id>] [gl | cl | clkde | cuda | cudakde | cpu] [<device serial>]
        [-noviewer] [-norgb | -nodepth] [-help] [-version]
        [-frames <number of frames to process>]
To pause and unpause: pkill -USR1 Protonect
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 8 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @2:1 with serial 002013164547
[Info] [Freenect2Impl] found 1 devices
[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] transfer pool sizes rgb: 3*1048576 ir: 8*64*33792
[Info] [Freenect2DeviceImpl] opened
[Info] [Freenect2DeviceImpl] starting...
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Info] [Freenect2DeviceImpl] started
device serial: 002013164547
device firmware: 4.0.3911.0
GLFW error 65543 WGL: Failed to create OpenGL context
Failed to create opengl window.

Does this error result from that Parallels Desktop 13 does not support openGL well? Do you have some alternative techniques to use this driver in a virtual Win 10 system? Thank you so much!

**Comment by xlz** [comment]
> virtual Win 10

You can't do that. Not supported.

**Comment by YANGYU106** [comment]
> > virtual Win 10
> 
> You can't do that. Not supported.

Do you mean I cannot use the driver on Virtual Win 10?

**Comment by xlz** [comment]
Virtual machines are not supported. See https://github.com/OpenKinect/libfreenect2#hardware-requirements
