### ISSUE TITLE
A issues about simulation by rviz

### ISSUE THREAD

**Issue by salo120day** [OpenKinect/libfreenect2#1039]
I use navigation stack to my robot simulation,bur when i want use the "2D pose Estimate" button to set my robot ,terminal warn me : 
[ WARN] [1542017987.602044741]: Frame ID of "initialpose" (map) is different from the global frame /map
[ WARN] [1542017987.602823922]: Failed to lookup transform!
and i add these in launch file:
  <remap from="base_pose_ground_truth" to="odom" />
  <param name="global_frame_id" value="map" />
  <param name="base_frame_id" value="base_footprint" />

but it dose't work ,some master tell me how can fix this problem

**Comment by xlz** [comment]
Doesn't seem to be related to this project.
