### ISSUE TITLE
Not found MSBuild.exe

### ISSUE THREAD

**Issue by zirop** [OpenKinect/libfreenect2#1042]
Hi, I am using Windows 10 and a visual studio 2017.
I have a problem installing this and I want to get some help

C:\Users\zirop\Desktop\kiki\libfreenect2\depends>git clone https://github.com/libusb/libusb.git libusb_src   || exit /b
Cloning into 'libusb_src'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 13071 (delta 5), reused 9 (delta 3), pack-reused 13058
Receiving objects: 100% (13071/13071), 3.52 MiB | 2.03 MiB/s, done.
Resolving deltas: 100% (9467/9467), done.

C:\Users\zirop\Desktop\kiki\libfreenect2\depends>cd libusb_src

C:\Users\zirop\Desktop\kiki\libfreenect2\depends\libusb_src>set CONFIG=Release

C:\Users\zirop\Desktop\kiki\libfreenect2\depends\libusb_src>set YEAR=2017

C:\Users\zirop\Desktop\kiki\libfreenect2\depends\libusb_src>set MSBUILD="C:\Program Files (x86)\MSBuild\15.0\Bin\MSBuild.exe"

C:\Users\zirop\Desktop\kiki\libfreenect2\depends\libusb_src>"C:\Program Files (x86)\MSBuild\15.0\Bin\MSBuild.exe" msvc\libusb_dll_2017.vcxproj /p:Platform=x64 /p:Configuration=Release /target:Rebuild   || exit /b
The system cannot find the path specified.

This is the situation in CMD.
I did a search, but it didn't work.
I want to settle this as soon as possible.

What should I do?
I will always thank you for your help.

**Comment by xlz** [comment]
You don't need to build libusb anymore. Download the official build: https://github.com/libusb/libusb/releases/tag/v1.0.22

**Comment by zirop** [comment]
thank you
I don't have to build this,I don't know where to put the file on the computer.
just libfreenect2 folder in it. also install Visual Studio 2015

now, another problem.

C:\Users\zirop\Desktop\kiki\libfreenect2\build>cmake .. -G "Visual Studio 14 2015 Win64"
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:25 (PROJECT):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:25 (PROJECT):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "C:/Users/zirop/Desktop/kiki/libfreenect2/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/zirop/Desktop/kiki/libfreenect2/build/CMakeFiles/CMakeError.log".
