### ISSUE TITLE
Install libfreenect2 on  Windows8.1 DETAILED procedure tutorial

### ISSUE THREAD

**Issue by Edwinzero** [OpenKinect/libfreenect2#105]
My build procedure is like this, I got the libfreenect2.lib and libfreenect2.dll,
and install it to `C:/Pragram files/libfreenect2`
## *****************_PRELIMINARIES**_*****************

install CUDA so that computer will have opencv...
install libjpeg-turbo
install Python...
download libtool, make from GNUWIN32 and use setup to install.
## *****************_STAGE1:**_***********************

open GIT bash which is a command console
enter below:
git clone git://github.com/OpenKinect/libfreenect2.git   //clone the project
git checkout master                                         //make sure it is release version
git pull                                                    //make the project up-to-date
## ******************_STAGE2:**_**********************

going to the direction "../depends/" then do the followings:
1. Download pre-built binaries libusbx-winiso.zip from https://www.dropbox.com/s/madoye1ayaoajet/libusbx-winiso.zip
2. Unzip into the depends folder such that the resulting folder structure ends up looking like:
   ./depends/libusbx/
   ./depends/libusbx/include/
   ./depends/libusbx/MS64/

Then, run install_deps.sh to download all the resources...
The glew_src doesn't include the glew.c file, so download another glew_src from github which include glew.c etc.. (LINK:https://github.com/omniavinco/glew-cmake)
If you want use this one, please go to `./glew_src/auto/Makefile` first then you will get corresponding missing files.
build glew with the sln in the folder. Release MX and Release for 64bit.
## *****************_STAGE3:**_*********************

Modify ./examples/Protonect/CMakeList.txt:

First, change the LIBUSB part:
`#LibUSB`
`INCLUDE_DIRECTORIES("${MY_DIR}/../../depends/libusbx/include/")`
`LINK_DIRECTORIES("${MY_DIR}/../../depends/libusbx/MS64/")`

Then, change the LINK LIBRARIES part:

```
TARGET_LINK_LIBRARIES(freenect2
  libusb-1.0
  ${OpenCV_LIBS}
  turbojpeg
  ${LIBFREENECT2_THREADING_LIBRARIES}
  glew32mxs
  glfw
  ${GLFW_LIBRARIES}
)
```
## *****************_STAGE4:**_*********************

Open Cmake,
source is libfreenect2/examples/Protonect/
build is libfreenect2/build
Press "Configure"
Then modified the link if there is error occurs, (Should not have error)
then Press Configure again until there is no error.
Then press "Generate...."

TroubleShooting: 
If you get error that 

```
 Could not find module FindOpenCV.cmake or a configuration file for package
  OpenCV.

  Adjust CMAKE_MODULE_PATH to find FindOpenCV.cmake or set OpenCV_DIR to the
  directory containing a CMake configuration file for OpenCV.  The file will
  have one of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake
```

Then configure the OpenCV_DIR_NOT_FOUND to where your opencv build folder is. Like: "opencv/build/". You can find OpenCVConfig,cmake there.
## *****************_STAGE4:**_*********************

Open /build vs libreenect2.sln....
Do not use ALL_BUILD instantly, build order:
Glfw and Generate_resource_inc, (Good )
freenect2;  (Error happens)
// SEEMS you need link Kinect2 to computer before run following projects.
test_opengl; 
Protonect; 
## *****************_STAGE5:**_*********************

unload ALL_BUILD, which will cause error on vs2013. Then right click INSTALL and choose build.
If you stick to these steps, there will be no error.

This tutorial doesn't configure OPENCL, and is there any way to use CUDA CL instead of using AMD CL on Windows?

**Comment by BenjaminRothschild** [comment]
I have done the same thing,but when I run the Protonect.exe in Win8.1 cmd,why i'm unsuccessed,like this:
[Freenect2DeviceImpl] failed to open Kinect v2 @3:7!
no device connected or failure opening the default one!
[ 0.558128] [00001f34] libusbx: debug [handle_events] poll() returned 0
[ 0.558128] [00001f2c] libusbx: debug [libusb_exit]
[ 0.558128] [00001f2c] libusbx: debug [libusb_exit] destroying default context
[ 0.558128] [00001f2c] libusbx: warning [libusb_exit] some libusb_devices were leaked
[ 0.559128] [00001f2c] libusbx: warning [libusb_exit] application left some devices open
[ 0.559128] [00001f2c] libusbx: debug [usbi_remove_pollfd] remove fd 0
[ 0.559128] [00001f2c] libusbx: debug [usbi_remove_pollfd] remove fd 1
[ 0.560128] [00002320] libusbx: debug [windows_clock_gettime_threaded] timer thread quitting

**Comment by Edwinzero** [comment]
@BenjaminRothschild It seems like there is sth wrong with your libusbx library. 
You can just use VS2013 build it, have you install Kinect2 SDK from MS? You must install it before you doing these stuffs.

**Comment by BenjaminRothschild** [comment]
hi,sorry for no replies for a long time,I just achieve the other things.I did  rebuild the libusb with VS2012, and also the libfreenect project.and both have a try in VS2013. But,there also something wrong with it:
C:\Users\benjamin>E:\pro_VS\libfreenect2-master\examples\protonect\bin\Debug\Protonect.exe
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 10 usb devices connected
[Freenect2Impl] failed to open Kinect v2 @3:4!
[Freenect2Impl] found valid Kinect v2 @3:4 with serial 500344540242
[Freenect2Impl] found 1 devices
[Freenect2DeviceImpl] opening...
[UsbControl::claimInterfaces(IrInterfaceId)] failed! libusb error -12: LIBUSB_ERROR_NOT_SUPPORTED
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] deallocating usb transfer pools...
[Freenect2DeviceImpl] closing usb device...
[Freenect2DeviceImpl] closed
[Freenect2DeviceImpl] failed to open Kinect v2 @3:4!
no device connected or failure opening the default one!
so,I have no ideas now.Do you have any other solution?

**Comment by Edwinzero** [comment]
@BenjaminRothschild  It seems like there is something wrong with your libusb, Could you tell me which version of libusb you are using? 

Have you done following procedure?
f you have the Kinect for Windows v2 SDK, install it first. You don't need to uninstall the SDK or the driver before doing this procedure.

Install the libusbK backend driver for libusbx:

Download Zadig from http://zadig.akeo.ie/.
Run Zadig and in options, check List All Devices and uncheck Ignore Hubs or Composite Parents
Select the Xbox NUI Sensor (composite parent) from the drop-down box. (Ignore the Interface 0 and Interface 2 varieties.) The current driver will list usbccgp. USB ID is VID 045E, PID 02C4.
Select libusbK (v3.0.6.0) from the replacement driver list.
Click the Replace Driver button. Click yes on the warning about replacing a system driver. (This is because it is a composite parent.)
Done.

**Comment by BenjaminRothschild** [comment]
thanks very much,it's solved now,in the step of zading I selected the Xbox NUI Sensor Interface 0,so failed,I have changed as your said.can you tell me why select the (composite parent),not others?

**Comment by Edwinzero** [comment]
I think if you look into the interface part of libfreenect2 you will find the setting is matching with the interface 0.

**Comment by vedanshu95** [comment]
hi, 

i am trying to follow these steps but i am finding error in cmake. kindly help me out with these 
here is the pic i have shared.

![error](https://cloud.githubusercontent.com/assets/12307323/7616951/fdb86d0e-f95c-11e4-8408-9e13920b8e5d.jpg)

**Comment by Edwinzero** [comment]
@vedanshu95  You don't have OpenCL DIR in your cmake configuration. Please check the installation tutorial in #211
