### ISSUE TITLE
Obtaining phase images possible?

### ISSUE THREAD

**Issue by amritrajck** [OpenKinect/libfreenect2#1057]
Is it possible to obtain the 3*3 phase images (3 modulations frequencies and 3 phase shifts for all 3 modulation frequencies) for a particular depth image? If yes, could you please explain how?

**Comment by floe** [comment]
See discussion at #821, I think this should be a good starting point.

**Comment by amritrajck** [comment]
What is the format of the phase images? I mean what dimensions and values?
