### ISSUE TITLE
Separate Driver from "GL" stuff and cleanup folder structure

### ISSUE THREAD

**Issue by goldhoorn** [OpenKinect/libfreenect2#107]
I just figured out by adding your driver to rock (www.rock-robotics.org) that it has several dependencies to GL stuff.

Would it not make more sense to create a "clean" only driver, instead mixing this with visualization stuff?
The real-driver seems to be in examples/ and there the "libfreenect2" target from the CMakeLists.
Do you have any reasons for this structure?
I would like to create a "clean" only driver. The folder structure could be like:

src/
include/
test/

Where in test Protonoect goes. I would like also like to change the DefaultPacketPipeline to NOT use GL stuff. And create a GLPacketPipeline instead. The GLPacketPipeline headers could then be activated or deactivated by Cmake. This would reduce the amount of dependencies libfreenect has.

Before i start with this i would like to have the opinion from the responsible "core" developers.

Best,
Matthias

**Comment by floe** [comment]
Sorry, forgot to mention that there is a CPUDepthPacketPipeline, but even a big Core i7 won't be sufficient to get realtime processing.
