### ISSUE TITLE
What is the libfreenect2 license?

### ISSUE THREAD

**Issue by fishcu** [OpenKinect/libfreenect2#1080]
See title.

I have found two seemingly license-related files in the root of the repository, APACHE20 and GPL2.
However I could not find which one of these licenses applies to the code base of libfreenect2 as a whole. Please clarify!

Can the license be chosen at will? Or is there some other mechanism how the licensing works?

I have found a similar description for the libfreenect2-openni2 dependency:
```
This code is licensed to you under the terms of the Apache License, version
2.0, or, at your option, the terms of the GNU General Public License,
version 2.0. See the APACHE20 and GPL2 files for the text of the licenses,
or the following URLs:
[...]
```

**Comment by fishcu** [comment]
Bump.

@floe Do you happen to know?

**Comment by fishcu** [comment]
This website mentions license as "other (open)": https://zenodo.org/record/50641

**Comment by floe** [comment]
Disclaimer: IANAL, but as far as I understand, you are free to choose which of both licenses to apply to your derivative works.

**Comment by fishcu** [comment]
Thank you for the confirmation!
