### ISSUE TITLE
Problem to include libraries in Ubuntu

### ISSUE THREAD

**Issue by manurare** [OpenKinect/libfreenect2#1094]
Overview Description:
Hi! I am not very familiar with cmake but I have been trying to install the library on my home directory. Everything works fine and I can execute the example file /libfreenect2/build/bin/Protonect. 

The problem comes when creating myself a cpp file and including the header
`
#include<libfreenect2/libfreenect2.hpp>
`
It pops the error that this directory does not exist as it is lying in 
`
/home/manuel/freenect2/include/libfreenect2/libfreenect2.hpp
`
How can I somehow tell the compiler to search in that directory without explicitly indicate the whole path?

Version, Platform, and Hardware Bug Found:

1. da68a71 (HEAD -> master, origin/master, origin/HEAD) Update TegraJPEG detection
2. Linux manuel-H81M-HD3 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
3. /:  Bus 06.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
/:  Bus 05.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 5000M
    |__ Port 1: Dev 6, If 0, Class=Hub, Driver=hub/1p, 5000M
        |__ Port 1: Dev 7, If 0, Class=Vendor Specific Class, Driver=, 5000M
        |__ Port 1: Dev 7, If 1, Class=Vendor Specific Class, Driver=, 5000M
        |__ Port 1: Dev 7, If 2, Class=Audio, Driver=snd-usb-audio, 5000M
        |__ Port 1: Dev 7, If 3, Class=Audio, Driver=snd-usb-audio, 5000M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/10p, 480M
    |__ Port 1: Dev 7, If 0, Class=Hub, Driver=hub/1p, 480M
    |__ Port 4: Dev 3, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
    |__ Port 5: Dev 4, If 2, Class=Audio, Driver=snd-usb-audio, 12M
    |__ Port 5: Dev 4, If 0, Class=Audio, Driver=snd-usb-audio, 12M
    |__ Port 5: Dev 4, If 3, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 5: Dev 4, If 1, Class=Audio, Driver=snd-usb-audio, 12M
    |__ Port 6: Dev 5, If 0, Class=Mass Storage, Driver=usb-storage, 480M
    |__ Port 6: Dev 5, If 1, Class=Human Interface Device, Driver=usbhid, 480M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/2p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/6p, 480M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/2p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M

4. 00:14.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI (rev 05)
00:1a.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 (rev 05)
00:1d.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 (rev 05)
06:00.0 USB controller: VIA Technologies, Inc. VL805 USB 3.0 Host Controller (rev 01)

**Comment by xlz** [comment]
You need to specify cmake -Dfreenect2_DIR=$HOME/freenect2/lib/cmake/freenect2 for CMake based third-party application to find libfreenect2.
