### ISSUE TITLE
"Kinect for Windows V2" vs "Kinect for Xbox One + Windows Adaptor"

### ISSUE THREAD

**Issue by andstein** [OpenKinect/libfreenect2#1101]
Is the "Kinect for Windows v2 (K4W2)" identical with a "Kinect for Xbox One + Windows Adaptor"?

(I plan to use the Kinect with Linux / OS X, and while [the README] states that libfreenect2 supports "Driver for Kinect for Windows v2 (K4W2) devices", I only find [offers like] "GENUINE KINECT V2 WITH ADAPTER FOR XBOX ONE S , X & PC" on eBay ... [some webpages] claim they're identical in how they function, but I'd rather know for sure before ordering)

[the README]: https://github.com/OpenKinect/libfreenect2/issues/25
[offers like]: https://www.ebay.ch/itm/283266429752
[some webpages]: https://docs.depthkit.tv/docs/kinect-for-windows-v2

**Comment by floe** [comment]
Yes, they are functionally identical. I've used both with libfreenect2.
