### ISSUE TITLE
fatal: repository 'https://github.com/xlz/libusb.git/' not found

### ISSUE THREAD

**Issue by gzg9901** [OpenKinect/libfreenect2#1104]
Branch Master
run in Windows Power Shell，looks like repository is missing
 
.\install_libusb_vs2013.cmd                      
git clone https://github.com/libusb/libusb.git libusb_src   || exit /b
Cloning into 'libusb_src'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 13807 (delta 26), reused 31 (delta 5), pack-reused 13747
Receiving objects: 100% (13807/13807), 3.88 MiB | 28.00 KiB/s, done.
Resolving deltas: 100% (9984/9984), done.

git remote add xlz https://github.com/xlz/libusb.git
git fetch xlz   || exit /b
remote: Repository not found.
fatal: repository 'https://github.com/xlz/libusb.git/' not found
PS E:\Github\libfreenect2-0.2.0\depends>

**Comment by xlz** [comment]
Use master https://github.com/OpenKinect/libfreenect2/blob/master/depends/install_libusb_vs2013.cmd
