### ISSUE TITLE
Multiple read access to one Kinect v2

### ISSUE THREAD

**Issue by mnemllr** [OpenKinect/libfreenect2#1112]
Hello,

I want to use one Kinect v2 camera for multiple applications on one computer. If I try to to get access with a second application using libfreenect2, both applications crash. 
Is it somehow possbile to do that? 

I am using Ubuntu 16.04.

Thank you.

**Comment by floe** [comment]
I guess the easiest way to do that would be to use ROS as middleware, and https://github.com/code-iai/iai_kinect2 as Kinect v2 driver.

**Comment by mnemllr** [comment]
Thanks for your answer.
So with libfreenect2 it is not possible, right?
Because one of the apps is an open source software which is using libfreenect2. I do not want to change their code base.

**Comment by floe** [comment]
Correct, libfreenect2 assumes exclusive hardware access, so two separate instances will just crash.
