### ISSUE TITLE
Kinect2 over LAN?

### ISSUE THREAD

**Issue by ManuelCostanzo** [OpenKinect/libfreenect2#1117]
Hello, i want to make a simple question. Can i share kinect2 frames over LAN ? For example using USB/IP. How many MB/s kinect2 sends ?

Thank you !

**Comment by floe** [comment]
The raw datastream from a Kinect v2 is roughly 5 GBit/s, close to the maximum of what a single USB 3.1 connection can deliver. Please join the related discussion at #1103 .
