### ISSUE TITLE
[Error] [OpenGLDepthPacketProcessorImpl] GLFW error 65542 GLX: GLX version 1.3 is required

### ISSUE THREAD

**Issue by azhuantou** [OpenKinect/libfreenect2#1133]
Hello, I have a quesetion. When I run ./Protonect, it doesn't work. Is there anyone who can help ?

Version: 0.2.0
Environment variables: LOGFILE=<protonect.log>
Usage: ./Protonect [-gpu=<id>] [gl | cl | clkde | cuda | cudakde | cpu] [<device serial>]
        [-noviewer] [-norgb | -nodepth] [-help] [-version]
        [-frames <number of frames to process>]
To pause and unpause: pkill -USR1 Protonect
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 9 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @1:24 with serial 001174145347
[Info] [Freenect2Impl] found 1 devices
[Error] [OpenGLDepthPacketProcessorImpl] GLFW error 65542 GLX: GLX version 1.3 is required
[Error] [OpenGLDepthPacketProcessor] Failed to create opengl window.

**Comment by floe** [comment]
Well: `GLX version 1.3 is required`. Whatever environment you're running it on (Wayland? Xorg?) doesn't provide a GLX 1.3 context.
