### ISSUE TITLE
Opencl depth packet processor no longer works..

### ISSUE THREAD

**Issue by metallo25** [OpenKinect/libfreenect2#114]
I have been using this version of libfreenect2(https://github.com/wiedemeyer/libfreenect2) for a while and it was working well with opencl depth packet processing. 

But recently after some system updates, the opencl depth packet processing no longer works. It is giving this error:
"[OpenCLDepthPacketProcessor::init] ERROR: clGetPlatformIDs(-1001)
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)"

I was able to use the cpu depth processing and still get the sensor working, but it much slower compared to before for my task. 

I am working on ubuntu 14.04(64 bit), ros indigo and NVIDIA Corporation GK106 [GeForce GTX 660] controller

I still want to use the opencl depth packet processor and not cpu. Please let me know what to do, Thank you!

**Comment by bassofil** [comment]
I'm having the same problem.
The strange fact is that `examples/protonect/bin/Protonect` still works as usual.

**Comment by floe** [comment]
Discussion has moved to #153, closing.
