### ISSUE TITLE
How do I save the paired depth and RGB image？

### ISSUE THREAD

**Issue by azhuantou** [OpenKinect/libfreenect2#1146]
hello,
I successfully installed it on Ubuntu. Can anyone tell me  how to save the paired depth and RGB image？
tks

**Comment by KP1-cmd** [comment]
@azhuantou hello,Did you get solution for saving RGB and depth images?

**Comment by azhuantou** [comment]
@KP1-cmd yes,I solved the problem by follow https://github.com/r9y9/pylibfreenect2 .

**Comment by KP1-cmd** [comment]
ok thank you @azhuantou
