### ISSUE TITLE
The windows of ir and depth stay black

### ISSUE THREAD

**Issue by hiwasawa** [OpenKinect/libfreenect2#117]
I downloaded libfreenect2-master on Github 12/15.
I tried run the solution libfreenect2_vs2013.
and I confirmed the following contents.

	1:Rgb,Ir,Depth Windows are start.
	2:At the Rgb window, I can see color picture from K4W2.
	3:But at the Ir and Depth windows stay black.

I tried setting some breakpoints on the codes.
and I confirmed the following contents.

	4:At upload on opengl_depth_packet_processor.cpp
	  There is the code "glTexSubImage2D(GL_TEXTURE_RECTANGLE, /*level*/0, /*xoffset*/0, /*yoffset*/0, width, height, FormatT::Format, FormatT::Type, data);"
	  the data value is maybe depth data.
	  
	  but, the process method on opengl_depth_packet_processor.cpp.
	  in the run method,
	  line 625 "*depth = filter2_depth.downloadToNewFrame();"
	  the value of "data  of depth" are all "00".
	  
	  I think lack glFlush()?
	  
	  or, failing OpenGL library?
	  I use OpenGL32.Lib at "C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x64".
	  

I want to get depth data without Kinect SDK.
I want to show the depth data on depth window!
So, please give me advice.

----------------------------------------------------
my Application Development Environment
windows 8.1
visual studio 2013

Whent I builded example's project.
I changed the 157 line Code to "ADD_LIBRARY(freenect2 STATIC ${SOURCES})" at the file CMakeLists.txt. 
Because I want to make freenect2.lib.

I could't build the INSTALL project.
There is some error.
![onlyrgb](https://cloud.githubusercontent.com/assets/5299882/5503440/1eb9f78a-87ba-11e4-9d30-5d5f6f110746.jpg)
![debug](https://cloud.githubusercontent.com/assets/5299882/5503531/586895ee-87bb-11e4-876d-5430ba7dcab6.jpg)

**Comment by christiankerl** [comment]
your first comment mentioned you are using OpenGL 3.2. the OpenGLDepthPacketProcessor requires OpenGL 3.3. is this the problem?

**Comment by Nican** [comment]
Hello! 
I am having the similar issue, I an running Ubuntu 14.10, with an Intel HD 4000, with OpenGL version 3.0.
I am trying to compile the larshg/libfreenect2, on the develop branch, but I am having a hard time getting it compile: It says that it can not link against the TurboJPEG library: "No rule to make target `/opt/libjpeg-turbo/lib/libturbojpeg.a`, needed by `cmTryCompileExec1603162789`" 

I compiled, and installed, libjpeg-turbo 1.4.0 from source, and the problem persists. And said .a file does exist. 

Suggestions?

**Comment by floe** [comment]
@Nican see #36 for a possible fix. Closing here.

**Comment by floe** [comment]
Oops, sorry, my mistake. Reopening.

**Comment by gerbyzation** [comment]
Hi!
I'm having the same issue running the Protonect example on mac, only the camera feed is displayed.
I've tried installing larshg branches, but they both fail to install. The develop branch fails on cmake, even with env variable set for libusb path it can't find it. the DepthRegistration branch fails on `make && make install`, not being able to find the `omp.h` file.

Any suggestions?

**Comment by pjryan93** [comment]
Same happening on macbook pro late 2011.  The rgb window also shows up as pink.

**Comment by Nican** [comment]
A temporary fix for me was to force createDefaultPacketPipeline to return new CpuPacketPipeline(). 
https://github.com/OpenKinect/libfreenect2/blob/master/examples/protonect/src/libfreenect2.cpp#L611

**Comment by gaborpapp** [comment]
@pjryan #171 fixed this for me on a macbook pro, although I hasn't experienced pink rgb.

**Comment by pjryan93** [comment]
#171 fixed my problems, still only getting red and pink values from rgb, but glad to have ir and depth working.  Thanks!
