### ISSUE TITLE
Add support for Linux ARM to libfreenect2

### ISSUE THREAD

**Issue by oscarbg** [OpenKinect/libfreenect2#13]
Hi,
don't know if it works by default but with Jetson K1 having linux on arm with cuda etc.. and USB 3.0 I would like to run kinect2 once released on this platform jointly with VisionWorks and would be nice that both freenect and freenect2 libraries have support for Linux on ARM..

**Comment by floe** [comment]
This is being actively worked on, so I'm closing the issue.
