### ISSUE TITLE
Crash/inf. loop on closing the device

### ISSUE THREAD

**Issue by djgaspa** [OpenKinect/libfreenect2#137]
The member TransferPool::pending_transfer_ is actually shared among the EventLoop and the thread calling Freenect2DeviceImpl::stop.

Hence, it needs to be mutex protected in order to avoid the program crashes or hungs up on exit.

A simple workaround is to wait a little (2 secs) between disableSubmission and cancel in the method Freenect2DeviceImpl::stop

**Comment by floe** [comment]
Could you submit a pull request with a fix?

**Comment by xlz** [comment]
Proposed fixes are in #212.

**Comment by xlz** [comment]
Fixed by #275.
