### ISSUE TITLE
Question about Depth range

### ISSUE THREAD

**Issue by MasWag** [OpenKinect/libfreenect2#152]
Hello all

I am using libfreenect2 with OpenCL and it seems no point further than 4.5m can be seen. But with Microsoft SDK, I cound see about 8m distant point.Is this expected behavior?

This is my environment

* OS : Ubuntu 14.10
* CPU : Intel(R) Core(TM) i7-3630QM 
* GPU : NVIDIA Corporation GF108GLM

Regards,
Masaki Waga

**Comment by tlind** [comment]
Looks like a duplicate of this issue: #143

**Comment by MasWag** [comment]
Sorry,I didn't read it. I tried and it works well. 
Thanks.
