### ISSUE TITLE
Turning down IR intensity

### ISSUE THREAD

**Issue by jeppewalther** [OpenKinect/libfreenect2#155]
Have anyone found / investigated a way to turn down the intensity of the IR light source. In order to achieve a near field mode. 

I am currently experimenting with adding physical filters in front of the light source witch seems to work. But it would be much cleaner to simply do this in software.

**Comment by christiankerl** [comment]
There was a email by Microsoft announcing an experimental near range firmware to be testable at some hackathon. So I guess this requires a different firmware.

**Comment by xlz** [comment]
Also see alternative discussion on turning it off #338.

**Comment by floe** [comment]
Coming back to this old thread, did anyone ever actually have access to this rumoured near-mode FW?

**Comment by fred-dev** [comment]
> Have anyone found / investigated a way to turn down the intensity of the IR light source. In order to achieve a near field mode.
> 
> I am currently experimenting with adding physical filters in front of the light source witch seems to work. But it would be much cleaner to simply do this in software.

I also looking for some kind of solution for this, can you share what kind of physical filters you are using to achieve this? Primarily I am using the kinect with an HTC vive and getting a lot of interference..

**Comment by floe** [comment]
What I used at one point was simply a stack of 1-3 post-it notes in front of the IR emitter. Worked surprisingly well.
