### ISSUE TITLE
Segfault 11 (on mac)

### ISSUE THREAD

**Issue by julienaubert** [OpenKinect/libfreenect2#185]
Regardless if I use OpenCL, CPU, or OpenGL.

[OpenCLDepthPacketProcessor] avg. time: 19.8993ms -> ~50.2531Hz
q[Freenect2DeviceImpl] stopping...
[Freenect2DeviceImpl] disabling usb transfer submission...
[Freenect2DeviceImpl] canceling usb transfers...
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
libusb: error [darwin_cancel_transfer] unknown endpoint type 49
libusb: error [libusb_cancel_transfer] cancel transfer failed error -2
Segmentation fault: 11

**Comment by floe** [comment]
Does this happen when you quit, or randomly at some point during runtime?

**Comment by julienaubert** [comment]
Each time when I quit.

**Comment by floe** [comment]
OK, in this case, can you try to run Protonect from gdb and post a stacktrace from the segfault?

**Comment by julienaubert** [comment]
Actually, it only occurs if I ctrl-c to exit. Running with gdb (using signal cmd in gdb to pass it to program):

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000000000000
libfreenect2::usb::TransferPool::cancel (this=0x10130e268) at /Users/julien/Documents/projects/libfreenect2/examples/protonect/src/transfer_pool.cpp:114
114	    int r = libusb_cancel_transfer(*it);

**Comment by xlz** [comment]
Fixed by #275.
