### ISSUE TITLE
protonect_vs2013 (incompatible)

### ISSUE THREAD

**Issue by Rosehart** [OpenKinect/libfreenect2#194]
Hi, 

I'm trying to connect a Kinect v2.0 to my Windows 7 laptop. Installation seemed to go well but when I try to open de sln file in visual studio it says "ptotonect_vs2013 (incompatible) the application is not installed."

I didn't install the Windows SDK because I can't on Windows 7, hence the reason I want to use this project.

Did I miss something or did something go wrong?

**Comment by floe** [comment]
You need to generate a new solution file using Cmake, the one that was included is entirely broken.

**Comment by Edwinzero** [comment]
Hi, @floe

I just wonder that is libfreenect2 only work on x64? I want to do some implements on Win32. So if I use libusb-1.0 win32 and set all the dependencies to win32 version, is that possible to make libfreenect2 work?

**Comment by floe** [comment]
This has long been superseded by the refactored build system & instructions, closing.
