### ISSUE TITLE
Request for DLL and LIB file

### ISSUE THREAD

**Issue by dinprojector** [OpenKinect/libfreenect2#197]
I'm trying to build libfreenect2 following istruction <a href="https://github.com/OpenKinect/libfreenect2/issues/105"> here</a>.
After that i failed to build with the proceudre described at beginning. 
I need to test this driver fory mutlikinect support fast as possible.
Has anyone the possibility to uplodad binaries of libfreenect2?

I need to make it work on windows 8, with VS 2012.

I will appreciate really any help,
Thank you.

**Comment by floe** [comment]
I don't think that will make much sense, as libfreenect2 is still very much a work in progress; DLL/LIB files only will be useful once we've reached an initial feature freeze & release. If you post some more detailed error descriptions, maybe somebody will be able to help you here.

**Comment by dinprojector** [comment]
You are right, i will describe my building procedure.

**Comment by DemonEater** [comment]
Will detailed instructions on installation be provided when you've reached freeze and release? I was following the same instructions as dinprojector, but had very little success.

**Comment by Edwinzero** [comment]
Hey guys,
 
He is using the instruction I write...
I try to build libfreenect2 in Win32 and I get the result like below
![image](https://cloud.githubusercontent.com/assets/5100412/7307355/54f502ae-e9da-11e4-98b3-6ba6a6350322.png)
![image](https://cloud.githubusercontent.com/assets/5100412/7307367/68f1c31e-e9da-11e4-9b98-47ecf97120ab.png)

A

**Comment by Edwinzero** [comment]
Hello @larshg ,

Sorry for bother you again, could you give me some suggestion about my problem?

**Comment by larshg** [comment]
Hi @Edwinzero 

Yes, you also need the libjpeg-turbo on windows for handling the RGB data.

Since you get errors with the USB - you are using USB 3.0 ? Can you try another USB controller?

Else it seems fine.

**Comment by Edwinzero** [comment]
Hi @larshg ,

Yes I am using USB 3.0. So Kinect v2 is not support USB 3.0? I think I am using the SATA usb 3.0 interface... I will change and try~

Thank you very much man!

**Comment by larshg** [comment]
@Edwinzero the kinect v2 requires USB 3.0 - it was just to verify :) I don't know how the SATA usb 3.0 and the belonging chipset works - so if you can try another USB port with a proper chipset, this could probably make it work.

Perhaps updating the drivers for the USB/SATA controller could also solve it.

**Comment by Edwinzero** [comment]
Hi @larshg ,

I change it back to 64bit since I create a sensor network interface in 64bit. But I compile all the libraries without error but when I run Protonect.ext there is an error.
![image](https://cloud.githubusercontent.com/assets/5100412/7321399/eecb0136-ea6f-11e4-8861-1c9a648d30d8.png)

Do you have any ideas?

**Comment by larshg** [comment]
Hmm as I remember this is normally due to mixing 32 and 64 bit libs, or using unsupported instruction set.
try to use dependency walker and see if it unintentionallyder links to a wrong library.

**Comment by Edwinzero** [comment]
Hi @larshg, I think I am using all the dependencies in x64 bit. 
Here is my dependencies.
![image](https://cloud.githubusercontent.com/assets/5100412/7323263/3ed8e674-ea7b-11e4-9dcf-88b0c0f8922a.png)
And the libusb I am using is from libusbx-winso.zip 
And the turbo-jpeg I am using is 64 bit, too... 
![image](https://cloud.githubusercontent.com/assets/5100412/7323312/903ecbfa-ea7b-11e4-91a5-4aea374c99ed.png)

Is there any possibility? I didn't use CUDA on my computer and I am using AMD opencl for now.

**Comment by Edwinzero** [comment]
I figure it out, I set x86 of opencv in my system variable.... Thanks a lot!

**Comment by elliotwoods** [comment]
Agree there should be binary releases (even with warnings/expectations of it not working)
especially 'bury' the binary releases within the readme

i've linked to my build from here:
https://github.com/OpenKinect/libfreenect2/issues/244
