### ISSUE TITLE
Protonect just crashes on OSX

### ISSUE THREAD

**Issue by procrash** [OpenKinect/libfreenect2#200]
Hi,

I started protonect with my Kinect One Sensor and compiled everything like the web page said but I just get a crash as soon as data seems to be retrieved from the Kinect Sensor.

There is also no picture displayed. Digging from the code it seems that the 
cv::imshow("rgb", cv::Mat(rgb->height, rgb->width, CV_8UC3, rgb->data));

did the crash

**Comment by floe** [comment]
Is this fixed with 0.1-rc1? If not, please re-open.
