### ISSUE TITLE
unable to locate package libturbojpeg

### ISSUE THREAD

**Issue by brant203** [OpenKinect/libfreenect2#209]
When trying to install dependencies by using "sudo apt-get install -y build-essential libturbojpeg libtool autoconf libudev-dev cmake mesa-common-dev freeglut3-dev libxrandr-dev doxygen libxi-dev libopencv-dev automake" I get the error "unable to locate packge libturbojpeg." Is there any way to fix this?
edit: I am trying to get this to work on a raspberry pi running rasbian.

**Comment by xlz** [comment]
apt-get install libjpeg-turbo8-dev

**Comment by brant203** [comment]
I'm getting the same error. It is important for me to note that I am trying to do this on a raspberry pi running rasbian.

**Comment by xlz** [comment]
Try with apt-file:

`sudo apt-get install apt-file && sudo apt-file update && apt-file search libturbojpeg.so`

**Comment by brant203** [comment]
apt-file search libturbojpeg.so did not return any results. Does this mean that there are no packages with the libturbojpeg.so file in it? Do I need to add a repo or something?

**Comment by wiedemeyer** [comment]
@brant203: As far as I know the raspberry pi has only USB 2.0. And from our experience the Kinect2 requires a USB 3.0 port to work.

**Comment by brant203** [comment]
I thought usb 3.0 is backwards compatible.

**Comment by wiedemeyer** [comment]
You can plug it in, it will be detected, but you probably won't receive any data.

**Comment by brant203** [comment]
hmmm. Is there any way to make it work that you know of?

**Comment by wiedemeyer** [comment]
Normally I would suggest to get a PCIe USB 3.0 controller card. But that won't work with the raspberry pi.

**Comment by brant203** [comment]
Is there a way to use the GPIO pins?

**Comment by wiedemeyer** [comment]
probably no.

**Comment by brant203** [comment]
hmmm. ok so it is for sure that I will get no data if i try to use this on my pi?

**Comment by wiedemeyer** [comment]
You could try, but the chances for it to not work are pretty high.

**Comment by floe** [comment]
It's 100% sure that the Kinect v2/One will not work with any Raspberry Pi. You need an embedded board with native USB3 support, such as the Arndale boards or the Odroid-XU. Even then, nobody has tested these yet AFAIK.

**Comment by floe** [comment]
BTW, to address the original bug regarding libturbojpeg.so, this is very likely a duplicate of #36 - closing.

**Comment by baomin** [comment]
sudo apt-get install apt-file && sudo apt-file update && apt-file search libturbojpeg.so
