### ISSUE TITLE
Failed to synchronize two Kinectv2 RGB and Depth images

### ISSUE THREAD

**Issue by Edwinzero** [OpenKinect/libfreenect2#218]
Hello guys,

I have already implemented two Kinect v2 on one computer without realtime refresh rate( fps: 18-22)
But there is huge distortion on time sequence between these two devices.
Is there any ideas for synchronizing two Kinect v2 so that we can make sure each pair of frames from same time stamp will be aligned?

**Comment by Edwinzero** [comment]
Hey guys,  @larshg  @JoshBlake  @BenjaminRothschild

I found that libfreenect use pthread for multiple threading. If I use pthread instead of using Windows default thread libraries, will the performance be better. Maybe reach 30fps for both?

**Comment by floe** [comment]
USB is notoriously bad at synchronizing different devices, even on the same bus, so I'm not sure if there is much you can do about it. Performance may of course be a secondary issue here.

**Comment by jonnycowboy** [comment]
Probably two different paths to fix the issue completely - 1) as @floe says, performance is an issue, a faster computer would help.  2) use an external identifier (flashing LED, clock, something similar) that the Kinect reads through its camera and synchronizes itself every minute or two...

**Comment by Edwinzero** [comment]
Hey guys, I am trying to use parallel USB 3.0 board to test two Kinect. I will give you guys a reply after I done that.

**Comment by floe** [comment]
Is this fixed with 0.1-rc1? If not, please re-open.
