### ISSUE TITLE
Kinect2 Serial Number

### ISSUE THREAD

**Issue by dvonhausen** [OpenKinect/libfreenect2#219]
I have libfreenect2 running fine on my box and now I want to run with two Kinects. I read the other threads on this and my question is how do I run two instances of Protonect and specify the serial numbers of each Kinect? It appears that Protonect just uses the first Kinect that it finds.

**Comment by Edwinzero** [comment]
Please check this issue#211

**Comment by dvonhausen** [comment]
Thanks - it looks like what I need but its for Windows. Is there code for this that is ported to linux/ubuntu?

**Comment by Edwinzero** [comment]
@dvonhausen 
I think you can use pthread on Linux, which is I am trying to do on windows right now. If you have solution to make two Kinect2 both in real-time(30fps), I hope you could let me know.

**Comment by floe** [comment]
This will be addressed by PR #82 (or its successor). Closing here.
