### ISSUE TITLE
how to get Depth Camera's Intrinsics parameters?

### ISSUE THREAD

**Issue by wangsen1312** [OpenKinect/libfreenect2#234]
How can I use libfreenect2 to get Depth Camera's Intrinsics parameters?
Can anyone give me some suggestion? Thank you very much!

**Comment by JuantAldea** [comment]
Check file libfreenect2.cpp, Freenect2Device::IrCameraParams getIrCameraParams();

**Comment by bellekci** [comment]
Are the parameters returned by getIrCameraParams retrieved from the device?
Weren't parameters hardcoded in libfreenect2 which has also caused the offset problem as mentioned #144.

I just went through the master and it seems to me that they are read from the device. Just wanted to confirm to be sure.

**Comment by floe** [comment]
The intrinsics are read directly from the device; they only relate to the geometric camera/lens parameters (see also registration.cpp). The stuff discussed in #144 relates to the depth calculation/deconvolution and is indeed still hardcoded.

**Comment by zardchim** [comment]
@floe  is there any comment on the accuracy of the camera parameter? I saw there is calibration tool in the ubuntu ros package, do we have similar feature in Windows? or could I do the calibration on my own and use my own parameter instead @@?

**Comment by floe** [comment]
A well-done chessboard calibration with an external calibration tool will very likely be of better quality than the factory-programmed calibration. However, it's difficult to directly compare them, as the factory calibration uses a different method for calculating, e.g. distortion, than common packages like OpenCV.

**Comment by zardchim** [comment]
In libfreenect2.cpp

**Comment by zardchim** [comment]
In libfreenect2.cpp there are functions to get rgb_camera_params_ & ir_camera_params_ in order to do registration, is it possible for us to replace these parameters to those generated from opencv (e.g. from iai_kinect calibration result) ?

**Comment by floe** [comment]
It might work for IrCameraParams; the format/algorithm for ColorCameraParams is different from the one OpenCV uses (IrCameraParams is just intrinsic & distortion parameters, ColorCameraParams is a mix of intrinsic & extrinsic parameters).

**Comment by lakehanne** [comment]
Oh I see. And this explains #144.
