### ISSUE TITLE
LIBUSB_ERROR_BUSY:  Could it work on USB2.0?

### ISSUE THREAD

**Issue by KahnShi** [OpenKinect/libfreenect2#235]
Actually, I worked it fine in my laptop with USB3.0.
Then I tried it to another computer which only has USB2.0, however ./Protonect couldn't work, just the same as https://github.com/OpenKinect/libfreenect2/issues/132 shows.
I also notice that some issues such as https://github.com/OpenKinect/libfreenect2/issues/160 and https://github.com/OpenKinect/libfreenect2/issues/231 talk about USB2.0 and USB3.0.
So is there really no way that we could use it on USB2.0?
BTW, my kernal is 3.16.
THX!

Kahn

**Comment by gaborpapp** [comment]
Kinect2 is an USB3 device, it won't work with USB2.
