### ISSUE TITLE
Permission denied (publickey) on Os X Yosemite 10.10.3

### ISSUE THREAD

**Issue by marmanda** [OpenKinect/libfreenect2#255]
Hi. I get this error while typing the following command:
OpenKinect/libfreenect2.git
Cloning into 'libfreenect2'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by JuantAldea** [comment]
You should clone using HTTPS instead of SSH.

**Comment by gaborpapp** [comment]
https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-recommended
