### ISSUE TITLE
I can't find any stock.

### ISSUE THREAD

**Issue by hanyazou** [OpenKinect/libfreenect2#285]
I was noticed there aren't any stock of the adaptors in local resellers. Out of stock completely. I'm afraid that it might be discontinued. Any one have any information about this?

**Comment by floe** [comment]
My local Microsoft online store (Germany) has them available, and some 3rd-party retailers, too. Temporarily out of stock, probably?

**Comment by hanyazou** [comment]
I found this page http://www.microsoft.com/en-us/kinectforwindows/purchase/
Some MS stores in the world have some stock while the stores have no stock in my region.
OK. I will wait for them back. Sorry for disturbing.
