### ISSUE TITLE
skipping depth packet

### ISSUE THREAD

**Issue by KahnShi** [OpenKinect/libfreenect2#296]
Hi everyone,
I do all the things according to the readme.md.
However when I run ./Protonect, 
if I use ./Protonect cpu, both rgb and depth image could work, but the output prints that
```
[DepthPacketStreamParser::onDataReceived] skipping depth packet
```
And sometimes also
```
[RgbPacketStreamParser::onDataReceived] skipping rgb packet!
```
if I use ./Protonect gl, it is similar to cpu mode.

if I use ./Protonect cl, it failed, and output prints that
````
./Protonect: /usr/lib/x86_64-linux-gnu/libOpenCL.so.1: no version information available (required by /home/Documents/sources/libfreenect2/examples/protonect/lib/libfreenect2.so)
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 11 usb devices connected
[Freenect2Impl] found valid Kinect v2 @4:11 with serial 022519243547
[Freenect2Impl] found 1 devices
[OpenCLDepthPacketProcessor::init] ERROR: clGetPlatformIDs(-1001)
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)
```

I have 2 questions.
1. Is everything OK if it prints "skipping depth packet" in CPU/gl mode, although I could get both rgb and depth image?
2. How could I make cl mode run? It is important to me because CPU mode is too slow and also affects the use of iai_kinect2...
I tried to add sudo before ./Protonect as others` advice, but it doesn`t work.
THX!

**Comment by xlz** [comment]
1. It is received 30 depth packets per second. If you don't see 30 warnings per second, it is OK.
2. Your OpenCL is not installed correctly. There is not enough information for more diagnostics.

**Comment by KahnShi** [comment]
@xlz  Thank you, man!
All problems are solved now.

**Comment by Abbyls** [comment]
@KahnShi Can you tell me how?

**Comment by whatisor** [comment]
@xlz ,can you explain why : "It is receiving 30 depth packets per second. If you don't see 30 warnings per second, it is OK."?
If skip 15 frames, FPS becomes 15FPS, not 30FPS => is it bad,right?

I got this issue with OpenGL pipeline when we move some windows (Protonect window or other program windows)

**Comment by xlz** [comment]
User asked about CPU/gl mode. The CPU/gl mode is meant for verification and its performance is bad, so getting any data at all is ok.

**Comment by whatisor** [comment]
I see, thanks.
About window issue I said, do you think why OpenGL processing become so slow wen we interact with other application windows?
I have a powerful PC, I saw you log it even 120Hz, it is too big for Kinect device, isn't it? It should be maximum 30Hz because of Hardware limitation.
If by some reasons, you require it 120Hz, it will be affected by other programs which make GPU busy.
