### ISSUE TITLE
Segmentation fault after running same code on different machine

### ISSUE THREAD

**Issue by anshulvj** [OpenKinect/libfreenect2#297]
So for the past few days I've been modifying libfreenect on my (sorta)embedded machine. I have added pcl code to libfreenect2 because I wanted to visualize point cloud using cloud_viewer. The same code (with modifications to CMakeLists.txt for including PCL, Protonect.cpp, Registration.cpp and Registration.h to access point cloud) works fine on the embedded machine (well, by fine I mean that the code runs without error but I cannot see the point cloud in the window, it's all black with the rgb axes showing in one corner).

To see whether this problem is due to lack of graphics card, I took the same code to a proper CPU running ubuntu 15.04 (which has integrated graphics card but a faster cpu) and tried to run it over there but I got the following error

anshulvj@anshulspc:~/DimApp/libfreenect2/examples/protonect$ sudo ./bin/Protonect gl
modprobe: FATAL: Module nvidia not found.
anshulvj@anshulspc:~/DimApp/libfreenect2/examples/protonect$ sudo ./bin/Protonect cpu
modprobe: FATAL: Module nvidia not found.
anshulvj@anshulspc:~/DimApp/libfreenect2/examples/protonect$ ./bin/Protonect cpu
Segmentation fault (core dumped)
anshulvj@anshulspc:~/DimApp/libfreenect2/examples/protonect$ ./bin/Protonect cl
Segmentation fault (core dumped)
anshulvj@anshulspc:~/DimApp/libfreenect2/examples/protonect$ ./bin/Protonect gl
Segmentation fault (core dumped)
anshulvj@anshulspc:~/DimApp/libfreenect2/examples/protonect$ 

no matter what option I used. I also had to install opencl, pcl, opencv before I could properly compile libfreenect2. I also re-cloned libfreenect2 (fresh code) without change and when I ran it, it only ran properly with the cl argument (for any other argument or no argument it shows only rgb output and does not show depth, ir, undistorted and registered). 

The code I've added is all from the [official cloud viewer documentation](http://pointclouds.org/documentation/tutorials/cloud_viewer.php) and it compiles without any error. Even though I suspect that the segfaults might be due to the code I added, it's strange that it ran fine on the other machine without runtime errors, and compiled on the new machine without problems. And since the fresh code is also not working with cl, gl and no arguments, I think there might be some other. 

What's noteworthy is that I do not have a Nvidia graphics card so when I run as su I don't know why it's looking for Nvidia module. Before I had installed opencl and used sudo, it simply used to quit without any output. Is there anything obviously wrong I'm doing here?

More info:
I've installed pcl-1.8, opencv3.0, beignet1.0.3 (opencl) from their official website. 

clinfo for me gives the following output:

anshulvj@anshulspc:~/DimApp/libfreenect2/examples/protonect$ clinfo
Number of platforms                               1
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 1.2 beignet 1.0.3
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_icd
  Platform Extensions function suffix             Intel

  Platform Name                                   Intel Gen OCL Driver
Number of devices                                 1
  Device Name                                     Intel(R) HD Graphics Haswell GT2 Desktop
  Device Vendor                                   Intel
  Device Vendor ID                                0x412
  Device Version                                  OpenCL 1.2 beignet 1.0.3
  Driver Version                                  1.0.3
  Device OpenCL C Version                         OpenCL C 1.2 beignet 1.0.3
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               20
  Max clock frequency                             1000MHz
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None, None, None
  Max work item dimensions                        3
  Max work item sizes                             512x512x512
  Max work group size                             512
  Preferred work group size multiple              16
  Preferred / native vector sizes                 
    char                                                16 / 8       
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 0 / 8        (n/a)
    float                                                4 / 4       
    double                                               0 / 2        (n/a)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    32, Little-Endian
  Global memory size                              2147483648 (2GiB)
  Error Correction support                        No
  Max memory allocation                           1073741824 (1024MiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        <printDeviceInfo:85: get CL_DEVICE_GLOBAL_MEM_CACHE_SIZE : error -30>
  Global Memory cache line                        64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             8192x8192 pixels
    Max 3D image size                             8192x8192x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Global
  Local memory size                               65536 (64KiB)
  Max constant buffer size                        134217728 (128MiB)
  Max number of constant args                     8
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Profiling timer resolution                      80(null)
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
  Prefer user sync for interop                    Yes
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                __cl_copy_region_align4;__cl_copy_region_align16;__cl_cpy_region_unalign_same_offset;__cl_copy_region_unalign_dst_offset;__cl_copy_region_unalign_src_offset;__cl_copy_buffer_rect;__cl_copy_image_1d_to_1d;__cl_copy_image_2d_to_2d;__cl_copy_image_3d_to_2d;__cl_copy_image_2d_to_3d;__cl_copy_image_3d_to_3d;__cl_copy_image_2d_to_buffer;__cl_copy_image_3d_to_buffer;__cl_copy_buffer_to_image_2d;__cl_copy_buffer_to_image_3d;__cl_fill_region_unalign;__cl_fill_region_align2;__cl_fill_region_align4;__cl_fill_region_align8_2;__cl_fill_region_align8_4;__cl_fill_region_align8_8;__cl_fill_region_align8_16;__cl_fill_region_align128;__cl_fill_image_1d;__cl_fill_image_1d_array;__cl_fill_image_2d;__cl_fill_image_2d_array;__cl_fill_image_3d;
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_icd

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Intel Gen OCL Driver
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [Intel]
  clCreateContext(NULL, ...) [default]            Success [Intel]
  clCreateContext(NULL, ...) [other]              <error: no devices in non-default plaforms>
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Intel Gen OCL Driver
    Device Name                                   Intel(R) HD Graphics Haswell GT2 Desktop
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Intel Gen OCL Driver
    Device Name                                   Intel(R) HD Graphics Haswell GT2 Desktop

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.3
  ICD loader Profile                              OpenCL 1.2

**Comment by xlz** [comment]
Can you produce the stack trace?

```
ulimit -c unlimited
./bin/Protonect xxx
Segmentation fault (core dumped)
gdb ./bin/Protonect core.xxxx
(gdb) bt
```

**Comment by anshulvj** [comment]
I changed from opencv 3 to opencv 2.4.9 and it worked.
