### ISSUE TITLE
Multiple Kinects does not work

### ISSUE THREAD

**Issue by xionglingfeng** [OpenKinect/libfreenect2#304]
I connected two Kinect2 on my computer and write a program to capture video from both Kinects.
This program creates two threads, each threads execute `Freenect2Device *dev = params->driver->openDevice(params->i, new OpenCLPacketPipeline());` to open a Kinect with device index.
When the program runs, it reports lots of errors said `
[TransferPool::submit] failed to submit transfer: LIBUSB_ERROR_OTHER`. Also, only one Kinect return data, the other thread just stucked at `listener.waitForNewFrame(frames);`.
After setting `LIBUSB_DEBUG=3`, it reports

    libusb: warning [darwin_transfer_status] transfer error: unknown error (0xe000400e) (value = 0xe000400e)

and

    libusb: error [submit_iso_transfer] isochronous transfer failed (dir: In): unknown error (0xe00002ec)
    [TransferPool::submit] failed to submit transfer: LIBUSB_ERROR_OTHER

I tested this with latest version (2ea7c3419932362376fb2dbb20b690f6730624f1) on both Ubuntu 15.04 and Mac OS X 10.10.3. I also tried to switch the USB ports I used to connect Kinect but the issue persists.

**Comment by antigp** [comment]
Have the same issues. Does external controller for second kinect fix this problem?

**Comment by siddharthachandra** [comment]
I confirm this issue on my Ubuntu 14.04 (with built-in Texas Instruments USB 3.0 HUBs on my HP Z420).

**Comment by Edwinzero** [comment]
External USB controller can solve this.

**Comment by xlz** [comment]
`0xe00002ec` means `kIOReturnNoBandwidth`.

**Comment by rain3k** [comment]
I have same issue.....
I try to connect external usb to Mac Pro
but it didn't work........
how to solve this issue.
