### ISSUE TITLE
OpenGLDepthPacketProcessor not working on Intel GPUs (Mac/OS X)

### ISSUE THREAD

**Issue by dominiklessel** [OpenKinect/libfreenect2#31]
Hello there!

I successfully compiled libfreenect2 on my MacBook Pro Retina (2013; QuadCore i7; Intel Iris GPU), but the IR/Depth Steam is just black. My first thought on this is a incompatible GPU … Does anybody have the same problem?

![bildschirmfoto 2014-07-24 um 12 23 44](https://cloud.githubusercontent.com/assets/582281/3686863/0b57057c-131e-11e4-8222-ce1b228fec6a.png)

Some debugging code I added in `SyncMultiFrameListener::onNewFrame(Frame::Type type, Frame *frame)` (frame_listener_impl.cpp:69) outputted the following information:

```
if ( type == 4 ) {
  printf( "Got depth frame!\n" );
  printf( "width: %i\n", int(frame->width) );
  printf( "height: %i\n", int(frame->height) );
  printf( "bytes per pixel: %i\n", int(frame->bytes_per_pixel) );
  double sum;
  for (int i = 0; i < frame->width*frame->height*frame->bytes_per_pixel; ++i)
    sum += frame->data[i];
  printf( "sum: %f\n", sum );
}
```

````

Got depth frame!
width: 512
height: 424
bytes per pixel: 4
sum: 0
```

After skimming through the code I ended up looking at the different DepthPacketProcessors and swapped `OpenGLDepthPacketProcessor` with `CpuDepthPacketProcessor` (libfreenect.cpp:76) and commented out `depth_packet_processor_(0)` (libfreenect.cpp:277) to make Protonect compile again.

Now Protonect is outputting IR and Depth information, but turns my MacBook into a pocket heater:

![bildschirmfoto 2014-07-24 um 12 25 08](https://cloud.githubusercontent.com/assets/582281/3686883/67d6380e-131e-11e4-9548-265c1e3a4dd4.png)

**Comment by DrFuzzy** [comment]
Same issue at Ubuntu 14.04 x64 with Quadro NVS 295, NVIDIA Driver Version 331.113 and OpenGL 3.3.0:

delk@Darwin:~/libfreenect2/examples/protonect/bin$ ./test_opengl 
[OpenGLDepthPacketProcessor::loadP0TablesFromFiles] Loading p0table 0 from './../p00.bin' failed!
[OpenGLDepthPacketProcessor::loadP0TablesFromFiles] Loading p0table 1 from './../p01.bin' failed!
[OpenGLDepthPacketProcessor::loadP0TablesFromFiles] Loading p0table 2 from './../p02.bin' failed!
[CpuDepthPacketProcessor::loadP0TablesFromFiles] Loading p0table 0 from './../p00.bin' failed!
[CpuDepthPacketProcessor::loadP0TablesFromFiles] Loading p0table 1 from './../p01.bin' failed!
[CpuDepthPacketProcessor::loadP0TablesFromFiles] Loading p0table 2 from './../p02.bin' failed!
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
Aborted (core dumped)

Any ideas?

**Comment by christiankerl** [comment]
test_opengl currently broken, because you need the p0tables and raw or data as binary files. We need to add a tool to dump these files from the device

**Comment by Edwinzero** [comment]
Hi @christiankerl , after done run libfreenect2 on windows, I turn to make a mac library for my project and I download the master folder today. But I came across the same problem that without IR and Depth image, and I try to do modification like previous comments. There seems no use CPUDepthPacketProcessor in the libfreenect2.cpp file now, and I don't know why...

I use macports to install autoconf, libtool, nasm, automake and other stuffs that mentioned in the mac installation instruction. 
By the way, during manually run install_mac.sh, there are lots of lines that shows "no key in the table", is this means a problem?
and I also get an info says can not find such files or dependencies named config.guess ...

Hope you could reply me.
Thank you very much!

**Comment by DrFuzzy** [comment]
Exact same problem here! MacOSX 10.10, RGB works fine but no IR, neither Depth (black window). CPUDepthPacketProcessor doesn't exist in libfreenect2.cpp.

So kinda stuck for now, anyone who could help?

**Comment by christiankerl** [comment]
You can instantiate a CpuPacketPipeline and pass it to the Freenect2 openDevice method. It will use the CPU depth processor

**Comment by DrFuzzy** [comment]
Since I am not very familiar with this code hierarchy, could you rather post the necessary code additions/changes?

**Comment by christiankerl** [comment]
For example in Protonect.cpp:

add an include after line 37
```cpp
#include <libfreenect2/packet_pipeline.h>
```

change line 61 from
```cpp
libfreenect2::Freenect2Device *dev = freenect2.openDefaultDevice();
```
to
```cpp
libfreenect2::Freenect2Device *dev = freenect2.openDefaultDevice(new libfreenect2::CpuPacketPipeline());
```
if you have opencl support you can also use
```cpp
libfreenect2::Freenect2Device *dev = freenect2.openDefaultDevice(new libfreenect2::OpenCLPacketPipeline());
```

libfreenect2 takes care of deleting the pipeline object.

**Comment by DrFuzzy** [comment]
Brilliant, thanks a million, works a treat now! With OpenCLPacketPipeline is noticeably faster than CpuPacketPipeline. Only con, my Macbook Air fan is working overtime, you can almost fry an egg on it! Any idea what's wrong with OpenGLDepthPacketProcessor?

**Comment by Edwinzero** [comment]
Thank you @christiankerl !!! It really works!! You are awesome!! And now it perfectly fit 10.10 now. By the way, could you provide me some solution about multiple camera calibration with libfreenect2? Or read multiple Kinect2 data? I'm trying to connect 6 Kinect on my mac with an individual USB3.0 board with 6 individual buses. Thx again!

**Comment by gaborpapp** [comment]
i dumped the necessary files required for test_opengl (#112). it runs, but displays almost white images. attached the screenshot from protonect with cpu depth packet processor and the dumped data displayed with test_opengl. is this normal? or is it some kind of an error diff? any hint would be appreciated.

protonect cpu:
![protonect-cpu](https://cloud.githubusercontent.com/assets/203532/6059055/ab1745be-ad2d-11e4-92d1-574c65bde98b.jpg)

test_opengl:
![test_opengl](https://cloud.githubusercontent.com/assets/203532/6059063/b8e12a34-ad2d-11e4-99ec-94d4d62e390d.jpg)

**Comment by gaborpapp** [comment]
#171 fixes this for me on OS X with Intel and NVidia GPU as well, please test

**Comment by vedanshu95** [comment]
Hi,

I am also facing the same problem in ubuntu 14.04. i have installed kernel 13.16 but still i am facing the same problem. I am unable to see dept and ir image. only rgb image shows up.
