### ISSUE TITLE
Licensing Questions

### ISSUE THREAD

**Issue by jjoachim** [OpenKinect/libfreenect2#312]
I am a bit confused about what the GNU license implies when it comes to selling software. I am making some software that uses a Kinectv2(s) (and some other bits) to do various things.  I am using libfreenect2's shared library to talk to the Kinectv2(s).  It's getting to the point where I want to think about selling it, but then I read the GPL2 document.

While trying to understand the specific rules, the best/most relevant clarification that I could find was this:
http://programmers.stackexchange.com/questions/47032/can-i-use-gpl-software-in-a-commercial-application

As one of the comments points out, it sounds like the license used here intends to make all source code it touches freely distributable.  While I don't mind distributing libfreenect2 source code libraries on request or even with the package, do I need to also make my own mostly unrelated source code available as well?

At the bottom of the GPL2 document, it states:
"If your program is a subroutine library, you may consider it more useful to permit linking proprietary applications with the library.  If this is what you want to do, use the GNU Library General Public License instead of this License."

Is the intended license being used here?  Granted, I'm not entire confident that I fully understand the differences and scope.

**Comment by JoshBlake** [comment]
Libfreenect2 is published under a dual license of Apache 2.0 and GPL2. You are free to use the project under the terms of either license. See any of the source file headers for specifics, e.g. https://github.com/OpenKinect/libfreenect2/blob/master/examples/protonect/Protonect.cpp.

The primary intention is the more liberal Apache 2.0 license (and you would have no problem with commercial use or sales). The GPL2 is included for maximum compatibility with GPL only projects, such as the Linux kernel, in the case that libfreenect(2) needed to publish any kernel space drivers.
