### ISSUE TITLE
color, depth registration issue

### ISSUE THREAD

**Issue by flyfj** [OpenKinect/libfreenect2#316]
I used the example program from protonect. It has no problem fetching rgb and depth data, but when i call the registration function, the returned color is not well aligned.
the code i used:
```
libfreenect2::Registration* registration = new libfreenect2::Registration(dev->getIrCameraParams(), dev->getColorCameraParams());
...
registration->apply(rgb, depth, registered);
...
```
example images are shown below:
![1_color](https://cloud.githubusercontent.com/assets/2397970/8608876/41c760bc-2654-11e5-9b7b-6d823bb43ed4.png)
![1_depth](https://cloud.githubusercontent.com/assets/2397970/8608877/41d09cf4-2654-11e5-87ac-4b6cc91a8fe7.png)

Official SDK doesn't have this problem if I remember it correctly. Struggling with this issue now.

**Comment by floe** [comment]
This is a bit weird, never seen such a large mismatch so far. With libfreenect 2 on my Kinect devices, the images line up very well. Can you check if you have the latest master branch?

**Comment by wiedemeyer** [comment]
It cant be the newest master, the new api for the registration looks like this now:
`registration->apply(rgb,depth,&undistorted,&registered);`

**Comment by flyfj** [comment]
@floe @wiedemeyer thanks for the advice. didn't notice the new branch change. will update and test.

**Comment by flyfj** [comment]
@floe So I rebuilt from the latest master branch, but it still gives me the same results. From the command line window, it shows messages like: skipping depth package. subpackage too large.
It looks like the registration is running late behind the fetching or display.

**Comment by floe** [comment]
Was the screenshot taken with a moving camera? You could try a different depth packet processor, see here: https://github.com/OpenKinect/libfreenect2/blob/master/README.md#im-seeing-the-color-camera-stream-but-no-depthir-black-windows

**Comment by floe** [comment]
Any news? If there's still need for discussion, please re-open.
