### ISSUE TITLE
Unable to locate package libturbojpeg0-dev

### ISSUE THREAD

**Issue by renxinhe** [OpenKinect/libfreenect2#323]
I have Ubuntu 14.04. During the build, I ran `sudo apt-get install libturbojpeg0-dev`, and this is the error message:
>Reading package lists... Done
>Building dependency tree
>Reading state information... Done
>E: Unable to locate package libturbojpeg0-dev

Maybe the package is renamed?

**Comment by floe** [comment]
Please see https://github.com/OpenKinect/libfreenect2#debianubuntu-1404-perhaps-earlier - the package name is libjpeg-turbo8-dev.
