### ISSUE TITLE
Edit) optirun ./Protonect ->  running ( ./Protonect cl)  problem after installing beignet

### ISSUE THREAD

**Issue by Guhnoo** [OpenKinect/libfreenect2#327]
Hello,   I check  It runs well  when I run   './Protonect cpu '   (rgb,depth, etc)

but, I  also hope to run  on './Protonect gl ' 

I try to so many times and I guess  My problem is optimus feature. 

##installed bumblebee 

I have installed ' https://wiki.ubuntu.com/Bumblebee#Advanced_Setups ' this. 

and but, I don't know how I have to do next?   

after installed, I get nvidia 304.125 .

**Comment by larshg** [comment]
Maybe you can force it to use the gpu in nvidia's settings, or maybe use the beignet project for running it on the cpu if it defaults to this one. But what error are you getting? black screen? What if you run ./protonect cl ? what does it report as devices available?

**Comment by christiankerl** [comment]
did you try ```optirun ./Protonect gl```?

**Comment by Guhnoo** [comment]
Thanks to answer everyone.

I succeeded to force run like 
## $ optirun ./Protonect
![optirun protonect](https://cloud.githubusercontent.com/assets/13333380/8867887/c0d81358-320a-11e5-8feb-c4b4c1575976.png)

well, but I have another problem in useing OpenCL 

when I try to calibration in this git hup =>  https://github.com/code-iai/iai_kinect2 
(I will use this in ros)
I have some problem to getting depth img ,trying to use $ optirun --no-failsafe ~~~~~   
![cal-data](https://cloud.githubusercontent.com/assets/13333380/8867906/45c2cf86-320b-11e5-8431-a1c4d5adcf37.png)

I thought It is because Depth registration method does not change from CPU to OpenCL
So, I followed this  to install beignet
![beignet](https://cloud.githubusercontent.com/assets/13333380/8867962/f7de8b60-320b-11e5-964d-7f1baefeabeb.png)

and rebuild , as trying same section 4 

But, I get error  when I use $ ./Protonect cl
![opencl](https://cloud.githubusercontent.com/assets/13333380/8867983/7a3bfff2-320c-11e5-8ebe-b19f9044c233.png)
What is this problem???

**Comment by floe** [comment]
This is addressed in the FAQ, when you want to use OpenCL on an Intel GPU, you have to execute `echo 0 | sudo tee /sys/module/i915/parameters/enable_cmd_parser` first if this error occurs.

**Comment by Guhnoo** [comment]
Thanks to give me an answer. I fixed it . Really Thanks

2015-07-25 3:44 GMT+09:00 Florian Echtler <notifications@github.com>:
