### ISSUE TITLE
BodyIndex Frame?

### ISSUE THREAD

**Issue by ThomasLengeling** [OpenKinect/libfreenect2#334]
Is it possible to obtain the boydIndex frame from the device?. 
Any recommendation in how should I extract the bodyIndex information from the kinect v2, such as using a external library like openNI.

Thomas

**Comment by floe** [comment]
Check out pull request #302 which provides an OpenNI adapter. Further questions in that thread, please.

**Comment by sunnysunnyran** [comment]
I want to know bodyIndex,too,can you have a good idea?

**Comment by floe** [comment]
@sunnysunnyran as stated above, use the OpenNI adapter. This is described in the README.
