### ISSUE TITLE
[Issue] [multiple kinects] open(idx) always returns "the device may already be open" even for unique indexes

### ISSUE THREAD

**Issue by chipweinberger** [OpenKinect/libfreenect2#336]
Hi =)

First off thank you for this wonderful software. GH needs a donation button ;)

I am trying to get multiple kinects working on windows 8.1. One device works fine and there are multiple compatible USB3 cards on my desktop. First off, I should mention that I am using a November build of libfreenect2 because I was having major build issues and this is one that I found prebuilt.

I have multiple kinects plugged into different controllers. Device enumeration finds both. The first one open(0) opens no issues. open(1) however returns the same kinect handle for some reason....

The offending code seems to be this:

    bool tryGetDevice(libusb_device *usb_device, Freenect2DeviceImpl **device)
    {
        for(DeviceVector::iterator it = devices_.begin(); it != devices_.end(); ++it) {
            if((*it)->isSameUsbDevice(usb_device)) {
                *device = *it;
                return true;
            }
        }

        return false;
    }

I imagine it is important but nevertheless I made it always return false which almost seemed to solve the issue and returned a unique device - but later on the code crashed when trying to call start(). 

Has anyone else run into this issue?

Thanks in advance =)

Best,
Chip

**Comment by floe** [comment]
The method to select specific devices has changed quite a bit since November; I would suggest you try and build the current master branch first.

**Comment by chipweinberger** [comment]
Okay no worries =) Have you heard of anyone successfully using multiple kinects on windows before? Fingers very crossed I can get it to work.

**Comment by chipweinberger** [comment]
Indeed updating to the newest build partially solved my issue but ultimately it's failing where the last one failed as well. 

It appears that it is having trouble communicating with the second device over usb, resulting in access violations when it expects a parameter to be there, but failed. 

For reference here are the log details when starting a second deivce:

	[Freenect2DeviceImpl] starting...
	[DepthPacketStreamParser::onDataReceived] not all subsequences received 0
	[DepthPacketStreamParser::onDataReceived] skipping depth packet
	[DepthPacketStreamParser::onDataReceived] skipping depth packet
	[DepthPacketStreamParser::onDataReceived] skipping depth packet
	[DepthPacketStreamParser::onDataReceived] skipping depth packet
	[DepthPacketStreamParser::onDataReceived] skipping depth packet
	[RgbPacketStreamParser::onDataReceived] skipping rgb packet!
	[DepthPacketStreamParser::onDataReceived] skipping depth packet
	[DepthPacketStreamParser::onDataReceived] skipping depth packet
	[DepthPacketStreamParser::onDataReceived] skipping depth packet
	[RgbPacketStreamParser::onDataReceived] skipping rgb packet!
	[CommandTransaction::send] bulk transfer failed! libusb error -1: LIBUSB_ERROR_I
	
	[CommandTransaction::send] sent number of bytes differs from expected number! ex
	pected: 20 got: 0
	[CommandTransaction::send] bulk transfer failed! libusb error -1: LIBUSB_ERROR_I
	O
	[CommandTransaction::send] sent number of bytes differs from expected number! ex
	pected: 20 got: 0
	[Freenect2DeviceImpl] ReadData0x14 response
	0 bytes of raw data
	[CommandTransaction::send] bulk transfer failed! libusb error -1: LIBUSB_ERROR_I
	O
	[DepthPacketStreamParser::onDataReceived] skipping depth packet
	[CommandTransaction::send] sent number of bytes differs from expected number! ex
	pected: 24 got: 0
	[Freenect2DeviceImpl] serial number reported by libusb 502233641942 differs from
	 serial number ²²²²½½½½½½½½½½½½½½½½ε■ε■ε■ε■ε■ε■ in device protocol!
	[CommandTransaction::send] bulk transfer failed! libusb error -1: LIBUSB_ERROR_I
	O
	[CommandTransaction::send] sent number of bytes differs from expected number! ex
	pected: 24 got: 0

**Comment by chipweinberger** [comment]
Closing this because updating to the newest build fixed the initial bug. The eventual bug (crashing after starting two devices) can be worked around by using a separate process of libfreenect for each kinect as indicated in another issue.
