### ISSUE TITLE
RESOLVED!! =) Multiuple kinects works on windows **IF YOU USE SEPARATE PROCESSES OF LIBFREENECT FOR EACH KINECT**

### ISSUE THREAD

**Issue by chipweinberger** [OpenKinect/libfreenect2#344]
whoo =)

**Comment by floe** [comment]
Nice that you've got it working :-) You've opened quite a number of issues, could you perhaps close those again which are resolved for you?

**Comment by chipweinberger** [comment]
Will do =)
