### ISSUE TITLE
[Question] What kind of multithreading is there regarding "OnFrameArrived" events?

### ISSUE THREAD

**Issue by chipweinberger** [OpenKinect/libfreenect2#347]
If say, 6 frames arrives, 2 ir, 2 color, 2 depth, do all 6 frames onarrived events fire simulateously without blocking? Or does one frame of the same type block the next frame of the same type? Or do all frames of all types block each other (sequential).

Thanks

Chip

**Comment by floe** [comment]
The IR and depth frames will always arrive simultaneously, the RGB frames on their own. If you set one single listener for all three types, then `waitForNewFrames` will block until one of each type has arrived.

**Comment by chipweinberger** [comment]
Thanks!!
