### ISSUE TITLE
X server found. dri2 connection failed! 

### ISSUE THREAD

**Issue by zfxw0206** [OpenKinect/libfreenect2#359]
When I run "./Protonect cl" , I got the following message:

~/libfreenect2/examples/protonect/bin$ ./Protonect cl
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 14 usb devices connected
[Freenect2Impl] found valid Kinect v2 @2:3 with serial 503384541942
[Freenect2Impl] found 1 devices
X server found. dri2 connection failed! 
Trying to open directly...Device open failed

Then I run "ldd Protonect|grep usb", I got this
	libusb-1.0.so.0 => /home/visiongm/libfreenect2/examples/protonect/lib/libusb-1.0.so.0 (0x00007fcb7fa6c000)

how to fix this problem?

**Comment by xlz** [comment]
Need output of `ls -l /dev/dri/` and `id`. You should be in the `video` group and `/dev/dri/*` should have rw access for `video` group. If not, add yourself to `video` and relogin.

If this does not work, run `strace ./Protonect cl` and post the end of the log.

**Comment by zfxw0206** [comment]
Thank you very much. I think there may be something wrong of the system. Then I reinstall the system,   it works fine now.

**Comment by melodybinbin** [comment]
sudo apt-get remove beignet*

Try this command. It is works for me.
