### ISSUE TITLE
Build error regarding libjpegturbo.a on Ubuntu 14.04

### ISSUE THREAD

**Issue by floe** [OpenKinect/libfreenect2#36]
On current Ubuntu 14.04 amd64, even with all dependencies installed, you can get the following build error:

    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value

This is due to a bug in the libturbojpeg package. A one-line fix is to execute:

    sudo ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0.0.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so

**Comment by fstafforini** [comment]
[This confirmed bug](https://bugs.launchpad.net/ubuntu/+source/libjpeg-turbo/+bug/1369067) could be the culprit, apparently there is a symlink missing.

**Comment by sketchc89** [comment]
I've installed all dependencies and added the symbolic link with 
```
sudo ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0.0.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so
```
but the make step still fails on Ubuntu 14.04
```
Linking CXX shared library lib/libfreenect2.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libfreenect2.so] Error 1
make[1]: *** [CMakeFiles/freenect2.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by xlz** [comment]
We have created a workaround that does not requires creating symlink under /usr. Please test latest master.

**Comment by sketchc89** [comment]
The workaround worked using the latest master (commit 42da6d8c09b ) and I have Protonect up and running. 
I upgraded Kernel to 3.16 per the instructions using:
```sudo apt-get install linux-image-generic-lts-utopic```
Thanks for the great work guys.

**Comment by SebastianVarma** [comment]
I installed the latest commit, but it still returns the same error.

**Comment by floe** [comment]
@SebastianVarma can you post the output of `ls -la /usr/lib/*/libturbojpeg*`?

**Comment by sketchc89** [comment]
```-rw-r--r-- 1 root root 499438 Dec 19  2013
/usr/lib/x86_64-linux-gnu/libturbojpeg.a
lrwxrwxrwx 1 root root     47 Jun  8 15:40
/usr/lib/x86_64-linux-gnu/libturbojpeg.so ->
/usr/lib/x86_64-linux-gnu/libturbojpeg.so.0.0.0
lrwxrwxrwx 1 root root     21 Dec 19  2013
/usr/lib/x86_64-linux-gnu/libturbojpeg.so.0 -> libturbojpeg.so.0.0.0
-rw-r--r-- 1 root root 301472 Dec 19  2013
/usr/lib/x86_64-linux-gnu/libturbojpeg.so.0.0.0```

On Tue, Jun 9, 2015 at 2:54 PM, Florian Echtler <notifications@github.com>
wrote:

> @SebastianVarma <https://github.com/SebastianVarma> can you post the
> output of ls -la /usr/lib/*/libturbojpeg*?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenKinect/libfreenect2/issues/36#issuecomment-110485469>
> .
>



-- 
Chris Sketch
(248) 835-5638

**Comment by sketchc89** [comment]
```bash
-rw-r--r-- 1 root root 499438 Dec 19  2013 /usr/lib/x86_64-linux-gnu/libturbojpeg.a
lrwxrwxrwx 1 root root     47 Jun  8 15:40 /usr/lib/x86_64-linux-gnu/libturbojpeg.so -> /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0.0.0
lrwxrwxrwx 1 root root     21 Dec 19  2013 /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0 -> libturbojpeg.so.0.0.0
-rw-r--r-- 1 root root 301472 Dec 19  2013 /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0.0.0
```

**Comment by SebastianVarma** [comment]
@floe I will do so tomorrow morning when I get to work.

**Comment by SebastianVarma** [comment]
@floe The output is as follows:

-rw-r--r-- 1 root root 499438 Dec 19  2013 /usr/lib/x86_64-linux-gnu/libturbojpeg.a
lrwxrwxrwx 1 root root     47 Jun  9 13:42 /usr/lib/x86_64-linux-gnu/libturbojpeg.so -> /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0.0.0
lrwxrwxrwx 1 root root     21 Dec 19  2013 /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0 -> libturbojpeg.so.0.0.0
-rw-r--r-- 1 root root 301472 Dec 19  2013 /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0.0.0

**Comment by floe** [comment]
This does look correct... can you please open a new issue and post the exact build error?

**Comment by neorobo** [comment]
Just wanted to chime in that I have this exact same issue, with the same output from ls -la /usr/lib/*/libturbojpeg*

**Comment by xlz** [comment]
@neorobo 
Can not reproduce.

I also have this same output from `ls -la /usr/lib/*/libturbojpeg*` and my build works fine.

Can you post the log of your cmake ..?

(Should have Found TurboJPEG: /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0)

**Comment by floe** [comment]
@neorobo Duplicate issue #286 was fixed by a fresh clone of master and re-run of cmake, maybe try that first?

**Comment by neorobo** [comment]
@xlz  Based on your suggestion I checked CMakeCache.txt. It was pointing to the static library. I edited it to point to .so as you suggested should be the case and protonect was succesfully installed.

**Comment by xlz** [comment]
I checked again. On Ubuntu 14.04, `/usr/lib/x86_64-linux-gnu/libturbojpeg.a` is provided by `libjpeg-turbo8-dev`, but `/usr/lib/x86_64-linux-gnu/libturbojpeg.so.0` is provided by `libturbojpeg`. If the users follow the documentation, they will only install `libjpeg-turbo8-dev`, and can not find `libturbojpeg.so.0`. The docs need fixing.

I was also confused by this in several previous comments.

**Comment by sketchc89** [comment]
I've compiled libfreenect2 quite a few times in the past couple weeks and I don't know if I've ever gotten it to work on the first time through following the order in the documentation. 
After failing, I remove it entirely from my system, reclone it, run `./depends/install_ubuntu.sh`, `cmake CMakeLists.txt`, `make && sudo make install` it builds almost every time. Have repeated this on Ubuntu 14.04 32-bit & 64-bit and 15.04.

**Comment by floe** [comment]
I'm hoping that this is finally fixed for Debian and Ubuntu with latest master (both `CMakeLists.txt` and `install_ubuntu.sh`). I'll close it for now, but please comment if this is still a problem.

**Comment by Pincello** [comment]
I had the same Problem and had to delete  /libfreenect2 and clone it again from Git. Now it works.

**Comment by jamesbellaero** [comment]
Fixed it with ./depends/install_ubuntu.sh and then installing libturbojpeg with apt-get.

**Comment by YandanYang** [comment]
I met the same problem, and I refer to this page : [http://www.jetsonhacks.com/2015/02/26/install-kinect-v2-using-libfreenect2-on-nvidia-jetson-tk1/](url)
Fixed with `:sudo apt-get install -y build-essential libturbojpeg libtool autoconf libudev-dev cmake mesa-common-dev freeglut3-dev libxrandr-dev doxygen libxi-dev libjpeg-turbo8-dev`

**Comment by rayjs** [comment]
On Ubuntu 16, I had the same issue. Here is how it got fixed. Hope it helps
**Step 1:**
Install `libjpeg-turbo8-dev`
**Step 2:**
The `libturbojpeg.so` file was missing so I had to create a sym-link.
I ran `sudo ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so`
**Step 3:**
Deleted the build directory and ran cmake again.

**Comment by xlz** [comment]
The above suggestion is wrong.

The issue was fixed. Follow the instructions in README, and no workaround is necessary.

**Comment by paulnord** [comment]
@xlz can you point me to the README to which you refer?

**Comment by xlz** [comment]
> (Ubuntu 14.04 and newer) sudo apt-get install libturbojpeg libjpeg-turbo8-dev

According to https://packages.ubuntu.com/trusty/amd64/libturbojpeg/filelist, libturbojpeg provides /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0. Our CMake was specifically made to detect libturbojpeg.so.0 in the absence of libturbojpeg.so.

**Comment by Smilels** [comment]
@rayjs  your solution also works for me in Ubuntu 16.04. Thanks a lot.

**Comment by hsandt** [comment]
I know the issue is closed, but in case someone still has it after the other suggestions:

We had a very similar issue on https://github.com/HaxeFoundation/hashlink/issues/147 and our solution was to follow the error message on -fPIC and rebuild libjpeg-turbo ourselves with Position-Independent Code. It should be the default when building with cmake/make, but apparently was not done so for the Ubuntu package.

**Comment by xlz** [comment]
@hsandt It's generally better to link shared libraries not static objects. In this case it's better to link libturbojpeg.so not libturbojpeg.a. This is also the reason libturbojpeg.a is not built with -fPIC, because it's not meant for building shared libraries. Either you go all shared or all static.
