### ISSUE TITLE
Unable to install mesa-common-dev

### ISSUE THREAD

**Issue by cpaniagua1** [OpenKinect/libfreenect2#370]
Hello,
I'm trying to install libfreenect2 to work with my new Kinect2. I'm following the installation instructions for Ubuntu 14.04 but when I want to install mesa-common-dev I get the following error:

The following packages have unmet dependencies:
 libcheese-gtk23 : Depends: libclutter-gtk-1.0-0 (>= 0.91.8) but it is not going to be installed
                   Depends: libcogl15 (>= 1.15.8) but it is not going to be installed
 libcheese7 : Depends: libclutter-gst-2.0-0 (>= 0.10.0) but it is not going to be installed
              Depends: gstreamer1.0-clutter but it is not going to be installed
 libclutter-1.0-0 : Depends: libcogl-pango15 (>= 1.15.8) but it is not going to be installed
                    Depends: libcogl15 (>= 1.15.8) but it is not going to be installed

Can somebody help me with this?

**Comment by xlz** [comment]
You have installed unusual versions of packages in the graphics stack previously. "it is not going to be installed" this is because it conflicts with something. You need to manually resolve the conflict. I think an usual way is update everything to newest.

**Comment by cpaniagua1** [comment]
Thank you for your answer. I've updated everything to newest but I have the same problem.

**Comment by floe** [comment]
Sometimes, `apt-get install -f` can be used to fix this situation.

**Comment by cpaniagua1** [comment]
Thank you very much. It fixed my problem.
