### ISSUE TITLE
Build with errors in Visual Studio 2015 (undefined M_PI)

### ISSUE THREAD

**Issue by mbk74** [OpenKinect/libfreenect2#373]
Hi guys
Please fix examples/protonect/CMakeLists.txt. In 177 replace with this
ADD_DEFINITIONS(-DRESOURCES_INC -D_USE_MATH_DEFINES)

**_USE_MATH_DEFINES** - should be defined in project

**Comment by xlz** [comment]
_USE_MATH_DEFINES was removed in #361 51a569ff8473025951111b8df37efc915414c9b5 . @fran6co

**Comment by mbk74** [comment]
Anyway I couldn't build in Visual Studio 2013/2015 without this definition.
