### ISSUE TITLE
[windows]Runtime error occurs instantly after execution

### ISSUE THREAD

**Issue by pierceh89** [OpenKinect/libfreenect2#389]
Hi,
I have libfreenect2 installed using instructions on readme file. My environment is windows 8.1 and VS2013.
I had no errors during the build. I put all necessary dlls in the folder I guess (freenect2.dll, libusb-1.0.dll, glfw3.dll). However once I run the program, error occurs and the program stops working.
So I compiled them again in debug mode, and I got this message.
![untitled-1](https://cloud.githubusercontent.com/assets/12782821/9866393/cba83752-5b9c-11e5-9e77-0340bf66fdd8.png)

I compiled the latest version!
Thank you in advance for answer!

**Comment by pierceh89** [comment]
I have compiled the source downloaded on 18th Aug and it worked well, so it seemed there is a problem in the latest version of the source

**Comment by floe** [comment]
If you have the most recent master, can you try commenting out these lines: https://github.com/OpenKinect/libfreenect2/blob/master/examples/protonect/Protonect.cpp#L98-L100 and re-run Protonect? /cc @xlz

**Comment by pierceh89** [comment]
Thank you very much! It resolved the problem!

**Comment by xlz** [comment]
I didn't find anything in docs that says `std::ofstream::ofstream(NULL)` is invalid. But if MSVC does this check, I think I have to err on the safe side and add that NULL check.
