### ISSUE TITLE
Development Board Compatibility 

### ISSUE THREAD

**Issue by brant203** [OpenKinect/libfreenect2#399]
Does anyone know of any smaller development boards that this would work with? I am working on a project and we need something around the same size as an arduino and for under $150. I know that the minnowboard max has usb 3.0 would libfreenect2 work on it?

**Comment by floe** [comment]
The Odroid XU3 and XU4 are known to work, there's even recently been a release of an unofficial "Ubuntu 15.04 Robotics Edition" which supports both old and new Kinect: http://news.softpedia.com/news/ubuntu-15-04-robotics-edition-brings-microsoft-kinect-support-to-odroid-491887.shtml

**Comment by brant203** [comment]
That is exactly what i needed. Thanks
