### ISSUE TITLE
The reason Using viewer instead of opencv

### ISSUE THREAD

**Issue by Cynthia0217** [OpenKinect/libfreenect2#400]
Hi, I am new to kinect, I noticed the protonect.cpp has been modifed by replacing opencv with viewer, can anyone explain the reason to me ?  I was going to process images extracted form the data stream using opencv, is this a wise choice? Or should I update the code to the new  version?

Thanks a lot ~

**Comment by floe** [comment]
You can still use OpenCV for image processing, of course. However, within libfreenect2, it was used _only_ to display images, and that can be done with OpenGL equally well, so we removed the unnecessary dependency.

**Comment by Cynthia0217** [comment]
@floe Thank you very much. Best Regards~
