### ISSUE TITLE
case CL_DEVICE_TYPE_CUSTOM:  is not defined.

### ISSUE THREAD

**Issue by moonsh** [OpenKinect/libfreenect2#401]
When I tried to build libfreenect2 project, VS said case CL_DEVICE_TYPE_CUSTOM:  is not defined.

Therefore, I ignored this part and did compile and it was success.

**Comment by floe** [comment]
Thanks for the report, this is actually kind of a known bug when using an older OpenCL SDK. We might just remove that, as it's only used for debug output anyway.
