### ISSUE TITLE
Depth/IR Image not working

### ISSUE THREAD

**Issue by madduci** [OpenKinect/libfreenect2#42]
Hi

I've successfully compiled libfreenect2 on my machine and I'm able to run Protonect, but only RGB image is shown, meanwhile IR and Depth images are black.
My configuration:
ManjaroLinux x64 0.8.10 with kernel 3.14.15 on a Lenovo IdeaPad u430.
I receive a lot of messages in the terminal, such as "skipping rgb packet!" or "image data too short!" or "not all subsequences received" and the OpenGLDepthPacketProcessor is relatively fast (~7.70ms -> ¨130Hz).
Device firmware: 2.3.3912.0.7

How can i solve this bug?

Kind regards

**Comment by Edwinzero** [comment]
I am working on Mac and I come across the same problem.
I will do that then give it a try. 
THx!
