### ISSUE TITLE
[Question] Is there any hope for eventually adding exposure control to the color camera?

### ISSUE THREAD

**Issue by chipweinberger** [OpenKinect/libfreenect2#420]

**Comment by chipweinberger** [comment]
It looks like exposure is supported in the SDK so that is a good sign. Taken from the header file:

/* [propget] */ HRESULT ( STDMETHODCALLTYPE *get_ExposureTime )( 
            IColorCameraSettings * This,
            /* [annotation][out][retval] */ 
            _Out_  TIMESPAN *exposureTime);
        
        /* [propget] */ HRESULT ( STDMETHODCALLTYPE *get_FrameInterval )( 
            IColorCameraSettings * This,
            /* [annotation][out][retval] */ 
            _Out_  TIMESPAN *frameInterval);
        
        /* [propget] */ HRESULT ( STDMETHODCALLTYPE *get_Gain )( 
            IColorCameraSettings * This,
            /* [annotation][out][retval] */ 
            _Out_  float *gain);
        
        /* [propget] */ HRESULT ( STDMETHODCALLTYPE *get_Gamma )( 
            IColorCameraSettings * This,
            /* [annotation][out][retval] */ 
            _Out_  float *gamma);

**Comment by HenningJ** [comment]
The official SDK only supports reading of the camera settings. So, most likely, that's the most we can hope for here.

**Comment by xlz** [comment]
> The color exposure is fixed function of the camera, so changing exposure cannot be controlled by software. It is a firmware change.

-- Carmine Sirignano - MSFT

**Comment by chipweinberger** [comment]
Rats!!!
