### ISSUE TITLE
Unable to load DLL 'KernelBuilderAPI.dll':The specified procedure could not be found.(Exception from HRESULT:0x8007007F)

### ISSUE THREAD

**Issue by lishirui** [OpenKinect/libfreenect2#425]
Hi, when I open the libfreenect2.sln using VS2013 after I finished CMake procedure I got this error in  VS2013 dialog.  It seems like the OpenCL cause to this error. When I uninstall the OpenCL this error disappear, But I can't compile the project. Have you meet this problem? 
My OS is Windows 10 , CPU is Intel Xeon(R) CPU E5-1620 and GPU is Quadro K4200.

**Comment by xlz** [comment]
It seems your OpenCL SDK is not correctly set up. I also used OpenCL SDK without this issue.

> When I uninstall the OpenCL this error disappear, But I can't compile the project.

You must regenerate the cmake files. `cmake .. _G "Visual Studio 12 2013 Win64"`.

**Comment by lishirui** [comment]
You mean I can compile this project without OpenCL?

**Comment by xlz** [comment]
With `cmake -DENABLE_OPENCL=OFF`.

**Comment by lishirui** [comment]
Ok It does works. but when I run Protonect.exe I got this:
C:\Users\li.6833\Downloads\libfreenect2-master\libfreenect2-master\build\bin\Debug>Protonect
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 13 usb devices connected
[Error] [Freenect2Impl] failed to open Kinect v2: @2:22 LIBUSB_ERROR_NOT_SUPPORTED Operation not supported or unimplemented on this platform
[Info] [Freenect2Impl] found valid Kinect v2 @2:22 with serial 502792341942
[Info] [Freenect2Impl] found 1 devices
[Info] [Freenect2DeviceImpl] opening...
[Error] [protocol::UsbControl] failed to claim interface with IrInterfaceId(=1)! LIBUSB_ERROR_NOT_SUPPORTED Operation not supported or unimplemented on this platform. Try debugging with environment variable: export LIBUSB_DEBUG=4 .
[Info] [Freenect2DeviceImpl] closing...
[Info] [Freenect2DeviceImpl] deallocating usb transfer pools...
[Info] [Freenect2DeviceImpl] closing usb device...
[Info] [Freenect2DeviceImpl] closed
[Error] [Freenect2] failed to open Kinect v2: @2:22
failure opening device!
I don't know why...  do it support the Windows 10 platform?

**Comment by xlz** [comment]
I have not tested Windows 10. What you saw maya be a bug. Can you do as the error message says, provide the log with LIBUSB_ERROR=4?

**Comment by xlz** [comment]
The followed up win10 issue is to be merged to #448.

**Comment by floe** [comment]
Should be fixed by #429, please re-test with latest master and re-open if necessary.

**Comment by zybaugur** [comment]
I have the same problem, and here is the solution : https://software.intel.com/en-us/forums/opencl/topic/603665
