### ISSUE TITLE
Depth undistortion giving even more distorted result

### ISSUE THREAD

**Issue by vaheta** [OpenKinect/libfreenect2#428]
Did anyone try to look at the depth map or point cloud after applying Registration::distort ? I get even more distorted result, although, as far as I understand this function should undistort the depth map (although it sounds opposite from it's name :)).

**Comment by xlz** [comment]
Registration::distort really does distortion.

Undistortion is in apply().

**Comment by vaheta** [comment]
What is the point of Registration::distort then?

**Comment by xlz** [comment]
Undistortion uses it internally for the reverse pixel mapping algorithm.

**Comment by vaheta** [comment]
Got it. Thanks!
