### ISSUE TITLE
cl.hpp operation not permitted

### ISSUE THREAD

**Issue by hoverpeter** [OpenKinect/libfreenect2#434]
When I run sh ./depends/install_mac.sh, at the end of the process, 

cl.hpp: Operation not permitted

Cannot write to 'cl.hpp' (Success).

It doesn't look like that I don't have permission to run the command because sudo is used. Any idea ?

**Comment by xlz** [comment]
Use this PR #429. Previously reported in #430.

**Comment by hoverpeter** [comment]
@xlz Thanks so much. I solved it as well. The issue was caused by the new security feature in El Capitan.
