### ISSUE TITLE
std::string missing include

### ISSUE THREAD

**Issue by giacomodabisias** [OpenKinect/libfreenect2#437]
Hi,
everytime I build libfreenect2 and then use it by including libfreenect2.hpp I get some error since std::string is undefined. Including it in the header fixes the problem obviously.
Is this intentional or am I making something wrong?

**Comment by xlz** [comment]
Looks like a bug.

> I get some error

Post it.

**Comment by giacomodabisias** [comment]
Its just the common std::string undefined. It comes since there it is used here
virtual std::string getSerialNumber() = 0;
virtual std::string getFirmwareVersion() = 0;
but not defined.

**Comment by xlz** [comment]
`libfreenect2.hpp` should add `#include <string>`.

**Comment by floe** [comment]
Closed by #440 .
