### ISSUE TITLE
[Question] Can't find loadFromFile series member function in test_opengl_depth_packet_processor.cpp or .h

### ISSUE THREAD

**Issue by Edwinzero** [OpenKinect/libfreenect2#446]
![image](https://cloud.githubusercontent.com/assets/5100412/10699195/13cee824-7983-11e5-9ceb-54c1482387b3.png)
I can't find these member functions in the correspondent class. Am I download a old version code from github source?
This happens when I done build the libfreenect and then I create a new project and import example files to run protonect.cpp. It keeps popping out this error
![image](https://cloud.githubusercontent.com/assets/5100412/10699239/63220636-7983-11e5-9186-d5e757b82914.png)

**Comment by xlz** [comment]
This is not a bug. You can remove test_opengl_depth_packet_processor.cpp from the project. C4146 is just a warning, not an error. Maybe you can turn off warnings as errors.
