### ISSUE TITLE
Required Notification in ReadMe no longer needed?

### ISSUE THREAD

**Issue by RyanGordon** [OpenKinect/libfreenect2#461]
There is a section at the bottom of the ReadMe that doesn't seem like it's pertinent anymore: https://github.com/OpenKinect/libfreenect2#required-notification

Just wanted to confirm if that's the case and if so I can open a PR if someone doesn't beat me to it.

**Comment by JoshBlake** [comment]
Yes, that notification is not necessary anymore, since K4W2 SDK officially launched.

-----Original Message-----
