### ISSUE TITLE
libusb1.0.20 needed but libusb1.0.19 provided

### ISSUE THREAD

**Issue by jagunh** [OpenKinect/libfreenect2#466]
I was installing libfreenect2 yesterday and ran into the issue that the needed version of libusb is 1.0.20 but the one being installed by the install_libusb.sh is 1.0.19.
At the end changing the version manually in the built libfreenect2/depends/libusb/lib/pkgconfig/libusb-1.0.pc from 1.0.19 to 1.0.20 solved the problem. Maybe the used "git checkout 51b10191033ca3a3819dcf46e1da2465b99497c2" can be updated or completely changed to the ppa-method?

**Comment by floe** [comment]
Thanks for the hint, fixed for now. Perhaps the PPA variant is cleaner, though.
