### ISSUE TITLE
why the image is reversed and not calibrated for the latest upgrade?!!!

### ISSUE THREAD

**Issue by shamoorti** [OpenKinect/libfreenect2#474]
Hello guys,
Please take a look at this issue, I installed the latest upgrade of Libfreenect2 and I see the iamge reversed and not calibrated anymore:
![screenshot - 2015-11-19 - 12 57 49](https://cloud.githubusercontent.com/assets/10776933/11270272/bc50291e-8ebd-11e5-80b6-a2e8fc1141bb.png)

**Comment by xlz** [comment]
Do you know when it was not mirrored? All images are mirrored, see #172.

Also, I don't see any miscalibration in your picture.

**Comment by shamoorti** [comment]
Oh ok. I thought before me installing the latesr version it was not
mirrored. Strange. Thanks anyway.
