### ISSUE TITLE
link of GLFW3 static libraries in cmake

### ISSUE THREAD

**Issue by a-cvision** [OpenKinect/libfreenect2#478]
In the current version, the glfw3 static libraries are not linked.. this could cost some time for a lot of people as "make" will fail as such.

Perhaps someone could correct that in the cmake file.

Thanks

**Comment by xlz** [comment]
Not linked to libfreenect2.so or Protonect?

**Comment by a-cvision** [comment]
I don't have a very good know-how with the whole cmake -make toolchain. But I had to add $GLFW3_STATIC_LIBRARIES in the append libraries part of the cmake file in order for "make" to work. Otherwise it resulted in a bunch of unknown references to XRR_..

I apologize if it is a particular case for me. Though I can't imagine why that would happen just for me.

**Comment by xlz** [comment]
That means you didn't install OpenGL dependencies. mesa-common-dev freeglut3-dev libxrandr-dev libxi-dev

**Comment by a-cvision** [comment]
I checked that and they are installed, otherwise I wouldn't be able to link to the static libraries. But certainly this seems to be a strange particular case, thanks for the comments.
