### ISSUE TITLE
Error LNK1120: 1 resolved external symbol

### ISSUE THREAD

**Issue by jaebums** [OpenKinect/libfreenect2#489]
Hello, I have been trying to build the library but have failed over 1 week. I do not have a good experience solving this kind issues partly since I have been using C but not C++. Any comment how I can fix this kind of error?

![image 1](https://cloud.githubusercontent.com/assets/16108252/11515794/bd90d4a6-984d-11e5-94f0-4fb64ac00536.png)

**Comment by xlz** [comment]
It's a bug. I didn't test it on Windows.

MSVC refuses to resolve the symbol when the return type is different (a different type of pointer). I didn't see this with GCC. I'll create a fix promptly.

**Comment by xlz** [comment]
Can you try the above PR 490?

**Comment by jaebums** [comment]
0 Warning, 0 Error! Thank you so much!
