### ISSUE TITLE
cannot edit  /sys/module/i915/parameters/enable_cmd_parser file

### ISSUE THREAD

**Issue by chevalfoucher** [OpenKinect/libfreenect2#506]
I've tried in many ways to edit this file in a graphic terminal :
sudo su
echo 0 > /sys/module/i915/parameters/enable_cmd_parser
-> bash: /sys/module/i915/parameters/enable_cmd_parser: No such file or directory

or:
sudo vim /sys/module/i915/parameters/enable_cmd_parser
... can t open file for writing
Il never works? Any one knows why?

**Comment by xlz** [comment]
Are you using Beignet? Is your hardware Intel CPU? What is the kernel version?

**Comment by chevalfoucher** [comment]
Yes, I installed beignet Dev. My hardware is a Intel CPU as well as Intel GPU (intel HD graphics 3000). The version of my linux kernel is 3.13.0-71-generic.
My computer recognises the kinect, but I just see a black screnn when a run Protonect. I have the following log [Debug] [DepthPacketStreamParser] skipping depth packet

**Comment by xlz** [comment]
Try at least 3.16 kernel.

**Comment by chevalfoucher** [comment]
I updated my kernel to version 4.2 . Now i can set enable_cmd_parser to zero, but I still have 
[Debug] [DepthPacketStreamParser] skipping depth packet

**Comment by xlz** [comment]
skipping depth packet is not an error. It just tells you your gpu is too slow to catch up with the data source.

**Comment by floe** [comment]
Do you see any output if you run `./Protonect cpu`?
