### ISSUE TITLE
No response after running ./bin/Protonect 

### ISSUE THREAD

**Issue by zaidiawan** [OpenKinect/libfreenect2#511]
Hi,
I have been using Protonect before succefully on my lenovo Laptop with i7 processor and AMD Radeon R5 240 GPU. I have to install Protonect again. make was successful without any errors. But when I run Protonect, nothing happens. and nothing is shown up. I re-installed my ubuntu 14.04, the same situation!. What could be the possible problem. After running Protonect not only nothing shows up but also when I shutdown the system, the system can't shutdown. It seems something bad happens inside there. I also used the cpu, gpu and cl options separately. nothing changes.  Have you made any changes to libfreenect2?

cmake output:

 -- using tinythread as threading library
-- RPATH set to /usr/lib/x86_64-linux-gnu
-- Linking with these libraries: 
 /usr/lib/x86_64-linux-gnu/libusb-1.0.so
 /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0
 pthread
 /usr/lib/x86_64-linux-gnu/libglfw.so
 /usr/lib/x86_64-linux-gnu/libGL.so
 /usr/lib/x86_64-linux-gnu/libOpenCL.so
-- Configurating examples
-- Using in-tree freenect2 target
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zahid/drivers/libfreenect2/build

make output:

   [  3%] Built target generate_resources_tool
[ 88%] Built target freenect2
[100%] Built target Protonect

Regards,
Zahid

**Comment by floe** [comment]
What is the console output from `Protonect`?

**Comment by xlz** [comment]
If you have more information, please comment and reopen.
