### ISSUE TITLE
Change RGB camera parameters - Gain, White balance, exposure, etc

### ISSUE THREAD

**Issue by miguelriemoliveira** [OpenKinect/libfreenect2#522]
Hello,

Is there a way to change the RGB camera parameters? 
For example, how can I set exposure to manual?

I searched around and could not find any...

Best regards,

Miguel

**Comment by xlz** [comment]
No.

#420

**Comment by mriem** [comment]
Ok, thanks for the reply. I missed that issue.

Regards,

Miguel
