### ISSUE TITLE
restart the kinect

### ISSUE THREAD

**Issue by zfxw0206** [OpenKinect/libfreenect2#527]
I have a kinect, but sometimes, it may die. So I am thinking if I could write a code to detect it, if the kinect die, I will kill the kinect driver and restart it.

Does anybody have an idea about this?

Thank you!

**Comment by xlz** [comment]
If it "dies", you should report an issue. But considering the style of this issue you are writing in, I recommend you perform complete collection of relevant information before submitting an issue.

Error reporting in the library will be improved in 0.2.

**Comment by zfxw0206** [comment]
I am sorry, I may not state it clearly. The situation is my robot is using kinect to see something, but sometime the kinect may died. I can accept it died, but I want to write a code to detect kinect, if it died, the system will restart the kinect automatically.

In my mind, I will write a code to subscribe the topic, once the kinect died, I won't get the topic, then I will send "1" to a ".txt" file. I also write a ".bash" file, which is used to detect the ".txt" file, once I get "1", it will run "roslaunch kinect_bridge.launch" again.

Do you think this is doable and how could I make the ".bash" file run background?

**Comment by xlz** [comment]
You can create a new thread in your program and in that thread set a timer of 1 second. In the data receiving thread, reset the timer each time a new frame is received. Once the timer times out, restart.

**Comment by zfxw0206** [comment]
Thank you for your idea, but I have another question. How to restart kinect2_bridge.launch? Can we realize it by using cpp code?

**Comment by xlz** [comment]
There are too many ways to restart kinect2_bridge.launch. You can.

Here is an example:
```bash
while true; do
  roslaunch kinect2_bridge.launch
done
```

**Comment by zfxw0206** [comment]
This is a shell script, right?

**Comment by xlz** [comment]
Yes

**Comment by zfxw0206** [comment]
Ok, I did it. Thank you very much!

**Comment by xlz** [comment]
Then this issue is considered resolved.
