### ISSUE TITLE
OpenNi2 driver - image convert to opencv 

### ISSUE THREAD

**Issue by kruss84** [OpenKinect/libfreenect2#542]
@hanyazou I'm trying to convert an image from openni::VideoFrameRef to cv::Mat.
When I use the examples given for color and depth, I just get gray images.
Resolution of the images is correct, only the data is bad.

http://stackoverflow.com/questions/15966722/capture-rgb-from-kinnect-with-openni-and-show-with-opencv
http://answers.opencv.org/question/33513/opencv-asus-xtion-sensor/

When I start the program SimpleRead of Openni2, the depth image looks very good.
The readout of the Kinect v2 is working perfectly.

I would appreciate any suggestions or ideas to solve this problem.

**Comment by xlz** [comment]
@hanyazou

**Comment by hanyazou** [comment]
@kruss84 I will investigate the driver and opencv sample code. But I don't have a lot of experience with opencv. Could you please provide your source code include main() so that I can compile it without adding lines.
