### ISSUE TITLE
Ghosting or Multiple Exposures in IR image

### ISSUE THREAD

**Issue by aurelw** [OpenKinect/libfreenect2#544]
The IR image appears to have multiple exposures overlapped into one image. At least I can identify two separate exposures in a moving image with high contrast.

Is this just an artefact of how single frames are combined to one IR image? Is there a way to get a single frame with full IR illumiation and just one exposure?

**Comment by xlz** [comment]
http://research.microsoft.com/pubs/256286/stuehmer2015toftracking.pdf

TL;DR: requires firmware modification.

**Comment by xlz** [comment]
CANTFIX
