### ISSUE TITLE
Impossible to process depth image without processing color image

### ISSUE THREAD

**Issue by matthieu-ft** [OpenKinect/libfreenect2#548]
in the Registration module, I would like to be able to work only with depth and not to have to process the color image. Indeed, if I want to get any 3D Point associated with a given pixel value, the current implementation forces me to register the color image, which is time consuming and critical for my current application (I make projections on bodies that I detect using the depth image of the kinect).

I implemented two additional methods for that. See the pull request bellow.

**Comment by xlz** [comment]
To follow in #549.
