### ISSUE TITLE
how can i get data from Kinect v2 to PCL?

### ISSUE THREAD

**Issue by kerolos** [OpenKinect/libfreenect2#571]
hello,
the libfreenect2 is working very fine in my PC, but i wanna use this data from Kinect v2 into PCL. i followed this link "http://robotica.unileon.es/mediawiki/index.php/PCL/OpenNI_tutorial_1:_Installing_and_testing" but i think , it is only for kinect v1 by calling this function "Grabber* openniGrabber;  " .
thanks in advance

**Comment by xlz** [comment]
There is OpenNI2 interface you can probably use. PCL seems to have several OpenNI2 examples.

**Comment by moonsh** [comment]
How about following this ?

"https://github.com/giacomodabisias/libfreenect2pclgrabber"

He combined Libfreenect2 and PCL

**Comment by ahundt** [comment]
I also have a modified version of the above at https://github.com/ahundt/libfreenect2pclgrabber

**Comment by kerolos** [comment]
thanks a lot Moonsh and Ahundt for your replay. i really appreciate that.
