### ISSUE TITLE
Protonect example only works with "cl"

### ISSUE THREAD

**Issue by nylen** [OpenKinect/libfreenect2#573]
On OS X 10.10.5, with Kinect model 1520, the Protonect example only works in OpenCL mode.  Running `bin/Protonect` and `bin/Protonect gl` behaves as follows:

- Kinect "resets" (lights blink briefly, this seems to be normal)
- Computer (including mouse and keyboard) hangs for 15-20 seconds
- Application closes:

![image](https://cloud.githubusercontent.com/assets/227022/13031773/7fb3f584-d29d-11e5-8c39-4dde9042abe8.png)

After the application gets going, the debug lines are mostly "skipping depth packet" as in the screenshot, but there is occasionally one of these:

```
[Info] [VTRgbPacketProcessor] avg. time: 14.9957ms -> ~66.6858Hz
```

Also, during application init, these lines usually appear:

```
[Debug] [DepthPacketStreamParser] not all subsequences received 0
[Debug] [DepthPacketStreamParser] not all subsequences received 1016
```

With `bin/Protonect cl` everything works fine.

**Comment by xlz** [comment]
Is your Mac with Nvidia GPU? Check #205 and see how it relates to your case.

**Comment by nylen** [comment]
Yes, it's an Nvidia GPU.  I'll post more details on #205 later when I'm back at home.
