### ISSUE TITLE
Protonect on windows: failed to submit transfer: LIBUSB_ERROR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by mmeliabit** [OpenKinect/libfreenect2#580]
Hello,

I was trying to run Protonect on our Windows 8.1 and I can't get to make it run. I don't know what I am doing wrong. I followed the instructions and the only error I got was on the .cmd execution to build libusb, and I finished the compilation with VS using the libusb_2013.sln generated by the command.

I associated the libusbK 3.0.7.0 driver with Xbox NUI Sensor (Composite Parent). However, if I run again Zadig I do not see this device anymore (only Xbox NUI Sensor (without "Composite Parent"), and two NUI Sensor Adaptors.

The first error I get in the logs when I run Protonect is: [Error] [usb::TransferPool] failed to submit transfer: LIBUSB_ERROR_NOT_SUPPORTED Operation not supported or unimplemented on this platform

Full log attached.
[out.txt](https://github.com/OpenKinect/libfreenect2/files/137627/out.txt)

**Comment by mmeliabit** [comment]
I replaced my freenect and libusb DLLs with prebuild ones download from here: https://github.com/OpenKinect/libfreenect2/releases/tag/v0.1.0

Now it is working. I don't know what I did wrong.

**Comment by xlz** [comment]
https://github.com/OpenKinect/libfreenect2/wiki/Troubleshooting#libusb_error_notsupported

> Also check the build log of install_libusb_vs201?.cmd to look for any errors that disable the libusbK backend.

?

**Comment by xlz** [comment]
> the only error I got was on the .cmd execution to build libusb

What error? Can you post the log?

**Comment by langmingzhou** [comment]
Hello,
  I had meet the same error of @mmeliabit. I debug into Protonect, and it was stop in the line "return -1":
  if (enable_rgb && enable_depth)
  {
    if (!dev->start())
      return -1; //step out there
  }
and the information output in the screen is: [Error][usb::TransferPool] failed to submit transfer: LIBUSB_ERROR_NOT_SUPPORTED Operation not supported or unimplemented on this platform.

Also, I set enable_rgb=true and enable_depth = false. Then run Protonect again, then I got those error:
  while(!protonect_shutdown)
  {
    listener.waitForNewFrame(frames); // step out there
    libfreenect2::Frame *rgb = frames[libfreenect2::Frame::Color];
    libfreenect2::Frame *ir = frames[libfreenect2::Frame::Ir];
    libfreenect2::Frame *depth = frames[libfreenect2::Frame::Depth];
and the information output in the screen is: [Error] [RgbPacketStreamParser] packetsize or sequence doesn't match!

My OS is window 10. And the old version:
https://github.com/OpenKinect/libfreenect2/releases/tag/v0.1.0
can work successfully in my computer. The same confusion: I don't know what I did wrong.

**Comment by xlz** [comment]
@langmingzhou 

> Also check the build log of install_libusb_vs201?.cmd to look for any errors that disable the libusbK backend.

Do you see any errors?

**Comment by langmingzhou** [comment]
I run install_libusb_vs2013.cmd in git shell. And there are some errors, I record them in a screenshot. 
![error](https://cloud.githubusercontent.com/assets/17394169/13207442/54184b7a-d949-11e5-84d7-9cfe60d0126c.png)

**Comment by langmingzhou** [comment]
But I can finished the compilation with VS using the libusb_2013.sln generated by the command "install_libusb.sh". The previous debug work of protonect is based on such libusb-1.0 dll and libusb-1.0 lib. And the version of those dll and lib are win32.

**Comment by xlz** [comment]
OK, I found out I forgot to update the script for VS2013. This is the merge conflict that makes your libusb not work.

Try the latest master now.

**Comment by langmingzhou** [comment]
Ok, it is working. Thanks a lot for your work. And another question: can I change the platform to win32 from original x64 cause my main framework is based on win32?

**Comment by xlz** [comment]
I don't know. It is not tested under win32 so there is no guarantee it will work.

Btw, building with win32 results in worse performance from a test long time ago.
