### ISSUE TITLE
[Windows7] Kinect V2 open fail

### ISSUE THREAD

**Issue by charles-lo** [OpenKinect/libfreenect2#59]
Currently, I'm successful to building and running the protonect. 
But I fail to run it with Kinect V2 when setting UsbControl::setIrInterfaceState.  The driver seems installed successfully.
following is the error log from protonect. Would you have any advice?

![image](https://cloud.githubusercontent.com/assets/5556379/4508631/89343e98-4b17-11e4-84be-cc65fb7171ea.png)

========================================================================
error logs:
[Freenect2DeviceImpl] opening...
[UsbControl::claimInterfaces(IrInterfaceId)] failed! libusb error -12: LIBUSB_ERROR_NOT_SUPPORTED
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] deallocating usb transfer pools...
[Freenect2DeviceImpl] closing usb device...
[Freenect2DeviceImpl] closed
[Freenect2DeviceImpl] failed to open Kinect v2 @3:1!
no device connected or failure opening the default one!

or

[Freenect2DeviceImpl] opening...
[UsbControl::setIrInterfaceState] failed! libusb error -5: LIBUSB_ERROR_NOT_FOUND
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] releasing usb interfaces...
[UsbControl::releaseInterfaces(IrInterfaceId)] failed! libusb error -5: LIBUSB_ERROR_NOT_FOUND
[Freenect2DeviceImpl] deallocating usb transfer pools...
[Freenect2DeviceImpl] closing usb device...
[Freenect2DeviceImpl] closed
[Freenect2DeviceImpl] failed to open Kinect v2 @3:1!
no device connected or failure opening the default one!

**Comment by DrFuzzy** [comment]
Same problem here (libusb error -6: LIBUSB_ERROR_BUSY) in Ubuntu 14.04:

[quote]
delk@Darwin:~/libfreenect2/examples/protonect$ sudo ./bin/Protonect
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 11 usb devices connected
[Freenect2Impl] found valid Kinect v2 @1:10 with serial 503526742542
[Freenect2Impl] found 1 devices
[Freenect2DeviceImpl] opening...
[UsbControl::claimInterfaces(IrInterfaceId)] failed! libusb error -6: LIBUSB_ERROR_BUSY
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] deallocating usb transfer pools...
[Freenect2DeviceImpl] closing usb device...
[Freenect2DeviceImpl] closed
[Freenect2DeviceImpl] failed to open Kinect v2 @1:10!
no device connected or failure opening the default one!
[/quote]

lsusb lists:

delk@Darwin:~/libfreenect2/examples/protonect$ lsusb
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 006 Device 002: ID 046d:c018 Logitech, Inc. Optical Wheel Mouse
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 010: ID 045e:02d8 Microsoft Corp. 
Bus 001 Device 009: ID 045e:02d9 Microsoft Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

Any ideas?

**Comment by floe** [comment]
According to the lsusb output, you don't have an USB 3 controller at all?

**Comment by a-m-p-m** [comment]
Hello,

Do I *have to* have a USB 3.0 controller to communicate with Kinect for Xbox One using libfreenect2 ?
If so, is this limitation on the side of the Kinect device or on the side of libfreenect2 ?

I would like to acquire depth and IR frames only. I think this would be possible to do via a USB 2.0 connection.
I am working with Ubuntu (12.04/14.04).


Thanks

**Comment by christiankerl** [comment]
USB3 is *required* and it won't work without

**Comment by floe** [comment]
To clarify, this is a hardware limitation. The bandwidth of USB 2 is just not sufficient for the raw data stream. Closing.

**Comment by BenjaminRothschild** [comment]
hi,I have the same question too.just like this:
C:\Users\benjamin>E:\pro_VS\libfreenect2-master\examples\protonect\bin\Debug\Protonect.exe
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 10 usb devices connected
[Freenect2Impl] failed to open Kinect v2 @3:4!
[Freenect2Impl] found valid Kinect v2 @3:4 with serial 500344540242
[Freenect2Impl] found 1 devices
[Freenect2DeviceImpl] opening...
[UsbControl::claimInterfaces(IrInterfaceId)] failed! libusb error -12: LIBUSB_ERROR_NOT_SUPPORTED
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] deallocating usb transfer pools...
[Freenect2DeviceImpl] closing usb device...
[Freenect2DeviceImpl] closed
[Freenect2DeviceImpl] failed to open Kinect v2 @3:4!
no device connected or failure opening the default one!
you can see ,the OS is win8 , I have the K4W2 installed,I made the project just as the "ReadMe",I have no ideas now.

**Comment by floe** [comment]
You need to use an USB3 controller, as stated above.

**Comment by BenjaminRothschild** [comment]
yes,I used the USB3.0 .now ,it has been solved ,follow :
https://github.com/OpenKinect/libfreenect2/issues/105#issuecomment-95313200
 ,thank you all the same.

**Comment by 1andres1** [comment]
Hi Im having the same problem on Mac
64 mac
:/Applications/Processing.app/Contents/Java/core/library:/Users/imac/Documents/Processing 3/libraries/openkinect_processing/library:/Applications/Processing.app/Contents/MacOS/v2/mac
Found path: /Users/imac/Documents/Processing 3/libraries/openkinect_processing/library/v2/mac/
Init Kinect2 
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 10 usb devices connected
[Freenect2Impl] found valid Kinect v2 @253:6 with serial 020846141747
[Freenect2Impl] found 1 devices
1 Device Connected!
[OpenCLDepthPacketProcessor::listDevice]  devices:
  0: Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz (CPU)[Intel]
  1: ATI Radeon HD 5750 (GPU)[AMD]
[OpenCLDepthPacketProcessor::init]  selected device: ATI Radeon HD 5750 (GPU)[AMD]
Devce: 0
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 10 usb devices connected
[Freenect2Impl] found valid Kinect v2 @253:6 with serial 020846141747
[Freenect2Impl] found 1 devices
[Freenect2DeviceImpl] opening...
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] deallocating usb transfer pools...
[Freenect2DeviceImpl] closing usb device...
[UsbControl::claimInterfaces(IrInterfaceId)] failed! libusb error -3: LIBUSB_ERROR_ACCESS
[Freenect2DeviceImpl] closed
[Freenect2DeviceImpl] failed to open Kinect v2 @253:6!
no device connected or failure opening the default one!
