### ISSUE TITLE
libfreenect2 builds but doesn't run Protonect

### ISSUE THREAD

**Issue by robozo** [OpenKinect/libfreenect2#590]
Hi, I have a modified Protonect running just fine on a mid-2012 macbook Pro running 10.8.5,
and am attempting to install libfreenect2 and Protonect on a nearly identical machine, and am having
problems.  Things have changed with the new version I guess.

I got a libfreenect2 build error kVTVideoDecoderSpecification_EnableHardwareAcceleratedVideoDecoder not defined in
vt_rgb_packet_processor.cpp.  I guess this is new in 10.9, but useless, there is no hardware
jpeg decoding on mac, is there?

So I manually defined that identifier = 0 in vt_rgb_packet_processor.cpp and libfreenect2 built,
but Protonect won't run.  It finds the valid Kinect, with serial number ####, then bombs out
with Trace/BPT trap: 5.  Google tells me this is a dynamic library problem, but I don't know
how to proceed, and whether this is related to my earlier problem.

Should I try reverting to an earlier library?

Any suggestions welcome!

rob

...for the moment gave up trying to get new version to work.  copied libfreenect2.dylib from
old machine into /usr/local/lib in the new machine, things are working.

**Comment by xlz** [comment]
@fran6co This time we have 10.8.

https://developer.apple.com/library/mac/releasenotes/General/APIDiffsMacOSX10_9/VideoToolbox.html
```
Added kVTVideoDecoderSpecification_EnableHardwareAcceleratedVideoDecoder
Added kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder
```
What happens if you use kVTVideoDecoderSpecification_RequireHardwareAcceleratedVideoDecoder?

**Comment by fran6co** [comment]
I think I can remove the hardware accelerated stuff because it's not actually accelerated in Mac... It is for IOS but it should be using it by default. I'll create the PR and test it for 10.8

**Comment by fran6co** [comment]
Just tried in 10.8 and works no problem.

**Comment by robozo** [comment]
Thanks!  Sorry about 10.8, is stable for me for a lot of old code.
It could have been worse, could have been classic mac 9.1!

**Comment by fran6co** [comment]
The patch was trivial, as long Apple doesn't add JPEG hardware acceleration by setting some flags we are going to be ok.
