### ISSUE TITLE
cl.hpp installation?

### ISSUE THREAD

**Issue by ahundt** [OpenKinect/libfreenect2#595]
I'm using iai_kinect2 and it also needs the cl.hpp provided by libfreenect2 as discussed here with iai_kinect2:

https://github.com/code-iai/iai_kinect2/pull/235

Is it best for dependent projects to have their own copy of the header or would it make more sense for libfreenect2 to start including it in the installation step when appropriate?

**Comment by xlz** [comment]
cl.h is provided by OpenCL ICD itself, containing hardware specific definitions.

We ship cl.hpp which is a C++ wrapper.

**Comment by ahundt** [comment]
Sorry, I meant cl.hpp, does that make sense for including in the install step?

**Comment by xlz** [comment]
No. cl.hpp is not part of our public API.
