### ISSUE TITLE
Ubuntu 14.04 error

### ISSUE THREAD

**Issue by giacomodabisias** [OpenKinect/libfreenect2#60]
Hi, I have clone the git and installed the dependencies. I am working on ubuntu 14.04.

At first I had to change the vendor id to 
Bus 009 Device 006: ID 045e:02d9 Microsoft Corp.
since it was set to 045e:02d8.

After that protonect got stucked at :

```
 libusb_get_string_descriptor_ascii(dev_handle, dev_desc.iSerialNumber, buffer, sizeof(buffer));
```

which gave me always the -2 error. 
I googled a bit and I found out that with xusb I could get the right serial number, so I substituted the code with the following :

```
r = libusb_get_string_descriptor(dev_handle, 0, 0, string, 128);
              if (r > 0) {
                  nb_strings = string[0];
                  for (int i=1; i<nb_strings; i++) {
                          if (libusb_get_string_descriptor_ascii(dev_handle, (uint8_t)i, string, 128) >= 0) {
                                  printf("   String (%d/%d): \"%s\"\n", i, nb_strings-1, string);
                          }
                  }
              }
```

and this worked printing:
String (1/3): "Microsoft Corporation  "
String (2/3): "NuiSensor Adaptor      "

Going on the program crashes when checking the IrInterfaceId in the following call 

```
UsbControl::ResultCode UsbControl::claimInterfaces()
{
  UsbControl::ResultCode code = Success;
  int r;

  r = libusb_claim_interface(handle_, ControlAndRgbInterfaceId);
  code = checkLibusbResult("claimInterfaces(ControlAndRgbInterfaceId)", r);

  if(code == Success)
  {
    r = libusb_claim_interface(handle_, IrInterfaceId);
    code = checkLibusbResult("claimInterfaces(IrInterfaceId)", r);
  }

  return code;
}
```

in usb_control.cpp
getting:
[UsbControl::claimInterfaces(IrInterfaceId)] failed! libusb error -5: LIBUSB_ERROR_NOT_FOUND.

The complete output is:

gf@Pelars-GF:~/Libraries/libfreenect2/examples/protonect/bin$ sudo ./Protonect  
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 15 usb devices connected
   String (1/3): "Microsoft Corporation  "
   String (2/3): "NuiSensor Adaptor      "
[Freenect2Impl] found valid Kinect v2 @9:4 with serial NuiS
[Freenect2Impl] found 1 devices
[Freenect2DeviceImpl] opening...
[UsbControl::claimInterfaces(IrInterfaceId)] failed! libusb error -5: LIBUSB_ERROR_NOT_FOUND
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] deallocating usb transfer pools...
[Freenect2DeviceImpl] closing usb device...
[Freenect2DeviceImpl] closed
[Freenect2DeviceImpl] failed to open Kinect v2 @9:4!
no device connected or failure opening the default one!

and lsusb gives me:

Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 006 Device 002: ID 046d:c31f Logitech, Inc. 
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 004: ID 046d:c517 Logitech, Inc. LX710 Cordless Desktop Laser
Bus 001 Device 003: ID 1307:0330 Transcend Information, Inc. 63-in-1 Multi-Card Reader/Writer
Bus 001 Device 002: ID 0409:005a NEC Corp. HighSpeed Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 009 Device 006: ID 045e:02d9 Microsoft Corp. 
Bus 009 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 010 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub

usb controller:

01:00.0 USB controller: Renesas Technology Corp. uPD720201 USB 3.0 Host Controller (rev 03)

Thank you very much!

**Comment by bellekci** [comment]
I had the same problem. It was a permission problem. Running protonect as sudo solved it. This thread saved me a lot of time. Thanks.

**Comment by milq** [comment]
Solved for me using `sudo`. Thanks, Christian!

**Comment by zhangtemplar** [comment]
It works for me to.
