### ISSUE TITLE
Beignet-opencl-icd no supported GPU found

### ISSUE THREAD

**Issue by cpaniagua1** [OpenKinect/libfreenect2#606]
Hello,

I'm working with Intel Iris 6100 (Brodwell GT3) graphics and Ubuntu 14.04. I followed the installation instructions for Linux and everything was fine but when I run ./Proctonect cl  I have problems with OpenCL. 

I get the following error:
beignet-opencl-icd no supported GPU found

I read at the end of this thread https://github.com/OpenKinect/libfreenect2/issues/109 that there were problems with Beignet and Brodwell. 

Can somebody help me with this? 
Thanks in advance.

**Comment by xlz** [comment]
We'll create a ppa for beignet 1.1.1

https://github.com/OpenKinect/libfreenect2/issues/558#issuecomment-190405220

**Comment by cpaniagua1** [comment]
Would you mind telling me when it will be create?
Is there any way to install beignet 1.1.1 without the ppa?

**Comment by xlz** [comment]
> For the record, I built a ported beignet 1.1.1 to Ubuntu 14.04 with the beignet sources (1.1.1) from Ubuntu 16.04, changed debian/control to remove build dependencies on clang, llvm, installed clang-3.6 libclang-3.6-dev, and apt-src build beignet-dev built some beignet 1.1.1 debs.

**Comment by floe** [comment]
Try this PPA: https://launchpad.net/~floe/+archive/ubuntu/beignet (only AMD64 at the moment).

**Comment by cpaniagua1** [comment]
Thank your very much!
It solved my problem.
