### ISSUE TITLE
Stream mulitple Kinectv2s

### ISSUE THREAD

**Issue by siriusye** [OpenKinect/libfreenect2#607]
Sorry this is not really a bug, but i could not find other places to get help. I successfully connect 2 kinect v2 on one computer using libfreenect2, They can be opened with openDevice. However, I notice that they cannot stream data simultaneously. The problem seems on the pipline step. Only one gpu pipline can be allocated to one device. One device with gpu piplien, the other with cpu pipline will not work. My computer only have a single graphics card, dose this mean only one stream can be processed? 

Thanks very much!

**Comment by xlz** [comment]
You should create one packet pipeline for each device.

**Comment by siriusye** [comment]
I did new a instance of packet pipeline for each device. Could I get a confirmation about:
If everything is right, the driver can stream 2 kinect v2 data on a single graphic card high end computer?

**Comment by xlz** [comment]
yes

**Comment by siriusye** [comment]
it is working now. I did render two images to the same framebuffer..Thanks very much mate!
