### ISSUE TITLE
OSX build  "libusb.h" not found 

### ISSUE THREAD

**Issue by apparentVJ** [OpenKinect/libfreenect2#62]

**Comment by ThomasLengeling** [comment]
Hello I get tha same issue on 10.10.2 Mac, any solution for this? 

I get this when I do the 5 step 

make && make install 

In file included from /Users/tom/Documents/GitHub/libfreenect2/examples/protonect/src/transfer_pool.cpp:27:
/Users/tom/Documents/GitHub/libfreenect2/examples/protonect/include/libfreenect2/usb/transfer_pool.h:31:10: fatal error: 
      'libusb.h' file not found
#include <libusb.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/freenect2.dir/src/transfer_pool.cpp.o] Error 1
make[1]: *** [CMakeFiles/freenect2.dir/all] Error 2
make: *** [all] Error 2

**Comment by gaborpapp** [comment]
Check if you have a ```depends/libusb``` folder. If you don't try running ```depends/install_mac.sh```.

**Comment by ThomasLengeling** [comment]
hey.

Only the folder libusb_src, probability it did not compile successfully.

here is the compile output when doing 

sh ./depends/install_mac.sh

https://gist.github.com/ThomasLengeling/e07149706842022a3d39

**Comment by ThomasLengeling** [comment]
ok, so apparently libtool wasn't installed, I Installed libtool with `brew install libtool` and now I get this, which

./bootstrap.sh: line 18: aclocal: command not found
./install_deps.sh: line 16: ./configure: No such file or directory

I went to the directory libusb_src and did `sudo ./bootstrap.sh` but i cannot find the `./configure` file
