### ISSUE TITLE
Error during installation on OSX (missing:  PKG_CONFIG_EXECUTABLE)

### ISSUE THREAD

**Issue by MrfksIv** [OpenKinect/libfreenect2#620]
After installing all the packages needed, i created the build folder and cd-ed there. But when i run the command `cmake ..` i get the following error:

`-- using tinythread as threading library
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
CMake Error at /sw/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find LibUSB (missing: LibUSB_LIBRARIES)
Call Stack (most recent call first):
  /sw/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/FindLibUSB.cmake:87 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:93 (FIND_PACKAGE)`

After a couple of hours of searching online i am still not closer to solving this. Can anyone help?

Thanks

**Comment by hanyazou** [comment]
Did you install pkg config package?
$ brew install pkgconfig

**Comment by xlz** [comment]
> Make sure these build tools are available: wget, git, cmake, pkg-config. Xcode may provide some of them. Install the rest via package managers.

**Comment by v2k** [comment]
@hanyazou @xlz 
`brew install pkgconfig `

This fixed my issue too, can we add this to the OSX install readme?

**Comment by xlz** [comment]
From README:

> Make sure these build tools are available: wget, git, cmake, **pkg-config**. Xcode may provide some of them. Install the rest via package managers.

**Comment by nijisakai** [comment]
> brew install pkgconfig

like a charm
