### ISSUE TITLE
Vaapi sudo access problem

### ISSUE THREAD

**Issue by shamoorti** [OpenKinect/libfreenect2#635]
Hey guys,
When I run Protonect without sudo it runs fine but RGB processes with TurboJpeg, meanwhile if I use sudo Vaapi processes RGB! I have the rules copied in rules.d by the way. Has anyone encountered this problem? I have both Nvidia and Intel graphic card but I have put Nvidia as the main GPU. Another problem is after some processings of depth and RGB packets, prototonect starts to skip packages although I have the view. What can be the cause? Something is wrong with Nvidia and ubuntu 14.4 I guess.

mobin@mobin-Lenovo-IdeaPad-Y510P:~/freenect2$ sudo /home/mobin/freenect2/build/bin/Protonect cuda
Version: 0.2.0
Environment variables: LOGFILE=<protonect.log>
Usage: /home/mobin/freenect2/build/bin/Protonect [-gpu=<id>] [gl | cl | cuda | cpu] [<device serial>]
        [-noviewer] [-norgb | -nodepth] [-help] [-version]
        [-frames <number of frames to process>]
To pause and unpause: pkill -USR1 Protonect
[Info] [CudaDepthPacketProcessorImpl] device 0: GeForce GT 750M @ 967MHz Memory 2047MB
[Info] [CudaDepthPacketProcessorImpl] selected device 0
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_37
libva info: va_openDriver() returns 0
[Info] [VaapiRgbPacketProcessorImpl] driver: Intel i965 driver for Intel(R) Haswell Mobile - 1.5.0
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 12 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @2:9 with serial 025613444747
[Info] [Freenect2Impl] found 1 devices
[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] transfer pool sizes rgb: 20*16384 ir: 60*8*33792
[Info] [Freenect2DeviceImpl] opened
[Info] [Freenect2DeviceImpl] starting...
[Debug] [Freenect2DeviceImpl] status 0x090000: 9729
[Debug] [Freenect2DeviceImpl] status 0x090000: 9731
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Info] [Freenect2DeviceImpl] started
device serial: 025613444747
device firmware: 4.0.3911.0
[Debug] [DepthPacketStreamParser] not all subsequences received 0
[Debug] [DepthPacketStreamParser] not all subsequences received 960
[Debug] [DepthPacketStreamParser] skipping depth packet
[Info] [DepthPacketStreamParser] 1 packets were lost
[Info] [CudaDepthPacketProcessor] avg. time: 5.66269ms -> ~176.594Hz
[Info] [VaapiRgbPacketProcessor] avg. time: 6.33298ms -> ~157.904Hz
[Info] [CudaDepthPacketProcessor] avg. time: 5.66815ms -> ~176.424Hz
[Info] [VaapiRgbPacketProcessor] avg. time: 6.31349ms -> ~158.391Hz
[Info] [CudaDepthPacketProcessor] avg. time: 5.65137ms -> ~176.948Hz
[Info] [VaapiRgbPacketProcessor] avg. time: 6.26184ms -> ~159.697Hz
[Info] [CudaDepthPacketProcessor] avg. time: 5.64062ms -> ~177.286Hz
[Info] [VaapiRgbPacketProcessor] avg. time: 6.21346ms -> ~160.941Hz
[Info] [CudaDepthPacketProcessor] avg. time: 5.6529ms -> ~176.9Hz
[Info] [VaapiRgbPacketProcessor] avg. time: 6.22188ms -> ~160.723Hz
[Info] [CudaDepthPacketProcessor] avg. time: 5.63842ms -> ~177.355Hz
[Info] [VaapiRgbPacketProcessor] avg. time: 6.37211ms -> ~156.934Hz
[Info] [CudaDepthPacketProcessor] avg. time: 5.66183ms -> ~176.621Hz
[Info] [VaapiRgbPacketProcessor] avg. time: 6.15087ms -> ~162.579Hz
[Info] [CudaDepthPacketProcessor] avg. time: 5.69317ms -> ~175.649Hz
[Info] [VaapiRgbPacketProcessor] avg. time: 6.36534ms -> ~157.101Hz
[Info] [CudaDepthPacketProcessor] avg. time: 5.6228ms -> ~177.847Hz
[Info] [VaapiRgbPacketProcessor] avg. time: 6.32271ms -> ~158.16Hz
[Info] [CudaDepthPacketProcessor] avg. time: 5.6516ms -> ~176.941Hz
[Info] [VaapiRgbPacketProcessor] avg. time: 6.25138ms -> ~159.965Hz
[Info] [CudaDepthPacketProcessor] avg. time: 5.61526ms -> ~178.086Hz
[Info] [VaapiRgbPacketProcessor] avg. time: 6.27754ms -> ~159.298Hz
[Info] [CudaDepthPacketProcessor] avg. time: 5.6749ms -> ~176.215Hz
[Info] [VaapiRgbPacketProcessor] avg. time: 6.38243ms -> ~156.68Hz
[Info] [CudaDepthPacketProcessor] avg. time: 5.62556ms -> ~177.76Hz
[Info] [VaapiRgbPacketProcessor] avg. time: 6.09803ms -> ~163.987Hz
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Info] [DepthPacketStreamParser] 2 packets were lost
[Info] [CudaDepthPacketProcessor] avg. time: 5.63666ms -> ~177.41Hz
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Info] [VaapiRgbPacketProcessor] avg. time: 6.06912ms -> ~164.769Hz
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Info] [DepthPacketStreamParser] 2 packets were lost
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Info] [DepthPacketStreamParser] 2 packets were lost
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Info] [CudaDepthPacketProcessor] avg. time: 5.93441ms -> ~168.509Hz
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [DepthPacketStreamParser] skipping depth packet
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Info] [DepthPacketStreamParser] 10 packets were lost
^C[Info] [Freenect2DeviceImpl] stopping...
[Info] [Freenect2DeviceImpl] canceling rgb transfers...
[Info] [Freenect2DeviceImpl] canceling depth transfers...
[Info] [Freenect2DeviceImpl] stopped
[Info] [Freenect2DeviceImpl] closing...
[Info] [Freenect2DeviceImpl] releasing usb interfaces...
[Info] [Freenect2DeviceImpl] deallocating usb transfer pools...
[Info] [Freenect2DeviceImpl] closing usb device...
[Info] [Freenect2DeviceImpl] closed
[Info] [Freenect2DeviceImpl] closing...
[Info] [Freenect2DeviceImpl] already closed, doing nothing

**Comment by xlz** [comment]
I don't see anything wrong.

Also, https://github.com/OpenKinect/libfreenect2/wiki/Troubleshooting#things-not-to-do
