### ISSUE TITLE
Running libfreenect 2 on Intel NUC

### ISSUE THREAD

**Issue by pnambiar** [OpenKinect/libfreenect2#636]
I'm trying to run libfreenect 2 on Inel NUC -NUC5i7RYH with ubuntu Ubuntu 14.04.4 LTS.
I was able to install it successfully. However ./Protonect gives me the following error
Version: 0.2.0
Environment variables: LOGFILE=<protonect.log>
Usage: ./Protonect [-gpu=<id>] [gl | cl | cuda | cpu] [<device serial>]
        [-noviewer] [-norgb | -nodepth] [-help] [-version]
        [-frames <number of frames to process>]
To pause and unpause: pkill -USR1 Protonect
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 10 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @3:3 with serial 503931742542
[Info] [Freenect2Impl] found 1 devices
[Error] [OpenGLDepthPacketProcessorImpl] GLFW error 65544 X11: RandR gamma ramp support seems broken
[Error] [OpenGLDepthPacketProcessorImpl] GLFW error 65543 The requested client API version is unavailable
[Error] [OpenGLDepthPacketProcessor] Failed to create opengl window.
narayanan@nuc4:~/libfreenect2/build/bin$ 

Version, Platform, and Hardware Bug Found:
1. `git log -1 --oneline`
2. `uname -a`
   Linux nuc4 3.16.0-70-generic #90~14.04.1-Ubuntu SMP Wed Apr 6 22:56:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
3. `lsusb -t`
   lsusb -t
   /:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
   |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/1p, 5000M
       |__ Port 1: Dev 3, If 0, Class=Vendor Specific Class, Driver=, 5000M
       |__ Port 1: Dev 3, If 1, Class=Vendor Specific Class, Driver=, 5000M
       |__ Port 1: Dev 3, If 2, Class=Audio, Driver=snd-usb-audio, 5000M
       |__ Port 1: Dev 3, If 3, Class=Audio, Driver=snd-usb-audio, 5000M
   /:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/11p, 480M
   |__ Port 1: Dev 6, If 0, Class=Hub, Driver=hub/1p, 480M
   |__ Port 3: Dev 4, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
   |__ Port 4: Dev 5, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
   |__ Port 7: Dev 3, If 0, Class=Wireless, Driver=btusb, 12M
   |__ Port 7: Dev 3, If 1, Class=Wireless, Driver=btusb, 12M
   /:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/2p, 480M
   |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/8p, 480M
4. `lspci -nn`

00:00.0 Host bridge [0600]: Intel Corporation Broadwell-U Host Bridge -OPI [8086:1604](rev 09)
00:02.0 VGA compatible controller [0300]: Intel Corporation Broadwell-U Integrated Graphics [8086:162b](rev 09)
00:03.0 Audio device [0403]: Intel Corporation Broadwell-U Audio Controller [8086:160c](rev 09)
00:14.0 USB controller [0c03]: Intel Corporation Wildcat Point-LP USB xHCI Controller [8086:9cb1](rev 03)
00:16.0 Communication controller [0780]: Intel Corporation Wildcat Point-LP MEI Controller #1 [8086:9cba](rev 03)
00:19.0 Ethernet controller [0200]: Intel Corporation Ethernet Connection (3) I218-V [8086:15a3](rev 03)
00:1b.0 Audio device [0403]: Intel Corporation Wildcat Point-LP High Definition Audio Controller [8086:9ca0](rev 03)
00:1c.0 PCI bridge [0604]: Intel Corporation Wildcat Point-LP PCI Express Root Port #1 [8086:9c90](rev e3)
00:1c.3 PCI bridge [0604]: Intel Corporation Wildcat Point-LP PCI Express Root Port #4 [8086:9c96](rev e3)
00:1d.0 USB controller [0c03]: Intel Corporation Wildcat Point-LP USB EHCI Controller [8086:9ca6](rev 03)
00:1f.0 ISA bridge [0601]: Intel Corporation Wildcat Point-LP LPC Controller [8086:9cc3](rev 03)
00:1f.2 SATA controller [0106]: Intel Corporation Wildcat Point-LP SATA Controller [AHCI Mode] [8086:9c83](rev 03)
00:1f.3 SMBus [0c05]: Intel Corporation Wildcat Point-LP SMBus Controller [8086:9ca2](rev 03)
02:00.0 Network controller [0280]: Intel Corporation Wireless 7265 [8086:095a](rev 59)

Steps to Reproduce:
1. 
2. 
3. 

Actual Results:

Expected Results:

Reproducibility:

Additional Information:

**Comment by xlz** [comment]
`./bin/Protonect -noviewer cl`

**Comment by pnambiar** [comment]
./bin/Protonect -noviewer cl
Version: 0.2.0
Environment variables: LOGFILE=<protonect.log>
Usage: ./bin/Protonect [-gpu=<id>] [gl | cl | cuda | cpu] [<device serial>]
        [-noviewer] [-norgb | -nodepth] [-help] [-version]
        [-frames <number of frames to process>]
To pause and unpause: pkill -USR1 Protonect
X server found. dri2 connection failed! 
X server found. dri2 connection failed! 
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
[Info] [OpenCLDepthPacketProcessorImpl]  devices:
[Error] [OpenCLDepthPacketProcessorImpl] could not find any suitable device
[Error] [OpenCLAllocator] b->buffer = cl::Buffer(context, CL_MEM_WRITE_ONLY | CL_MEM_ALLOC_HOST_PTR, size, NULL, &err): -34
[Error] [OpenCLAllocator] b->buffer = cl::Buffer(context, CL_MEM_WRITE_ONLY | CL_MEM_ALLOC_HOST_PTR, size, NULL, &err): -34
Segmentation fault (core dumped)

**Comment by pnambiar** [comment]
After installing beignet1.1. I get

./bin/Protonect -noviewer cl
Version: 0.2.0
Environment variables: LOGFILE=<protonect.log>
Usage: ./bin/Protonect [-gpu=<id>] [gl | cl | cuda | cpu] [<device serial>]
        [-noviewer] [-norgb | -nodepth] [-help] [-version]
        [-frames <number of frames to process>]
To pause and unpause: pkill -USR1 Protonect
X server found. dri2 connection failed! 
Device open failed, aborting...
X server found. dri2 connection failed! 
Device open failed, aborting...
cl_get_gt_device(): error, unknown device: ffffffff
[Info] [OpenCLDepthPacketProcessorImpl]  devices:
[Error] [OpenCLDepthPacketProcessorImpl] could not find any suitable device
[Error] [OpenCLAllocator] b->buffer = cl::Buffer(context, CL_MEM_WRITE_ONLY | CL_MEM_ALLOC_HOST_PTR, size, NULL, &err): -34
[Error] [OpenCLAllocator] b->buffer = cl::Buffer(context, CL_MEM_WRITE_ONLY | CL_MEM_ALLOC_HOST_PTR, size, NULL, &err): -34

**Comment by wiedemeyer** [comment]
looks like the same problem as here: https://github.com/code-iai/iai_kinect2/issues/248
But that was with a Skylake NUC, not the Broadwell NUC.

**Comment by xlz** [comment]
There is no much we can do here because this is really a system configuration issue.
