### ISSUE TITLE
Loss of Depth Packets

### ISSUE THREAD

**Issue by niteshtm** [OpenKinect/libfreenect2#637]
Hi there!! I have built libfreenect2 with OpenCL . But in the console log I can see loss of Depth packets like 30 packets lost sometimes 15 packets lost . I have Intel i5 with onboard Intel graphics card ,using  usb 3.0 control . My total CPU usage is not exceeding 50-60 % . And I can notice frame drops . Just wanted to know how these packet loss can be decreased . How can i get 30 fps ?
And I am using SyncMultiFrameListener . So should I go for different listeners for both streams i.e RGB and Depth , but I need synced frames also for both. Suggest me something.
Thanks .

**Comment by xlz** [comment]
`./bin/Protonect -noviewer cl`.

**Comment by niteshtm** [comment]
Sorry ,l I didn't get you .

**Comment by hanshammel1337** [comment]
He asked you to post the output of `Protonect` with the arguments `-noviewer cl`. User xlz assumes your are using Linux, so he posted the Linux command for this. As your screenshots show, your are using Windows. I'am not familiar with libfreenect2 and Windows, but in your 1st screenshot you see the avaible arguments for KinectStreams.exe (which seems the same as Protonect in the Linux world?!). So just run `KinectStreams.exe -noviewer cl` and post the output here

**Comment by niteshtm** [comment]
Thanks hanshammel1337 !! Well even exclusively providing that argument also I am getting the same result only. I am using Windows 8.1 to be very specific.

**Comment by xlz** [comment]
That's the best you can get because the lower performance of JPEG decoding on Windows. If you want better performance use Linux.

**Comment by niteshtm** [comment]
That's sad !! My application is on Windows only :(
