### ISSUE TITLE
How to create two seperate listeners for rgb and depth data?

### ISSUE THREAD

**Issue by niteshtm** [OpenKinect/libfreenect2#638]
Need to create two seperate listeners for rgb and depth data? How can we implement it? 
Thanks.

**Comment by xlz** [comment]
```
libfreenect2::SyncMultiFrameListener rgb_listener(libfreenect2::Frame::Color);
libfreenect2::SyncMultiFrameListener ir_listener(libfreenect2::Frame::Ir | libfreenect2::Frame::Depth);
dev->setColorFrameListener(&rgb_listener);
dev->setIrAndDepthFrameListener(&ir_listener);
```

**Comment by niteshtm** [comment]
No but I thought SyncMultiFrameListener still waits for all the frames to arrive as it works in sync and that causes a very small amount of  delay . I was not aware of this fact that if we pass Color only as argument then it won't wait for others frame internally or so ? 
Correct me if I am wrong please .

**Comment by niteshtm** [comment]
Still waiting for an answer.

**Comment by xlz** [comment]
You were not wrong, so I didn't correct you.

**Comment by niteshtm** [comment]
xlz: I have calculated the fps I am getting and it's really bad. On an average it's 8 . Please suggest me something in order to increase the fps if there is any way.

**Comment by xlz** [comment]
Use one of the better configurations:
![](https://raw.githubusercontent.com/wiki/OpenKinect/libfreenect2/benchmark.png)

**Comment by niteshtm** [comment]
Means I can't get better fps,since I have i5 , and using Opencl .

**Comment by xlz** [comment]
I don't know your hardware. You may be doing something wrong to be slower than ARM CPU.

**Comment by niteshtm** [comment]
Processor : Intel core i5-3470 CPU@3.20 Ghz
Ram- 4GB
OS : 8.1(64bit)
GPU : On board Intel Graphics card.
 
![config](https://cloud.githubusercontent.com/assets/12180725/14880620/86ba5aea-0d4d-11e6-802e-42c6afe5742f.png)

**Comment by xlz** [comment]
8 fps is the expected performance for the step. If you want better use Linux.

**Comment by niteshtm** [comment]
Thanks man for the confirmation . :)
