### ISSUE TITLE
the rgb image format is not right, but i have no idea about it.

### ISSUE THREAD

**Issue by wangwenfeng0** [OpenKinect/libfreenect2#641]
when i use the libfreenect2 and ofTheo's ofxKinectV2 to connect the kinect, the depth image is normal ,but the rgb image is confusion， so i couldn't use the image to show. 
the problem is in the web:https://forum.openframeworks.cc/t/about-oftheos-ofxkinectv2-the-rgb-image-is-not-right/23147 and the code is in :https://github.com/wangwenfeng0/openkinect1/
if someone know how to solve it,please tell me soon.thank you very much.

**Comment by floe** [comment]
Not a bug in libfreenect2, probably either caused by ofxKinectV2 (file a bug there) or in your own code.
