### ISSUE TITLE
Running two Kinect v2 at the same time in one application

### ISSUE THREAD

**Issue by neilyoyoyoyo** [OpenKinect/libfreenect2#643]
I am using two Kinect v2 in one application with OpenNI and here is the source code:

	OpenNI::initialize();
	openni::Array<DeviceInfo> mDeviceInfo;
	OpenNI::enumerateDevices(&mDeviceInfo);
	Device mDevice1;
	Device mDevice2;

	/*if (mDeviceInfo.getSize() != 2) {
		cout << "Wrong number of Kinects" << endl;
		return -1;
	}*/

	mDevice1.open(mDeviceInfo[0].getUri());
	mDevice2.open(mDeviceInfo[1].getUri());

but it seems that doesn't work well because of loss of packets:

[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 8 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @105:2 with serial 0196534
[Info] [Freenect2Impl] found valid Kinect v2 @161:2 with serial 0197047
[Info] [Freenect2Impl] found 2 devices
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 8 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @105:2 with serial 0196534
[Info] [Freenect2Impl] found valid Kinect v2 @161:2 with serial 0197047
[Info] [Freenect2Impl] found 2 devices
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 8 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @105:2 with serial 0196534
[Info] [Freenect2Impl] found valid Kinect v2 @161:2 with serial 0197047
[Info] [Freenect2Impl] found 2 devices
[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] opened
[Info] [Freenect2DeviceImpl] starting...
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Info] [Freenect2DeviceImpl] started
[Info] [DepthPacketStreamParser] 2 packets were lost
[Info] [DepthPacketStreamParser] 4 packets were lost
[Info] [DepthPacketStreamParser] 4 packets were lost
[Info] [TurboJpegRgbPacketProcessor] avg. time: 13.2382ms -> ~75.5389Hz
[Info] [DepthPacketStreamParser] 5 packets were lost
[Info] [OpenGLDepthPacketProcessor] avg. time: 23.6746ms -> ~42.2394Hz
[Info] [DepthPacketStreamParser] 4 packets were lost
[Info] [DepthPacketStreamParser] 3 packets were lost
[Info] [DepthPacketStreamParser] 82 packets were lost
[Info] [TurboJpegRgbPacketProcessor] avg. time: 13.4984ms -> ~74.0827Hz
[Info] [OpenGLDepthPacketProcessor] avg. time: 26.3897ms -> ~37.8935Hz
[Info] [DepthPacketStreamParser] 17 packets were lost
[Info] [DepthPacketStreamParser] 5 packets were lost
[Info] [TurboJpegRgbPacketProcessor] avg. time: 13.8107ms -> ~72.4074Hz
[Info] [DepthPacketStreamParser] 14 packets were lost
[Info] [OpenGLDepthPacketProcessor] avg. time: 28.8671ms -> ~34.6415Hz

So are there other good solutions to get Kinects serial for device opening?

**Comment by xlz** [comment]
Get a good computer.
