### ISSUE TITLE
NO device Connected!   "KINECT V1" with "Ubuntu 14.04.4"

### ISSUE THREAD

**Issue by MahmoudRizk** [OpenKinect/libfreenect2#647]
Overview Description:

I have been trying to use the kinect on ubuntu, but all my tries failed. I tried libfreenect and libfreenect2, getting the same error. I read the troubleshoot page but still can't figure out where is the problem.I am a newbie in Ubuntu. so please help :)  

The Kinect is connected to USB 3.
I disabled the USB autosusped. 

--> On trying  "./Protonect ", i got this:

Version: 0.2.0
Environment variables: LOGFILE=<protonect.log>
Usage: ./Protonect [-gpu=<id>] [gl | cl | cuda | cpu] [<device serial>]
            [-noviewer] [-norgb | -nodepth] [-help] [-version]
             [-frames <number of frames to process>]
To pause and unpause: pkill -USR1 Protonect
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 12 usb devices connected
[Info] [Freenect2Impl] found 0 devices
no device connected!

-->The output of "lsusb" :

Bus 004 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 005: ID 064e:812e Suyin Corp. 
Bus 003 Device 004: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
Bus 003 Device 003: ID 8087:07da Intel Corp. 
Bus 003 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 050: ID 045e:02b0 Microsoft Corp. Xbox NUI Motor
Bus 001 Device 049: ID 0409:005a NEC Corp. HighSpeed Hub
Bus 001 Device 045: ID 093a:2510 Pixart Imaging, Inc. Optical Mouse
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

-->The output of "ldd ./Protonect" :

linux-vdso.so.1 =>  (0x00007ffc597fa000)
	libfreenect2.so.0.2 => /home/mahmoudrizk/libfreenect2/build/lib/libfreenect2.so.0.2 (0x00007f6478848000)
	libglfw.so.3 => /usr/lib/x86_64-linux-gnu/libglfw.so.3 (0x00007f647860e000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f647837e000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f647807a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6477e64000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6477a9e000)
	libusb-1.0.so.0 => /lib/x86_64-linux-gnu/libusb-1.0.so.0 (0x00007f6477886000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6477668000)
	libturbojpeg.so.0 => /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0 (0x00007f647740d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6477107000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6476eff000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f6476bc9000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f64769bf000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f64767bc000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f64765ab000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f64763a5000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f647619b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6475f96000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f6475d6c000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f6475b3e000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f647592b000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f6475728000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f6475522000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f647531f000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f6475108000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f6474f03000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f6474cff000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f6474afc000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f64748f6000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f64746d6000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f64744d4000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f64742c7000)
	/lib64/ld-linux-x86-64.so.2 (0x000056148228a000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f64740b5000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f6473eab000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f6473ca6000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f6473aa0000)
	libcgmanager.so.0 => /lib/x86_64-linux-gnu/libcgmanager.so.0 (0x00007f6473884000)
	libnih.so.1 => /lib/x86_64-linux-gnu/libnih.so.1 (0x00007f647366c000)
	libnih-dbus.so.1 => /lib/x86_64-linux-gnu/libnih-dbus.so.1 (0x00007f6473462000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f647321c000)

-->The output of "lspci" :

00:00.0 Host bridge: Intel Corporation 3rd Gen Core processor DRAM Controller (rev 09)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port (rev 09)
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04)
00:16.0 Communication controller: Intel Corporation 7 Series/C210 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 7 Series/C210 Series Chipset Family High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 1 (rev c4)
00:1c.1 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 2 (rev c4)
00:1d.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation HM76 Express Chipset LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 7 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 7 Series/C210 Series Chipset Family SMBus Controller (rev 04)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Mars [Radeon HD 8730M] (rev ff)
07:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8101/2/6E PCI Express Fast/Gigabit Ethernet controller (rev 05)
08:00.0 Network controller: Intel Corporation Centrino Wireless-N 2230 (rev c4)

-->The output of "dmesg" after running  "./Protonect" as a Root. : 

[12285.345044] usb 1-3: USB disconnect, device number 49
[12285.345050] usb 1-3.2: USB disconnect, device number 50
[12289.673482] usb 1-1: new high-speed USB device number 52 using xhci_hcd
[12289.801901] usb 1-1: New USB device found, idVendor=0409, idProduct=005a
[12289.801907] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[12289.802417] hub 1-1:1.0: USB hub found
[12289.802443] hub 1-1:1.0: 3 ports detected
[12290.550577] usb 1-1.2: new full-speed USB device number 53 using xhci_hcd
[12290.663205] usb 1-1.2: New USB device found, idVendor=045e, idProduct=02b0
[12290.663222] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[12290.663224] usb 1-1.2: Product: Xbox NUI Motor
[12290.663225] usb 1-1.2: Manufacturer: Microsoft
[12292.280537] usb 1-1.1: new high-speed USB device number 54 using xhci_hcd
[12292.388674] usb 1-1.1: New USB device found, idVendor=045e, idProduct=02ad
[12292.388685] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=4
[12292.388690] usb 1-1.1: Product: Xbox NUI Audio
[12292.388694] usb 1-1.1: Manufacturer: Microsoft
[12292.388698] usb 1-1.1: SerialNumber: A44883D09739103A
[12292.835712] usb 1-1.1: USB disconnect, device number 54

**Comment by xlz** [comment]
Please do not use libfreenect2 for Kinect v1.

Close as invalid.
