### ISSUE TITLE
OpenCV Conversions

### ISSUE THREAD

**Issue by lakehanne** [OpenKinect/libfreenect2#648]
Hi y'all,

Trying to pass the frames to an opencv `Mat` container here. I proceed as follows:

```c++
    cv::Mat rgbMat(rgb->height, rgb->width, CV_8UC3, rgb->data);    
    cv::Mat depthMat(depth->height, depth->width, CV_8UC1, depth->data);
    cv::Mat irMat(ir->height, ir->width, CV_8UC1, ir->data);

    cv::imshow("rgbWin", rgbMat);
    cv::imshow("depthWin", depthMat);
    cv::imshow("irWin", irMat);
```

Am I right in the way I an mapping to opencv `Mat` format? 'Cause `imshow` is not showing anything.

Would appreciate your response. Thanks!

**Comment by xlz** [comment]
Your bit formats are incorrect. Check the format provided by libfreenect2 https://openkinect.github.io/libfreenect2/classlibfreenect2_1_1Frame.html#a1d1cfd8ffb84e947f82999c682b666a7
