### ISSUE TITLE
Black dot in depth image

### ISSUE THREAD

**Issue by AlexxxBeck** [OpenKinect/libfreenect2#650]
Hello guys,

I have a problem with the depth image of the kinect 2. This is just an example of a screenshot taken with the rqt_image_viewer of the depth image:
![fehler im tiefenbild](https://cloud.githubusercontent.com/assets/17646377/14887302/83dfaf7a-0d55-11e6-8ac9-e33e47c27e2f.png)

So the depth image always contains the dark "dot" but I don't know where it comes from. So also when I'm using Protonect this black dot is showing. The thing is that I have two different Kinect's and tested it on different computers and I always get that black dot in the depth image. On one of the Kinect's the dot is stronger than on the other  but I unfortunately have no idea how I can get rid of it because the rest of the depth image works fine.
I would be really glad if you could help me.

Thank you very much, 
Alex

**Comment by xlz** [comment]
Where in the image is the dark dot you refer to?

**Comment by AlexxxBeck** [comment]
Here:
![black dot](https://cloud.githubusercontent.com/assets/17646377/14891079/798b0352-0d65-11e6-824e-866218203e10.png)

**Comment by xlz** [comment]
It may be the surface is reflective and the area you marked reflects directly and saturates the measurements.

**Comment by AlexxxBeck** [comment]
Yes the surface is reflective and I just tried the depth image on that specific part. I'll try again tomorrow on non-reflective parts. Thank you very much for the fast response.

**Comment by AlexxxBeck** [comment]
So I just did some further tests and got the following results:
In this first image there is just a table without any objects and there is the clear black area in the picture:
![image3](https://cloud.githubusercontent.com/assets/17646377/14909577/7f13f2a4-0de5-11e6-846e-d178fc91f0f7.png)
So i thought I just bent the camera above that black dot and surprisingly it then disappeared althought it doesn't make a lot of sense to me why that should be.
![image4](https://cloud.githubusercontent.com/assets/17646377/14909628/30265a64-0de6-11e6-98ad-23d49367e998.png)


Then i put an object below the camera (the same kinda reflective object I showed last time) and the big black area is still there:
![image](https://cloud.githubusercontent.com/assets/17646377/14909595/c8271142-0de5-11e6-8325-e54c67e953e6.png)
so I thought perhaps it's really because the area of the surface might be reflective but when I move the object out of the black area the black are remains on exactly the same point like before:
![image2](https://cloud.githubusercontent.com/assets/17646377/14909613/05b6091e-0de6-11e6-9f85-5c2e5a9aed47.png)

Just for your notice these images were recorded with my other kinect so I doubt that the kinect is broken or something like that.

**Comment by AlexxxBeck** [comment]
The problem with that is that in my program I create a difference image between the background and the foreground. So the difference image of my color stream is totally black after I use my program to get the difference image. 
Here is the depth image before my program:
![depthimage](https://cloud.githubusercontent.com/assets/17646377/14910357/d0269cd0-0dec-11e6-8296-5d228a4d2a54.png)
and here it is after my program:
![difference_depthimage](https://cloud.githubusercontent.com/assets/17646377/14910360/d5f3f8b0-0dec-11e6-9d66-0e0497ab827c.png)

and as you can see in the are of the black are my difference image looks really weird and that's why I can't use it and try to solve it.

**Comment by AlexxxBeck** [comment]
For your information in the pictures taken the camera was just around 50 cm away from the object. By increasing the distance between the camera and the objects the problem got slightly better but the black area is still there as you can see in this picture:
![black dot](https://cloud.githubusercontent.com/assets/17646377/14915788/d96f400c-0e15-11e6-8d42-34226f7b290b.png)

**Comment by xlz** [comment]
What about the corresponding IR images?

**Comment by AlexxxBeck** [comment]
So I could solve this issue by changing the camera to a vertical position and increasing the distance even further. Now everything works fine although I still don't know what caused this black area. Thank you really much for the fast responses though.
