### ISSUE TITLE
Kinect can't immediately be restarted after a stop() on Mac OS X

### ISSUE THREAD

**Issue by fernLightning** [OpenKinect/libfreenect2#653]
I see similar fail as mentioned previously in https://github.com/OpenKinect/libfreenect2/issues/539

Only if I wait at least 4 seconds after the stop(), can I then call start() again.

**Comment by xlz** [comment]
https://github.com/OpenKinect/libfreenect2/commit/9c80ccd6a088a0e9e6cdafc9c837497b2434328d?

**Comment by fernLightning** [comment]
Sorry, seems the issue was a consequence of the kinect rebooting(?) in stop() due to another error caused by my own frame mis-management.
