### ISSUE TITLE
DeviceOpen using default: no devices found

### ISSUE THREAD

**Issue by ashokbugude** [OpenKinect/libfreenect2#654]
Hi I am trying to run 'UserViewer' in Linux using kinect xbox360, but I get below error(the green light is glowing)

Failed to open device
	DeviceOpen using default: no devices found

**Comment by xlz** [comment]
libfreenect2 is not for Kinect Xbox 360. It's for Kinect Xbox One.

**Comment by ashokbugude** [comment]
Hi Thanks for your response, Can I know is there any link/source code similar to libfreenect2 for Kinect Xbox 360 ?

**Comment by xlz** [comment]
https://github.com/OpenKinect/libfreenect
