### ISSUE TITLE
Kinect v2 kinectFusion on Ubuntu using Openni2 (no bug, need some advice)

### ISSUE THREAD

**Issue by luyuechao** [OpenKinect/libfreenect2#657]
I want to use kinect v2 to make a simple kinectfusion demo on Ubuntu 14.04.
Now I'm using slambench.(https://github.com/pamela-project/slambench),
which uses kinect v1 + openni1 to do SLAM.
I try to use it, and find it's not simple to alter the code into kinect v2 + openni2.
There are a lot of demos for windows, but I didn't find a linux one.
Can anyone give some advice? 
Or some implementation pipeline I should follow.
Thank you in advance:->

**Comment by xlz** [comment]
Protonect is our demo. Here is detained documentation about the demo: https://openkinect.github.io/libfreenect2/
