### ISSUE TITLE
Error of libusb [protocol::CommandTransaction] bulk transfer failed: LIBUSB_ERROR_TIMEOUT Operation timed out

### ISSUE THREAD

**Issue by minhkhue** [OpenKinect/libfreenect2#658]
I have recently installed libfreenect2 and tried ./Protonect.
I've got errors that seem like libusb does not receive kinect frame

[genious@localhost ~]$ ./Documents/SUP_INRIA_v2.2/libfreenect2-inria/build/bin/Protonect 
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 7 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @2:2 with serial 501830441942
[Info] [Freenect2Impl] found 1 devices
[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] opened
[Info] [Freenect2DeviceImpl] starting...
[Error] [protocol::CommandTransaction] bulk transfer failed: LIBUSB_ERROR_TIMEOUT Operation timed out
[Error] [protocol::CommandTransaction] sent number of bytes differs from expected number! expected: 20 got: 0
[Error] [protocol::CommandTransaction] bulk transfer failed: LIBUSB_ERROR_TIMEOUT Operation timed

Somebody have an idea ? 
Thanks so much

**Comment by xlz** [comment]
It looks like you are using an old version of libfreenect2.
