### ISSUE TITLE
No device found with with NiView2

### ISSUE THREAD

**Issue by twmht** [OpenKinect/libfreenect2#659]
Trying to `sudo apt-get install openni2-utils && sudo make install-openni2 && NiViewer2`

but it shows

```
openDevice failed:
	DeviceOpen using default: no devices found

Press any key to continue . . .
```

However, `./bin/Protonect` works well.

What's the possible cause?

thank you

**Comment by hanyazou** [comment]
please refer #632

**Comment by xlz** [comment]
True as above, it's probably because you installed OpenNI not from apt-get but from a binary and your OpenNI.ini does not point to the system OpenNI library path.

**Comment by birgersp** [comment]
Having the exact same issue, and I don't quite understand how to actually fix this... Tried modifying `/etc/openni2/OpenNI.ini` by adding `Repository=/usr/lib/OpenNI2/Drivers/`. Is that it? I still get the same error...

**Comment by doom-black** [comment]
Make symlink /usr/lib/OpenNI2/Drivers/libDummyDevice.so.0 for /usr/lib/OpenNI2/Drivers/libFreenectDriver.so.0.6.0.

**Comment by doom-black** [comment]
You should make symlink /usr/lib/OpenNI2/Drivers/libDummyDevice.so.0 for freenect driver (libFreenectDriver.so.0.6.0 or something like that). 
[https://github.com/OpenKinect/libfreenect2/issues/639](url)
