### ISSUE TITLE
catkin_make failure

### ISSUE THREAD

**Issue by ccrescent** [OpenKinect/libfreenect2#662]
Hi, I can install the libfreenect2 successfully, and ./bin/Protonect works.
but when I try to compile the iai_kinect2 ,($ catkin_make -DCMAKE_BUILD_TYPE="Release") it shows that:

/usr/include/CL/cl.hpp :1041:38 error : '_mm_mfence' was not declared in this scope 
            inline void fence() { _mm_mfence();

I have used the new version of libfreenect2
https://github.com/OpenKinect/libfreenect2  ;

what should i do to solve it .. @xlz

**Comment by xlz** [comment]
Then report a bug with iai_kinect2 because you tell us there is no bug with libfreenect2.
