### ISSUE TITLE
Cannot instantiate abstract class

### ISSUE THREAD

**Issue by Amoonet** [OpenKinect/libfreenect2#665]
Hello,
Im trying to make multiple kinect v2 skeleton tracking and as usually, I do everything on the manual in installation. Everything going well, I used a Cmake but when I tried to build it in Visual Studio 14 2015, it wrote an error: `Cannot instantiate abstract class`. Im using Win10 x64.

There is an error:
`...libfreenect2-master\src\openni2\DeviceDriver.cpp(134): error C2259: 'Freenect2Drive
r::ColorStream': cannot instantiate abstract class [C:\Users\Andy\Documents\GitHub\libfreenect2-master_64\build2\freene
ct2-openni2.vcxproj]`

 `...libfreenect2-master\src\openni2\DeviceDriver.cpp(138): error C2259: 'Freenect2Drive
r::DepthStream': cannot instantiate abstract class [C:\Users\Andy\Documents\GitHub\libfreenect2-master_64\build2\freene
ct2-openni2.vcxproj]
`

`...libfreenect2-master\src\openni2\DeviceDriver.cpp(142): error C2259: 'Freenect2Drive
r::IrStream': cannot instantiate abstract class [C:\Users\Andy\Documents\GitHub\libfreenect2-master_64\build2\freenect2
-openni2.vcxproj]`

I tried reinstall all dependencies (OpenNI, turbojpeg, etc...) and nothing helped. Could you please tell me if I doing something wrong or it is a problem of driver?

Sincerely,
Andy

**Comment by xlz** [comment]
Could not reproduce.
