### ISSUE TITLE
Protonect.exe: failed to create usb context: LIBUSB_ERROR_NOT_FOUND Entity not found

### ISSUE THREAD

**Issue by HollaDieWaldFee0815** [OpenKinect/libfreenect2#666]
Hello,
i followed the installation instructions and used Zadig to install the libusbk driver. And build the libfreenect2 library succesfully.

Using: Libfreenect2, Win7, Intel® Q85

When i try to run the Protonect.exe i get this error message:
![errorlib2](https://cloud.githubusercontent.com/assets/18439686/16003919/65fd2ae0-315f-11e6-87af-e79ae72a69fd.PNG)

In the device manager i can see the Xbox NUI Sensor(Composite Parent) listed under "libusbk USB devices". But i had to install some usb 3.0 intel drivers to see the device listed, before that i didn´t see anything.

The kinect v2 sensor works flawlessly on another computer. So i don´t think its an issue with the sensor.

Thanks in advance for your help.

**Comment by xlz** [comment]
Is USB 3.0 supported on this computer?

**Comment by HollaDieWaldFee0815** [comment]
It is supported on this computer. I got the same pc with a linux os, and the sensor is working fine there with libfreenect2.

**Comment by HollaDieWaldFee0815** [comment]
I found the solution. I used libusbx from josh blake (see : https://github.com/wjchen84/libfreenect2 )
and voila its working fine!
