### ISSUE TITLE
Can I replace default IR camera parameters with the ones I calculated?

### ISSUE THREAD

**Issue by anshulvj** [OpenKinect/libfreenect2#670]
I have calibrated my own Kinect v2 using OpenCV calibration, and the intrinsic parameters of the IR camera are slightly different, but close to what is given by libfreenect2 by default. For e.g., my parameters are:

//Cam params calibrated: 
fx: 362.30998043447721 
fy: 362.52170954186670 
cx: 260.13030010765118 
cy: 205.95775790704684

//Distortion params: 
k1: 0.097933635322428672 
k2:-0.28228584546727936 
p1: 0.00037521758983472805 
p2:0.00090946323232494151 
k3: 0.10598533154534898

I read on [#522](https://github.com/OpenKinect/libfreenect2/issues/522) and [#420](https://github.com/OpenKinect/libfreenect2/issues/420) that the camera registration params are only read by the device and cannot be changed. Is this also true about IR params.

Is there any way to replace the IR parameters in libfreenect2, atleast temporarily, to see which ones are better, mine or the ones already present? I could do that by replacing each and every depth.param each and every time it's called in registration, with my own, but that seems like a bad way of doing it. I would rather change some config file if that's easier.

**Comment by xlz** [comment]
You can.

https://openkinect.github.io/libfreenect2/classlibfreenect2_1_1Freenect2Device.html#a3343e3656ef4ea26650f7e2884aa129c

> setIrCameraParams
