### ISSUE TITLE
Cannot correctly set up the OpenCL stack

### ISSUE THREAD

**Issue by cforntu** [OpenKinect/libfreenect2#671]
Ubuntu 14.04
After I installed the opencl, I want to verify it using clinfo, but the output is 
 X server found. dri2 connection failed! 
/dev/dri/card0 not authenticated
X server found. dri2 connection failed! 
/dev/dri/card0 not authenticated
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
 and I reinstall the opencl but the error is still there. Could any give me any suggestion

**Comment by BrannonKing** [comment]
What are your graphics cards' models? What drivers are you using for them -- native or open source?

**Comment by cforntu** [comment]
My graphic card model is
   product: GM200 [GeForce GTX 980 Ti]
And this is my driver information:
  
![selection_001](https://cloud.githubusercontent.com/assets/20038828/16368239/83238d30-3c5e-11e6-9994-3077451c0b85.png)
  Could you please help me to solve the problem

**Comment by xlz** [comment]
Use CUDA.
