### ISSUE TITLE
OS X Memory leak

### ISSUE THREAD

**Issue by Natoito** [OpenKinect/libfreenect2#678]
Overview Description:
I try to use Freenect2 on Mac Mini. After about 1 minute RAM is full and exsample is frozen. In my code written in Xcode, I have the same problem.

Device information:
1. Darwin Mini-UserMac.home 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
2. libusb-1.0.20
3. glfw3-3.1.2
4. jpeg-turbo-1.5.0
5. Freenect2 0.20

Reproducibility:
Always

Additional Information:
Bug appears in any code.

**Comment by xlz** [comment]
We have tested and fixed most if not all memory leaks on MacOSX. This is probably a problem with your usage.
