### ISSUE TITLE
IR frame and Color Frame Alignment

### ISSUE THREAD

**Issue by scarabeo** [OpenKinect/libfreenect2#685]
Hello,
I am working on a segmentation in the IR frame with OpenCV.
My plan is filtering some objects in the IR frame and then get the color of these objects using the Color frame.
But, the IR frame and Color frame are not aligned. How could I do this alignment?
Do I have to use apply of registration.h like depth frame alignment or there is another way to align these frames?
thanks

**Comment by xlz** [comment]
Applying methods in registration.h does provide you "aligned" frames. It may be not optimally aligned though, which is only obtained by extrinsic calibration.

**Comment by harpreetsatwal** [comment]
Are you trying to pull only IR frames??

**Comment by xlz** [comment]
I believe the question has been answered.
