### ISSUE TITLE
[Question] Is there way of including Glew ?

### ISSUE THREAD

**Issue by moonsh** [OpenKinect/libfreenect2#702]
I am trying to include glew to use modern opengl functions but it collides with existing functions. 

 Is there a way of including Glew ?

Thank you for reading.

**Comment by xlz** [comment]
We had used GLEW but it didn't work for multithreading so we generated a header to import OpenGL functions one by one.

How did it conflict with your code? Likely solution would be to avoid the conflict.

**Comment by moonsh** [comment]
Thanks a lot.  Problems are solved by importing OpenGL functions one by one.
