### ISSUE TITLE
Ubuntu Multiple Kinects

### ISSUE THREAD

**Issue by Severn-Vergil** [OpenKinect/libfreenect2#704]
Thankhank you in advance for your patience!
Overview Description:
I've used two Kinect by ROS iai_kinect2 package on my notebook successfully, however for some reasons I reinstalled my system and reconfigured the environment, now I can not make them work.

**Current Version, Platform, and Hardware Bug Found:**
current environment: newest libfreenect2 and its dependencies.

## **uname -a**
Linux  4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

## **lsusb -t**
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/2p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/8p, 480M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/2p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/6p, 480M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/6p, 5000M
    |__ Port 1: Dev 16, If 0, Class=Hub, Driver=hub/1p, 5000M
        |__ Port 1: Dev 18, If 0, Class=Vendor Specific Class, Driver=, 5000M
        |__ Port 1: Dev 18, If 1, Class=Vendor Specific Class, Driver=, 5000M
        |__ Port 1: Dev 18, If 2, Class=Audio, Driver=snd-usb-audio, 5000M
        |__ Port 1: Dev 18, If 3, Class=Audio, Driver=snd-usb-audio, 5000M
    |__ Port 2: Dev 15, If 0, Class=Hub, Driver=hub/1p, 5000M
        |__ Port 1: Dev 19, If 0, Class=Vendor Specific Class, Driver=, 5000M
        |__ Port 1: Dev 19, If 1, Class=Vendor Specific Class, Driver=, 5000M
        |__ Port 1: Dev 19, If 2, Class=Audio, Driver=snd-usb-audio, 5000M
        |__ Port 1: Dev 19, If 3, Class=Audio, Driver=snd-usb-audio, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/14p, 480M
    |__ Port 1: Dev 13, If 0, Class=Hub, Driver=hub/1p, 480M
    |__ Port 2: Dev 12, If 0, Class=Hub, Driver=hub/1p, 480M
    |__ Port 4: Dev 4, If 0, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 4: Dev 4, If 1, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 7: Dev 5, If 0, Class=Video, Driver=uvcvideo, 480M
    |__ Port 7: Dev 5, If 1, Class=Video, Driver=uvcvideo, 480M
    |__ Port 14: Dev 6, If 0, Class=Vendor Specific Class, Driver=, 12M

## **lspci -nn**
00:00.0 Host bridge [0600]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor DRAM Controller [8086:0c04] (rev 06)
00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller [8086:0c01] (rev 06)
00:02.0 VGA compatible controller [0300]: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller [8086:0416] (rev 06)
00:03.0 Audio device [0403]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller [8086:0c0c] (rev 06)
00:14.0 USB controller [0c03]: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI [8086:8c31] (rev 05)
00:16.0 Communication controller [0780]: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 [8086:8c3a] (rev 04)
00:1a.0 USB controller [0c03]: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 [8086:8c2d] (rev 05)
00:1b.0 Audio device [0403]: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller [8086:8c20] (rev 05)
00:1c.0 PCI bridge [0604]: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #3 [8086:8c14] (rev d5)
00:1c.2 PCI bridge [0604]: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 [8086:8c10] (rev d5)
00:1c.3 PCI bridge [0604]: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #4 [8086:8c16] (rev d5)
00:1c.6 PCI bridge [0604]: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #7 [8086:8c1c] (rev d5)
00:1d.0 USB controller [0c03]: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 [8086:8c26] (rev 05)
00:1f.0 ISA bridge [0601]: Intel Corporation HM87 Express LPC Controller [8086:8c4b] (rev 05)
00:1f.2 SATA controller [0106]: Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] [8086:8c03] (rev 05)
00:1f.3 SMBus [0c05]: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller [8086:8c22] (rev 05)
01:00.0 3D controller [0302]: NVIDIA Corporation GK107M [GeForce GT 750M] [10de:0fe4] (rev a1)
07:00.0 Network controller [0280]: Ralink corp. RT3290 Wireless 802.11n 1T/1R PCIe [1814:3290]
07:00.1 Bluetooth [0d11]: Ralink corp. RT3290 Bluetooth [1814:3298]
09:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5227 PCI Express Card Reader [10ec:5227] (rev 01)
0f:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 0c)

## **sudo dmidecode | grep -1 PCI**
Characteristics:
PCI is supported
BIOS is upgradeable

	Designation: J5C1
	Type: x16 PCI Express x16
	Current Usage: Available

	Designation: J6C1
	Type: x1 PCI Express x1
	Current Usage: Available

	Designation: J6C2
	Type: x1 PCI Express x1
	Current Usage: Available

	Designation: J6D2
	Type: x1 PCI Express x1
	Current Usage: Available

	Designation: J7C1
	Type: x1 PCI Express x1
	Current Usage: Available

	Designation: J7D2
	Type: x1 PCI Express x1
	Current Usage: Available

	Designation: J8C1
	Type: x1 PCI Express x1
	Current Usage: Available

	Designation: J8C2
	Type: x16 PCI Express x16
	Current Usage: Available

	Referenced Offset: 0x05
	String: PCIExpressx16
	Value: 0xaa

## **Run LIBUSB_DEBUG=3 ./Protonect using another Kinect:**
Version: 0.2.0
Environment variables: LOGFILE=<protonect.log>
Usage: ./Protonect [-gpu=<id>] [gl | cl | cuda | cpu] [<device serial>]
        [-noviewer] [-norgb | -nodepth] [-help] [-version]
        [-frames <number of frames to process>]
To pause and unpause: pkill -USR1 Protonect
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 15 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @2:17 with serial 501056442742
[Info] [Freenect2Impl] found valid Kinect v2 @2:18 with serial 502041243142
[Info] [Freenect2Impl] found 2 devices
[Warning] [ShaderProgram] Working around buggy boolean instructions in your Mesa driver. Mesa DRI 10.3+ is recommended.
[Warning] [ShaderProgram] Working around buggy boolean instructions in your Mesa driver. Mesa DRI 10.3+ is recommended.
[Warning] [ShaderProgram] Working around buggy boolean instructions in your Mesa driver. Mesa DRI 10.3+ is recommended.
[Warning] [ShaderProgram] Working around buggy boolean instructions in your Mesa driver. Mesa DRI 10.3+ is recommended.
[Info] [Freenect2Impl] re-enumerating devices after reset
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 15 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @2:19 with serial 501056442742
[Info] [Freenect2Impl] found valid Kinect v2 @2:18 with serial 502041243142
[Info] [Freenect2Impl] found 2 devices
[Info] [Freenect2DeviceImpl] opening...
libusb: error [op_get_configuration] device unconfigured
libusb: error [op_set_configuration] failed, error -1 errno 28
[Error] [protocol::UsbControl] failed to set configuration! LIBUSB_ERROR_OTHER Other error. Try debugging with environment variable: export LIBUSB_DEBUG=3 .
[Info] [Freenect2DeviceImpl] closing...
libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=3
[Error] [protocol::CommandTransaction] bulk transfer failed: LIBUSB_ERROR_IO Input/Output Error
libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=3
[Error] [protocol::CommandTransaction] bulk transfer failed: LIBUSB_ERROR_IO Input/Output Error
[Info] [Freenect2DeviceImpl] deallocating usb transfer pools...
[Info] [Freenect2DeviceImpl] closing usb device...
[Info] [Freenect2DeviceImpl] closed
[Error] [Freenect2Impl] failed to open Kinect v2: @2:19
failure opening device!

**## dmesg:**
[dmesg.txt](https://github.com/OpenKinect/libfreenect2/files/406315/dmesg.txt)

## **Past Version:**
linux kernel 3.16, libusb 1.0.20, installed the libfreenect2 in 2015.12.29;
8GB memory, i7-4702MQ

## @**Additional Information:**
Hardware:
HP-15-j105tx
Microprocessor: 2.2 GHz Intel Core i7-4702MQ
Chipset: Intel HM87 Express
Microprocessor Cache: 6 MB cache, 4 cores
Memory: 8 GB 1600 MHz DDR3L
Memory Slots: 2 user-accessible
Video Graphics: NVIDIA GeForce GT 750M (4 GB DDR3 dedicated)
External Ports
1 multi-format digital media card reader for SD cards
4 SuperSpeed USB 3.0 (1 for USB Boost)
1 HDMI
1 RJ-45

**Increasing USBFS buffer size**
echo 64 > /sys/module/usbcore/parameters/usbfs_memory_mb does not work.

**try methods from [#615](https://github.com/OpenKinect/libfreenect2/issues/615)
dmesg as follows**
[   22.925874] usb 2-3.1: Not enough bandwidth for altsetting 1
[   22.926333] usb 2-3.1: 3:1: usb_set_interface failed (-28)
[   40.557331] audit: type=1400 audit(1470656550.817:78): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/cups/backend/cups-pdf" pid=2722 comm="apparmor_parser"
[   40.557337] audit: type=1400 audit(1470656550.817:79): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/sbin/cupsd" pid=2722 comm="apparmor_parser"
[   40.557586] audit: type=1400 audit(1470656550.817:80): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/sbin/cupsd" pid=2722 comm="apparmor_parser"
[   41.201464] audit: type=1400 audit(1470656551.465:81): apparmor="DENIED" operation="open" profile="/usr/lib/telepathy/mission-control-5" name="/home/rabot/.config/dconf/user" pid=2797 comm="mission-control" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   74.130841] usb 2-3.1: reset SuperSpeed USB device number 5 using xhci_hcd
[   74.524085] xhci_hcd 0000:00:14.0: WARN Event TRB for slot 7 ep 2 with no TDs queued?
[  152.008969] usb 2-3.1: reset SuperSpeed USB device number 5 using xhci_hcd
[  152.046484] xhci_hcd 0000:00:14.0: WARN Event TRB for slot 7 ep 2 with no TDs queued?
[  152.097631] xhci_hcd 0000:00:14.0: WARN Event TRB for slot 7 ep 2 with no TDs queued?
[  156.809703] usb 2-1.1: reset SuperSpeed USB device number 4 using xhci_hcd
[  156.826655] usb 2-1.1: Not enough bandwidth for new device state.
[  156.826689] usb 2-1.1: Busted HC?  Not enough HCD resources for old configuration.
[  156.830579] usb 2-1.1: USB disconnect, device number 4
[  156.830839] usb 2-1.1: Not enough bandwidth for new device state.
[  156.830855] usb 2-1.1: Not enough bandwidth for altsetting 1
[  156.832991] systemd-udevd[3650]: Failed to apply ACL on /dev/snd/pcmC1D0c: No such file or directory
[  156.833000] systemd-udevd[3650]: Failed to apply ACL on /dev/snd/pcmC1D0c: No such file or directory
[  157.486245] usb 2-1.1: new SuperSpeed USB device number 6 using xhci_hcd
[  157.502677] usb 2-1.1: New USB device found, idVendor=045e, idProduct=02d8
[  157.502680] usb 2-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=4
[  157.502681] usb 2-1.1: Product: Xbox NUI Sensor
[  157.502683] usb 2-1.1: Manufacturer: Microsoft
[  157.502681] usb 2-1.1: Product: Xbox NUI Sensor
[  157.502683] usb 2-1.1: Manufacturer: Microsoft
[  157.502684] usb 2-1.1: SerialNumber: 501056442742
[  157.503354] usb 2-1.1: Not enough bandwidth for new device state.
[  157.503373] usb 2-1.1: can't set config #1, error -28
[  157.837925] usb 2-3.1: usbfs: process 3644 (Protonect) did not claim interface 0 before use
[  157.837951] usb 2-3.1: usbfs: process 3644 (Protonect) did not claim interface 0 before use
[  269.347733] systemd-hostnamed[3676]: Warning: nss-myhostname is not installed. Changing the local hostname might make it unresolveable. Please install nss-myhostname!
[  668.919668] systemd-hostnamed[3957]: Warning: nss-myhostname is not installed. Changing the local hostname might make it unresolveable. Please install nss-myhostname!
[ 1392.012023] audit: type=1400 audit(1470657900.872:82): apparmor="DENIED" operation="file_inherit" profile="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=5170 comm="nm-dhcp-client." lport=43217 family="inet" sock_type="dgram" protocol=17
[ 1392.012033] audit: type=1400 audit(1470657900.872:83): apparmor="DENIED" operation="file_inherit" profile="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=5170 comm="nm-dhcp-client." lport=55457 family="inet6" sock_type="dgram" protocol=17
[ 1621.327941] usb 2-3.1: reset SuperSpeed USB device number 5 using xhci_hcd
[ 1621.417097] xhci_hcd 0000:00:14.0: WARN Event TRB for slot 7 ep 2 with no TDs queued?
[ 1626.889359] usb 2-1.1: reset SuperSpeed USB device number 6 using xhci_hcd
[ 1626.906427] usb 2-1.1: Not enough bandwidth for new device state.

I just find that my notebook has 2 PCIx16 slot in my notebook, is it workable?
It seems weird that the hardware could support two Kinects before and dmesg shows not enough bandwidth now. 
Thank you for your advice again!

**Comment by xlz** [comment]
Not enough bandwidth. A hardware problem.

I don't have a solution for this.

**Comment by Severn-Vergil** [comment]
@xlz Thank's for your attention! I wonder if it is the hardware problem, as I successfully used two Kinects on my platform before and there are two PCIE-x16 according to the dmidecode result, maybe the PCIs are not allocated well and two Kinects are using the same PCI, and I'm trying to fix this. Are there some parts of code related to the PCI in libfreenect2? Thank you.
