### ISSUE TITLE
Jetson TK1 color channels are mixed on tegra libjpeg

### ISSUE THREAD

**Issue by kassinen** [OpenKinect/libfreenect2#705]
Hi

I am using Jetson TK1 with L4T21.4
I am currently experiencing some difficulties using libfreenect.
Protonect compiles and works, except, the colors seems to be BGR, not RGB.
When disabling tegra jpeg and using turbojpeg, this seems to working correctly and showing RGB.

In protonects Viewer.h, there is a line
`typedef ImageFormat<4, GL_RGBA, GL_BGRA, GL_UNSIGNED_BYTE> F8C4;` 
And changing GL_BGRA to GL_RGBA seems to resolve the problem for tegra jpeg in protonect.

I am also using libfreenect in Qt application but there it seems that defining anything does not have any effect. (Maybe jpeg's are compressed to have information that they are RGB when they are not and decoding in Qt goes haywire because of that)

At least turbo_jpeg_rbg_packet_processor.cpp seems to pack the frames as BGRX format.

Is there anything I can do inside libfreenect or do I need to stab the tegras libjpeg?

Thanks already

**Comment by xlz** [comment]
Tegra JPEG the hardware decoder only provides rgba format. Frame->format indicates this. If you need bgra you have to convert it yourself.

Protonect.cpp does not care yet to fix this.
