### ISSUE TITLE
Skeleton tracking with libfreenect2 and kinect v2

### ISSUE THREAD

**Issue by Lofert** [OpenKinect/libfreenect2#706]
Hello everyone, has anyone can get the skeleton data by using libfreenect2 and kinect v2?
Anther question, is the skeleton frame directly obtained from depth sensor in kinect? If so, how can we obtain skeleton data from kinect, just like depth image obtained by libfreenect2?
Thank you!

**Comment by robozo** [comment]
Short answer, no.  libfreenect2 is high-quality software, which lets you get depth and RGB data
from the kinect v2 hardware, without using the microsoft driver.

Determining skeleton tracking from depth data is a research problem.  The microsoft driver
does a semi-reasonable job of extracting a skeleton, if you directly face the camera.
But it, for example, can't tell your front from your back.

It's a hard problem!  Maybe someone has collected links to the current state of the art...

**Comment by chengzijiazu** [comment]
Here is the solution of skeleton tracking on linux. https://groups.google.com/forum/#!topic/openkinect/cXoEnHDUaZc

**Comment by Lofert** [comment]
@robozo Hi，robozo. I wonder if the skeleton data can be got from the kinect v2 hardware just like depth and RGB data.

**Comment by Lofert** [comment]
@chengzijiazu Thanks, but i don't use ros.

**Comment by robozo** [comment]
Hi @Lofert , no, the kinect just sends depth and RGB data (and audio, i think).
That's amazing enough!  Everything else is software.

Thanks @chengzijiazu, for telling me about ros.  I looked on youtube, looks like the ros
skeleton tracking is no better than the microsoft.  Plenty of room for improvement...

**Comment by chengzijiazu** [comment]
lastest paper <Real-time Collection and Analysis of 3-Kinect v2 Skeleton Data in a Single Application>
this paper introduce how to track skeleton with openni2+nite2.

**Comment by chengzijiazu** [comment]
Real-time Collection and Analysis of 3-Kinect v2 Skeleton Data in a Single Application

**Comment by orgicus** [comment]
I had a very similar question which you can see in this [issue](https://github.com/OpenKinect/libfreenect2/issues/668)

It boiled down to:

1. compiling libfreenect with openni2 support (as per readme)
2. grabbing NiTE2 (I got if from [this repo](https://bitbucket.org/kaorun55/openni-2.2/src/2f54272802bfd24ca32f03327fbabaf85ac4a5c4/NITE%202.2%20%CE%B1/?at=master))
3. placing `libfreenect2/build/lib/libfreenect2-openni2.0.dylib` in `NiTE-MacOSX-x64-2.2/Samples/Bin/OpenNI2/Drivers`

After that I could run samples like `SimpleUserTracker`. Note that I had the issue on OSX, but I imagine this can be adapted to Windows/Linux

HTH

**Comment by chengzijiazu** [comment]
thank you! Now I could build the solution.It work well.I just copy the Redist files of Openni2 and NiTE2 to the solution folder.

**Comment by xlz** [comment]
Looks like the discussion is over.

**Comment by fma-1724** [comment]
Hi,

I'm trying to use kinect v2 with openni and nite with ubuntu
Have any of you know how to do it? or do you know of someone that does?

Thanks

**Comment by bearpaw** [comment]
> I had a very similar question which you can see in this [issue](https://github.com/OpenKinect/libfreenect2/issues/668)
> 
> It boiled down to:
> 
> 1. compiling libfreenect with openni2 support (as per readme)
> 2. grabbing NiTE2 (I got if from [this repo](https://bitbucket.org/kaorun55/openni-2.2/src/2f54272802bfd24ca32f03327fbabaf85ac4a5c4/NITE%202.2%20%CE%B1/?at=master))
> 3. placing `libfreenect2/build/lib/libfreenect2-openni2.0.dylib` in `NiTE-MacOSX-x64-2.2/Samples/Bin/OpenNI2/Drivers`
> 
> After that I could run samples like `SimpleUserTracker`. Note that I had the issue on OSX, but I imagine this can be adapted to Windows/Linux
> 
> HTH

@fma-1724 

Just put `libfreenect2-openni2.so.0` into the `Samples/Bin/OpenNI2/Drivers` and create a symbolic link `libfreenect2-openni2.so` to it.

**Comment by boulbasakos** [comment]
I get black screen when i run ./UserViewer plus when i run ./Protonect with librefreenect2 core gets dumbed but with ./Protonect cpu works fine,Any ideas to help me with this issue?

Thanks
