### ISSUE TITLE
Get camera space position with color coordinate

### ISSUE THREAD

**Issue by kalluwa** [OpenKinect/libfreenect2#708]
I am doing a registration using a marker image:
first detect the marker with RGB buffer, then map the marker coorinates to camera space.
I got a correct result with Kinect SDK2.0 by using == MapColorFrameToCameraSpace ==.
just like this:
![20160817101503](https://cloud.githubusercontent.com/assets/9412335/17722322/e7523f5e-6463-11e6-8b44-31898af93ed8.jpg)

and now i need to implement the same effect with libfreenect2, but being stucked in mapping color coordinate to camera position.

[issue509](https://github.com/OpenKinect/libfreenect2/issues/509) can get the depth with the same coordinate in RGB buffer, but i cannot convert it into camera space.

i don't know to handle this problem, can you give me any suggestions?

**Comment by kalluwa** [comment]
i create a map from color to depth and add a 5x3 filter , and i get the correct result:
![1](https://cloud.githubusercontent.com/assets/9412335/17728483/059e661c-6492-11e6-823b-5ab0c80e1860.jpg)

**Comment by sairamkolla** [comment]
Hi @kalluwa  Can you explain what did you mean by 5x3 filter?

**Comment by floe** [comment]
A 5x3 upsampling filter is exactly what happens if you use the `bigdepth` parameter for `Registration::apply`.
