### ISSUE TITLE
Performance on Jetson TX1

### ISSUE THREAD

**Issue by xionglingfeng** [OpenKinect/libfreenect2#710]
What is the expected performance on Jetson TX1? Is there anyone who tried to run `libfreenect2` on Jetson TX1 can share the performance data, e.g. FPS?
My configuration is `CUDA` processor with `TegraJPEG`.

**Comment by lesterlo** [comment]
The debug output of the freenect2 said the TegraJPEG RGB packet processor can run in around  180Hz and the CUDA Depth packet processor can run in around 55 - 61Hz.

**Comment by Abbyls** [comment]
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Info] [OpenGLDepthPacketProcessor] avg. time: 13.3667ms -> ~74.8129Hz
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Debug] [RgbPacketStreamParser] skipping rgb packet!
[Info] [TurboJpegRgbPacketProcessor] avg. time: 41.353ms -> ~24.1821Hz
and my 4 CPU load are near 90%!
![screenshot from 2016-09-02 13 37 35](https://cloud.githubusercontent.com/assets/21240657/18193679/81d8b3cc-7112-11e6-81a9-c08026c09337.png)

**Comment by natejgardner** [comment]
I'm experiencing the exact same issue. I made my own issue for it [here](https://github.com/OpenKinect/libfreenect2/issues/737). Feel free to merge these issues.
