### ISSUE TITLE
[Question] running on CentOS 6.x+

### ISSUE THREAD

**Issue by smokhov** [OpenKinect/libfreenect2#711]
Has anyone tried running libfreenect2 with its examples on any EL6 (or EL7) distribution, such as CentOS, Scientific Linux, RHEL, successfully? And what was the experience like?

**Comment by xlz** [comment]
Most of the experiment would depend on corresponding dependency libraries. Kernel support for USB 3.0 controllers, libusb, GLFW3, graphics driver, OpenCL stack, CUDA. Check the versions and you should know enough.
