### ISSUE TITLE
[Question] Is there a way of accelerating speed of receiving depth data ?

### ISSUE THREAD

**Issue by moonsh** [OpenKinect/libfreenect2#717]
In my project, I need fast acquisition of depth data. 

 Therefore, I got a question . Is there a way of accelerating speed of receiving depth data ?

 I am planning to study OpenMP or TBB and apply it to libfreenect2.

 Thanks for reading.

**Comment by xlz** [comment]
I don't think multi-threading would help IO here.

**Comment by moonsh** [comment]
then there is no way speed up ?
