### ISSUE TITLE
error while loading shared library libfreenect2.so.0.2 

### ISSUE THREAD

**Issue by ashokbugude** [OpenKinect/libfreenect2#728]
I am using ubuntu 16.04. I am trying to run Protonect.cpp from 'Code Blocks'.I am able to build without any errors, but when I run , I get below errors

Error while loading shared library libfreenect2.so.0.2 
![error](https://cloud.githubusercontent.com/assets/10016848/18864126/8195e1ce-84b2-11e6-800d-87115cdbfd7f.png)

I have added the libfreenect2.so.0.2  file in linkers section of codeblocks as shown below, but still get same error
![settings](https://cloud.githubusercontent.com/assets/10016848/18864333/7420a730-84b3-11e6-8d97-76d5aba21679.png)

Please help resolve the issue

**Comment by floe** [comment]
What output do you get when you run `ldd /home/zayyon/Ashok/codeBlocksWS/test/bin/Debug/test` in the console?

**Comment by ashokbugude** [comment]
Thanks for your response, Below is the output of ldd command
![error2](https://cloud.githubusercontent.com/assets/10016848/18864684/142b5616-84b5-11e6-8962-578005c1998c.png)

I can see 'libfreenect2.so.0.2' is not found although I have added it in 'Linker settings' of codeblocks as shown in previous screenshot. Please help setup in codeBlocks

**Comment by floe** [comment]
Sorry, no idea about codeBlocks. But this means that `/usr/local/lib` is not part of your library search path, for whatever reason. As a temporary fix, you can do `export LD_LIBRARY_PATH=/usr/local/lib` in the console and run the binary from there.

**Comment by ashokbugude** [comment]
Thanks, working fine from terminal but not from codeblocks
