### ISSUE TITLE
Registration does only write into the data field in registered and undistorted frames

### ISSUE THREAD

**Issue by RealRecon** [OpenKinect/libfreenect2#731]
I tried to capture live input similar to the Protonect example. If I use the internal registration through

`registration->apply(rgb, depth, &undistorted, &registered);`

the remaining frame information (format, gain, exposure, etc.) is NOT copied to the Frames undistorted and registered.
This causes unexpected behaviour in my program if I try to process the data using this information.

**Comment by xlz** [comment]
The caller of `Registration::apply()` is responsible to allocate and populate the Frame objects for writing.
