### ISSUE TITLE
Raspberry Pi 3 LibUSB not found?

### ISSUE THREAD

**Issue by bleepbloopsify** [OpenKinect/libfreenect2#735]
Overview Description:

sudo cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/freenect2
-- using tinythread as threading library
-- checking for module 'libusb-1.0>=1.0.20'
--   package 'libusb-1.0>=1.0.20' not found
CMake Error at /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:341 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
  cmake_modules/FindLibUSB.cmake:21 (PKG_CHECK_MODULES)
  CMakeLists.txt:93 (FIND_PACKAGE)

-- Could NOT find TegraJPEG (missing:  TegraJPEG_LIBRARIES TegraJPEG_INCLUDE_DIRS TegraJPEG_L4T_OK TegraJPEG_DRIVER_OK TegraJPEG_WORKS) 
-- checking for module 'glfw3'
--   package 'glfw3' not found
-- Could NOT find OpenCL (missing:  OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Linking with these libraries: 
 LibUSB_LIBRARY-NOTFOUND
 pthread
 va-drm
 va
 /usr/lib/arm-linux-gnueabihf/libjpeg.so
 /usr/lib/arm-linux-gnueabihf/libturbojpeg.so.1
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configurating examples
-- Using in-tree freenect2 target
-- checking for module 'glfw3'
--   package 'glfw3' not found
-- checking for module 'libopenni2'
--   package 'libopenni2' not found
-- Could NOT find OpenNI2 (missing:  OpenNI2_LIBRARY_DIR OpenNI2_INCLUDE_DIRS) 
-- Feature list:
--   CUDA    no
--   CXX11    disabled
--   Examples    yes
--   OpenCL    no
--   OpenGL    no
--   OpenNI2    no
--   TegraJPEG    no
--   Threading    tinythread
--   TurboJPEG    yes
--   VAAPI    yes
--   VideoToolbox    no (Apple only)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LibUSB_LIBRARY
    linked by target "freenect2" in directory /home/leon/Downloads/Installers/libfreenect2

-- Configuring incomplete, errors occurred!
See also "/home/leon/Downloads/Installers/libfreenect2/build/CMakeFiles/CMakeOutput.log".
See also "/home/leon/Downloads/Installers/libfreenect2/build/CMakeFiles/CMakeError.log".

this is what happens when i run cmake.
I installed every library.
I am using Raspberry Pi 3 with Kinect 2
Libusb is not detected?

**Comment by boulabiar** [comment]
You need USB 3,
All Raspberry Pi are USB 2.
