### ISSUE TITLE
Problems building on Macbook

### ISSUE THREAD

**Issue by foong** [OpenKinect/libfreenect2#740]
Having problems building on my macbook
Was following the instructions and got stuck when building.

OSX 10.11.6 Elcapitan
NVIDIA GeForce GT 330M 512 MB
Have all the dependencies including Cuda 

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep_18_22:16:08_CDT_2016
Cuda compilation tools, release 8.0, V8.0.46

Terminal command:
Wees-MacBook-Pro:build Foong$ make

Terminal Response:
Scanning dependencies of target generate_resources_tool
[ 2%] Building CXX object CMakeFiles/generate_resources_tool.dir/tools/generate_resources.cpp.o
[ 5%] Linking CXX executable bin/generate_resources_tool
[ 5%] Built target generate_resources_tool
[ 7%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/src/cuda_compile_generated_cuda_depth_packet_processor.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal : The version ('80000') of the host compiler ('Apple clang') is not supported
CMake Error at cuda_compile_generated_cuda_depth_packet_processor.cu.o.RelWithDebInfo.cmake:207 (message):
Error generating
/Users/Foong/libfreenect2/build/CMakeFiles/cuda_compile.dir/src/./cuda_compile_generated_cuda_depth_packet_processor.cu.o

make[2]: *** [CMakeFiles/cuda_compile.dir/src/cuda_compile_generated_cuda_depth_packet_processor.cu.o] Error 1
make[1]: *** [CMakeFiles/freenect2.dir/all] Error 2
make: *** [all] Error 2

**Comment by xlz** [comment]
See solution here:
https://devtalk.nvidia.com/default/topic/970835/cuda-8-on-sierra/
