### ISSUE TITLE
[Question] Python Wrapper ?

### ISSUE THREAD

**Issue by pranali3215** [OpenKinect/libfreenect2#751]
Hi. 
I just started working with Kinect2.
I was previously using Kinect1 and was thus using libfreenect with it.
However it had python wrappers with it.
I do not seem to find any Python wrappers with libfreenect2.
Is there any way I can use Python with Kinect2 ?
I am using a Ubuntu 14.04 machine.

Any help is appreciated.

**Comment by xlz** [comment]
https://github.com/OpenKinect/libfreenect2/issues/280
