### ISSUE TITLE
Is there any advantage by using Nvidia Quadro for libfreenect2?

### ISSUE THREAD

**Issue by hanshammel1337** [OpenKinect/libfreenect2#753]
hello,

will there be any performance differences when using a nvidia quadro card compared to a similar nvidia geforce card? i kown the differences for CAD applications, but does libfreenect2 with cuda get any boost by using a quadro card?

greetings

**Comment by xlz** [comment]
Any one, even low end Nvidia card would be more than enough for libfreenect2.

There are two performance metrics of Nvidia cards here https://github.com/OpenKinect/libfreenect2/wiki/Performance
