### ISSUE TITLE
PCI x1 slot vs x8/x16

### ISSUE THREAD

**Issue by sdenenberg** [OpenKinect/libfreenect2#754]
I've read through these forums for posts relating to using multiple kinects.  In more than one instance (for example here: https://github.com/OpenKinect/libfreenect2/issues/715), it is stated that each Kinect needs its own USB 3.0 controller connected through a PCI Express x8/x16 slot as opposed to a PCI Express x1 slot.  

Is there a reason why the x1 slots shouldn't work?  For the past couple of months I've been working with a 3 Kinect setup and am now trying to move to a 5 Kinect setup.  I ran out of PCI slots so I am looking into alternatives.  However, in doing my searching, I've found that one of the PCI slots that I had been using was an x1 slot.  It seems to work just fine, although occasionally when used with a longer USB cable I have some packets that are dropped (this is a potentially unrelated issue).

So, my question is whether or not I've gotten incredibly lucky and if so, why?  The computer I'm looking to purchase would have the necessary PCI slots, however 2 of them would be x1 slots.

Thanks,

Scott

**Comment by xlz** [comment]
#715 didn't say PCIex1 doesn't work? It's the case when one PCIe card has multiple USB ports. If you have multiple PCIex1 card each with one USB port it should be OK too.
