### ISSUE TITLE
registration frame data lose

### ISSUE THREAD

**Issue by Abbyls** [OpenKinect/libfreenect2#755]
Overview Description:
environment: ubuntu 14.04 x86_64
i think my registration frame get from Protonect.cpp have lose many useful data(i think it's the depth frame problem) campared with the registration frame get from the kinect1(driver:libfreenect), and it affect my work, i don't kown if there any method or parameters to set the kinect2 to improve the results.

1. ./bin/Protonect cuda with my kinect2 the frame as follows:
![cuda-master](https://cloud.githubusercontent.com/assets/21240657/20431718/85cdf4c8-add6-11e6-88f4-1ac773020947.png)

2. the point cloud data get from the kinect1 as:
![screenshot from 2016-11-18 21 06 07](https://cloud.githubusercontent.com/assets/21240657/20431752/ad9a30b6-add6-11e6-800a-62fd01bff5f5.png)

You can see, the kinect2 registration frame can't get the white line in the rgb frame, the data is losed in the depth frame, so, i can't get the information, but in the point cloud from kinect1, we can see the white line and have a more broad sight.

I wonder what's probelm? If i need change some parameters?

**Comment by Abbyls** [comment]
add a more clear image from kinect2 Protonect:
![11](https://cloud.githubusercontent.com/assets/21240657/20432096/86900cbe-add8-11e6-9ddd-2b8646b39da5.png)

**Comment by floe** [comment]
Well, the Kinect1 and Kinect2 are very different cameras, you can't say that one is generally better than the other. Maybe the Kinect1 is just better suited for your specific application.

**Comment by Abbyls** [comment]
ok, after that, it's because i didn't remove the protect membrane on the new kinect2!
but the depth image also not well as you can see (1) and  i test the depth_image from the iai_kinect2/kinect2_bridge, as (2),
(1)
![1](https://cloud.githubusercontent.com/assets/21240657/20547453/17618610-b157-11e6-9450-55adfb7f2e6f.png)
(2)
![2](https://cloud.githubusercontent.com/assets/21240657/20547460/1f25ca96-b157-11e6-8c2c-32154e675d6a.png)

You can see, it's different. and i find the kinect2_bridge get headerfiles from freenect package, but protonect get header files from libfreenect2/include! 

Then i copied the header files from freenect to the libfreenect2/include errors happened. 
How can i get depth frame as the kinect2_bridge?

**Comment by Abbyls** [comment]
I solved it. As the kinect2_bridge have a config on the device.  You can closed the problem.
