### ISSUE TITLE
cmake error 

### ISSUE THREAD

**Issue by fcastilloc** [OpenKinect/libfreenect2#756]
Hi,

I'm following the steps to install libfreenect2 on Linux, but when I make: 
 cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/freenect2
I got:
-- using tinythread as threading library
-- checking for modules 'libva;libva-drm'
--   found libva, version 0.36.0
--   found libva-drm, version 0.36.0
-- Could NOT find TegraJPEG (missing:  TegraJPEG_LIBRARIES TegraJPEG_INCLUDE_DIRS TegraJPEG_L4T_OK TegraJPEG_DRIVER_OK TegraJPEG_WORKS) 
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find TurboJPEG (missing: TurboJPEG_INCLUDE_DIRS TURBOJPEG_WORKS)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/FindTurboJPEG.cmake:66 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:240 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/charles/Downloads/libfreenect2/build/CMakeFiles/CMakeOutput.log".

**Comment by xlz** [comment]
Your turbojpeg isn't set up correctly.

**Comment by fcastilloc** [comment]
How can I set it up correctly?

**Comment by xlz** [comment]
`turbojpeg.h` has to be located in system include paths.

**Comment by fcastilloc** [comment]
Finally it works,
thanks.

**Comment by sram022** [comment]
I have the same problem but not sure how to resolve it.How to setup turbojpeg correctly in Ubuntu.
