### ISSUE TITLE
Average time 0ms

### ISSUE THREAD

**Issue by pranali3215** [OpenKinect/libfreenect2#757]
Hi,
So I have been trying to make a code working with kinect2. 
It was working fine till yesterday.
But suddenly it started showing the following logs:

[Info] [DepthPacketStreamParser] 33 packets were lost22/11/16, 11:52:28 IST
[Info] [DepthPacketStreamParser] 35 packets were lost22/11/16, 11:52:29 IST
[Info] [DepthPacketStreamParser] 35 packets were lost22/11/16, 11:52:31 IST
[Info] [TurboJpegRgbPacketProcessor] avg. time: 0ms -> ~infHz22/11/16, 11:52:32 IST
[Info] [DepthPacketStreamParser] 36 packets were lost22/11/16, 11:52:32 IST
[Info] [DepthPacketStreamParser] 35 packets were lost22/11/16, 11:52:33 IST
[Info] [DepthPacketStreamParser] 8 packets were lost22/11/16, 11:52:34 IST
[Info] [DepthPacketStreamParser] 34 packets were lost22/11/16, 11:52:35 IST
[Info] [TurboJpegRgbPacketProcessor] avg. time: 0ms -> ~infHz

If anyone has gotten something like this before ?
I am unable to debug the reason for this.

**Comment by xlz** [comment]
You can ignore this. It's not important.
