### ISSUE TITLE
turn off logo light when camera usb and device is off

### ISSUE THREAD

**Issue by mpatalberta** [OpenKinect/libfreenect2#766]
Overview Description:

Version, Platform, and Hardware Bug Found:

1. `git log -1 --oneline`
2. `uname -a`
3. `lsusb -t`
4. `lspci -nn`

Steps to Reproduce:

1. 
2. 
3. 

Actual Results:

Expected Results:

Reproducibility:

Additional Information:

**Comment by mpatalberta** [comment]
When the camera is off the logo would be nice to be off.

**Comment by xlz** [comment]
I don't know to do this. We haven't reverse engineered this part.

**Comment by mpatalberta** [comment]
How and where in the code does the Kinectv2 logo light get turned on?

**Comment by mpatalberta** [comment]
sorry hit wrong button

**Comment by xlz** [comment]
>How and where in the code does the Kinectv2 logo light get turned on?
There is no code that does this.

**Comment by xlz** [comment]
CANTFIX
