### ISSUE TITLE
expose a in the libfreenect2 in the depth,rub data stream the acquisition of the from of the libusb interface

### ISSUE THREAD

**Issue by mpatalberta** [OpenKinect/libfreenect2#767]
Overview Description:

Version, Platform, and Hardware Bug Found:

1. `git log -1 --oneline`
2. `uname -a`
3. `lsusb -t`
4. `lspci -nn`

Steps to Reproduce:

1. 
2. 
3. 

Actual Results:

Expected Results:

Reproducibility:

Additional Information:

**Comment by mpatalberta** [comment]
When you are using the libfreenect2 api i do not see the actual reception time of the data from the usb interface.

**Comment by mpatalberta** [comment]
You have timeStamp which is acurrate to 0.1ms. A time stamp that is expressed in real world time will allow to coordinate picture between multiple cameras across multiple machines. 
Where in the code is timeStamp set in the software?

**Comment by mpatalberta** [comment]
Thanks

**Comment by xlz** [comment]
The timestamp of each frame is coded by the camera hardware relative to the one camera only. You can take your own wall time stamp if you want to compare multiple cameras.

**Comment by mpatalberta** [comment]
I am having a hard time seeing where the hardware assigns the 0.1 millisecond time stamp.
Can you please indicate where about this occurs.

**Comment by xlz** [comment]
The hardware timestamp is just what is being transmitted from the hardware. We don't know where it is assigned either.
