### ISSUE TITLE
Finding World co-ordinates

### ISSUE THREAD

**Issue by sairamkolla** [OpenKinect/libfreenect2#769]
Hello there,

I'm trying to find world co-ordinates of a color pixel. For this I found the depth to color mapping using `registration->apply() ` function with the **bigdepth** parameter. Now how to find the world coordinates of any depth pixel in this range??

My understanding of `getPointXYZ()` function is that it only returns the world coordinates of depth pixel in the range 512x424. But now my depth pixels are in the range 1920x1082. 

Thankyou

**Comment by xlz** [comment]
1. Get RGB camera intrinsics
2. Project a ray from a pixel in RGB image
3. Use the depth from corresponding pixel in bigdepth to find the 3D point on the ray

**Comment by sairamkolla** [comment]
Hello,

Can you please elaborate on the 2nd step? How to find the corresponding depth pixel for the color pixel?

I thought they have one to one correspondance i..e `colorpixel[i,j]` has the depth pixel `bigdepth[1920*i+j]`  because that's what registration from color to depth does right? Please correct me if I'm wrong.

Thanks

**Comment by xlz** [comment]
`colorpixel[x,y] <-> bigdepth[x,y+1]`?

**Comment by sairamkolla** [comment]
Yes, I'm asking if that holds.Thanks!

**Comment by xlz** [comment]
Yes

**Comment by sairamkolla** [comment]
Hi!

Actually I wanted to find the world coordinates of the corners of the chess board. So I found the bigDepth image, but the depth values of some of these corners are '0' in the bigDepth image. Can you tell why?

As @floe mentioned in #708 that bigDepth is upsampled version of depth image, how there are zeros in the bigDepth image when depth image doesn't have zeros in that ROI ( here ROI is the checkerboard)

Thanks


**Depth Image**
![screenshot from 2016-12-13 22-58-09](https://cloud.githubusercontent.com/assets/14178941/21152131/21d0e73c-c18b-11e6-8d13-1e06795a1466.png)

**bigDepth image**
![screenshot from 2016-12-13 22-59-07](https://cloud.githubusercontent.com/assets/14178941/21152132/21fc7956-c18b-11e6-99b5-d839b624c2f0.png)

**bigDepth values of some corners**
![screenshot from 2016-12-13 23-23-04](https://cloud.githubusercontent.com/assets/14178941/21152133/220ee0be-c18b-11e6-936c-045eaee466bf.png)

**Comment by xlz** [comment]
> here are zeros in the bigDepth image when depth image doesn't have zeros in that ROI 
I don't see any of the case.

**Comment by sairamkolla** [comment]
@xlz  in the 3rd image, as you can see the last column is the bigDepth value of that particular corner. Most of them are non zeros and are almost equal(since the board is in vertical position). But some values are zeros.

The code I used to access the bigDepth value is 

`depth_value  = float(bigDepth.data[int(corners[i].x),int(corners[i].y) + 1])`

Thankyou

**Comment by xlz** [comment]
The small depth image also has zeros in that ROI, so what's the problem?

**Comment by sairamkolla** [comment]
My ROI is the chessboard only. In the small depth image there are no zeros in that region. But I get zeros from the bigDepth image.

**Comment by xlz** [comment]
I think these are zeros
![21d0e73c-c18b-11e6-8d13-1e06795a1466](https://cloud.githubusercontent.com/assets/1385542/21154268/c6cdac52-c13b-11e6-907e-7bdb4bedf00c.png)

**Comment by sairamkolla** [comment]
ok, I still don't understand why I'm getting the checkerboard pattern in the depth image. Any idea? Sometimes I get complete grayscale image and sometimes this pattern(Hence the zeros in this case).

Also,is there any other approach for finding the world coordinates?

PS: I'm trying to implement icp algorithm for finding R and T matrices for calibration. For this I need world coordinates of the corner points.

Thankyou

**Comment by xlz** [comment]
I think the zero areas are dark blocks with no reflection. ToF cameras need reflection to get depth signals. An alternative would be fitting a surface with the checkerboard so you have all points on the surface.

**Comment by sairamkolla** [comment]
>  fitting a surface with the checkerboard

Can you elaborate what you mean by this? Currently my checkerboard is on a metal sheet. 

Thanks for your reply.

**Comment by xlz** [comment]
http://pointclouds.org/documentation/tutorials/planar_segmentation.php#planar-segmentation
