### ISSUE TITLE
Wrong colours when using TegraJPEG for RGB processing on Jetson TK1

### ISSUE THREAD

**Issue by ksze** [OpenKinect/libfreenect2#774]
Overview Description:

Version, Platform, and Hardware Bug Found:

1. `git log -1 --oneline`
    cec93c7 Merge pull request #765 from xlz/disable-default-constructors

2. `uname -a`

        Linux tegra-ubuntu 3.10.40-ga7da876 #1 SMP PREEMPT Tue Jun 7 21:05:06 PDT 2016 armv7l armv7l armv7l GNU/Linux`

3. `lsusb -t`

        /:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=tegra-ehci/1p, 480M
            |__ Port 1: Dev 5, If 0, Class=Hub, Driver=hub/4p, 480M
                |__ Port 1: Dev 6, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
                |__ Port 2: Dev 7, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
        /:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=tegra-xhci/2p, 5000M
            |__ Port 1: Dev 4, If 0, Class=Hub, Driver=hub/1p, 5000M
                |__ Port 1: Dev 5, If 0, Class=Vendor Specific Class, Driver=, 5000M
                |__ Port 1: Dev 5, If 1, Class=Vendor Specific Class, Driver=, 5000M
                |__ Port 1: Dev 5, If 2, Class=Audio, Driver=snd-usb-audio, 5000M
                |__ Port 1: Dev 5, If 3, Class=Audio, Driver=snd-usb-audio, 5000M
        /:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=tegra-xhci/6p, 480M
            |__ Port 3: Dev 3, If 0, Class=Hub, Driver=hub/1p, 480M
4. `lspci -nn`

        00:00.0 PCI bridge [0604]: NVIDIA Corporation TegraK1 PCIe x1 Bridge [10de:0e13] (rev a1)
        01:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 0c)

Steps to Reproduce:

1. Configure libfreenect2 with `ENABLE_TEGRAJPEG` in cmake;
2. Build it.
3. Run `Protonect cudakde`

Actual Results:
Colour image has red and blue channels swapped.

Expected Results:
Correct colour image.

Reproducibility:
Always

**Comment by xlz** [comment]
`frame->format == Format::RGBX` with your setup while the viewer displays in BGRX.
