### ISSUE TITLE
[Question] Depth data, Kinect v1 v/s Kinect v2?

### ISSUE THREAD

**Issue by pranali3215** [OpenKinect/libfreenect2#776]
Hi,

I have been using Kinect v1 previously and have recently shifted to Kinect v2.  I thought that the depth data information coming from both the cameras was same. 
However, where before I used to get 123 cm, now I get 3 cm for the same distance.

Thus, my question is what difference is there between the two cameras pertaining to depth information?
Also, how do I get depth data in cm in Kinect v2 for a ROI ?

**Comment by mpatalberta** [comment]
No the depth camera of the Kinectv2 has more depth pixel.
I think the unites are in meters.
Look in the iai_kinectv2 code base in git.

**Comment by xlz** [comment]
Question is answered.
