### ISSUE TITLE
Protonect crash on startup on OS X 10.10 

### ISSUE THREAD

**Issue by aamedina** [OpenKinect/libfreenect2#78]
Just got my Kinect Adapter yesterday. After the project was built without error and running Protonect the following is dumped to stdout. 

[Freenect2Impl] enumerating devices...
[Freenect2Impl] 5 usb devices connected
[Freenect2Impl] found valid Kinect v2 @20:1 with serial 032187733747
[Freenect2Impl] found 1 devices
[Freenect2Impl] failed to reset Kinect v2 @20:1!
no device connected or failure opening the default one!

A black window (I'm guessing the GL Window) flashes during this process. If I run test_opengl, the resulting stack trace seems to point to libGL as the source of the error. I think Apple changed things around with the GL frameworks in 10.10, so that might be the source of the crash, but I am ultimately unsure. 

Here's the full dump after running test_opengl: https://gist.github.com/aamedina/15efdc445edbb8f617c8

**Comment by Lyptik** [comment]
Same for me on OSX 10.9.5 @dmitryfd 's workaround solved it same way (still ran into problem #31 )
