### ISSUE TITLE
libfreenect2 and GTX1070

### ISSUE THREAD

**Issue by QinZiwen** [OpenKinect/libfreenect2#784]
I have a GTX1070 and I install ubuntu 14.04 in my notebook computer(hp OMEN 17-W119TX PLUS). Does libfreenect2 compatible with nvidia GTX1070, and should I use cuda8.0 or cuda7.5 ?

**Comment by xlz** [comment]
compatible.

doesn't have preference between Cuda 8.0 and 7.5.
