### ISSUE TITLE
packetsize or sequence doesn't match!

### ISSUE THREAD

**Issue by sairamkolla** [OpenKinect/libfreenect2#787]
Hi,

I'm trying to set a server and client system where the client program uses libfreenect2 to capture an RGB image whenever the server sends a message. 

The code of the client program looks like this.

``` 
while(count < no_frames){
    get_approval_from_server();
    if (!dev->start())
        return -1;
    else
        std::cout << "device started" << std::endl;
    if (!listener.waitForNewFrame(frames, 10*1000)) // 10 sconds
    {
        std::cout << "timeout!" << std::endl;
        return -1;
    }
    dev->stop(); \\ Pausing here for the next iteration
    rgb = frames[libfreenect2::Frame::Color];
    save_image(rgb);
}
```

All works well for the first iteration. But after I start (resume) the device in the second iteration I get an error ``packetsize or sequence doesn't match!``. Can someone tell why this is happening? 

![screenshot from 2017-01-25 00-07-20](https://cloud.githubusercontent.com/assets/14178941/22261469/2233ec8c-e293-11e6-9651-bc212d84b5bd.png)

**Comment by xlz** [comment]
An initial frame has incomplete data. Nothing to worry about. Ignore.
