### ISSUE TITLE
Kinect 1520 on Mac Sierra - No camera device

### ISSUE THREAD

**Issue by abeythomas** [OpenKinect/libfreenect2#788]
<img width="667" alt="screen shot 2017-01-25 at 9 59 39 pm" src="https://cloud.githubusercontent.com/assets/25354445/22309114/25e10308-e34a-11e6-8629-1995911e43bd.png">

No idea about this error.  Was just following the steps.
And by the way I have USB.3.0 and the depth is working while testing in Processing.
Please help!

**Comment by xlz** [comment]
The steps don't cover the case where you already have a libfreenect2 directory in place.
`rm -r ~/libfreenect2` and try again.

**Comment by abeythomas** [comment]
Kinect 1520 on mac - No Camera device(continued) #4

<img width="981" alt="screen shot 2017-01-25 at 11 50 48 pm" src="https://cloud.githubusercontent.com/assets/25354445/22312841/0355fd92-e35a-11e6-92ea-1a06b7ea6606.png">

This is what I got after removing the libfreenect2 folder and installing again
(Sorry for the trouble, I'm new to all these troubleshooting)
Please let me know know if there's a solution. Thanks

**Comment by xlz** [comment]
Did you follow this step?

> Make sure these build tools are available: wget, git, cmake, pkg-config. Xcode may provide some of them. Install the rest via package managers.

**Comment by abeythomas** [comment]
Yes! working now. Thanks a lot. 
I thought pkg-config was already there with Xcode, because it came up while searching in spotlight.
