### ISSUE TITLE
cannot read depth higher than 5000

### ISSUE THREAD

**Issue by danx0r** [OpenKinect/libfreenect2#789]
Overview Description: 

increasing max_depth:  recompiled with max_depth=10000
CL pipeline still sets anything over 4500 to zero
CPU pipeline shows readings>4500 but nothing seems to register > 5000 except occasional noise
I've read the hardware can sense up to 8 or 9 meters
is there a known path to getting that to work?

Version, Platform, and Hardware Bug Found: 

1. `git log -1 --oneline` 
cec93c7 Merge pull request #765 from xlz/disable-default-constructors

2. `uname -a` 
Linux dbm-Surface-Pro-3 4.4.6-3-surface #tigerite ZEN SMP Tue May 24 13:22:59 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

3. `lsusb -t`
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/1p, 5000M
        |__ Port 1: Dev 4, If 0, Class=Vendor Specific Class, Driver=, 5000M
        |__ Port 1: Dev 4, If 1, Class=Vendor Specific Class, Driver=, 5000M
        |__ Port 1: Dev 4, If 2, Class=Audio, Driver=snd-usb-audio, 5000M
        |__ Port 1: Dev 4, If 3, Class=Audio, Driver=snd-usb-audio, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/9p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/1p, 480M
    |__ Port 3: Dev 3, If 0, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 6: Dev 6, If 0, Class=Wireless, Driver=btusb, 480M
    |__ Port 6: Dev 6, If 1, Class=Wireless, Driver=btusb, 480M
    |__ Port 6: Dev 6, If 2, Class=Vendor Specific Class, Driver=, 480M
    |__ Port 7: Dev 4, If 0, Class=Video, Driver=uvcvideo, 480M
    |__ Port 7: Dev 4, If 1, Class=Video, Driver=uvcvideo, 480M
    |__ Port 7: Dev 4, If 2, Class=Video, Driver=, 480M
    |__ Port 8: Dev 5, If 0, Class=Video, Driver=uvcvideo, 480M
    |__ Port 8: Dev 5, If 1, Class=Video, Driver=uvcvideo, 480M
    |__ Port 8: Dev 5, If 2, Class=Video, Driver=, 480M

4. `lspci -nn`
00:00.0 Host bridge [0600]: Intel Corporation Haswell-ULT DRAM Controller [8086:0a04] (rev 0b)
00:02.0 VGA compatible controller [0300]: Intel Corporation Haswell-ULT Integrated Graphics Controller [8086:0a16] (rev 0b)
00:03.0 Audio device [0403]: Intel Corporation Haswell-ULT HD Audio Controller [8086:0a0c] (rev 0b)
00:14.0 USB controller [0c03]: Intel Corporation 8 Series USB xHCI HC [8086:9c31] (rev 04)
00:16.0 Communication controller [0780]: Intel Corporation 8 Series HECI #0 [8086:9c3a] (rev 04)
00:1b.0 Audio device [0403]: Intel Corporation 8 Series HD Audio Controller [8086:9c20] (rev 04)
00:1c.0 PCI bridge [0604]: Intel Corporation 8 Series PCI Express Root Port 3 [8086:9c14] (rev e4)
00:1f.0 ISA bridge [0601]: Intel Corporation 8 Series LPC Controller [8086:9c43] (rev 04)
00:1f.2 SATA controller [0106]: Intel Corporation 8 Series SATA Controller 1 [AHCI mode] [8086:9c03] (rev 04)
00:1f.3 SMBus [0c05]: Intel Corporation 8 Series SMBus Controller [8086:9c22] (rev 04)
01:00.0 Ethernet controller [0200]: Marvell Technology Group Ltd. 88W8897 [AVASTAR] 802.11ac Wireless [11ab:2b38]

Steps to Reproduce:

1. 
2. 
3. 

Actual Results:

Expected Results:

Reproducibility:

Additional Information:

**Comment by danx0r** [comment]
so.. no??

**Comment by mpatalberta** [comment]
if you tie the code to kinectv2_bridge their is a maxdepth you need change also

**Comment by danx0r** [comment]
no not using ROS -- just pylibfreenect2 -

as said I see occasional samples > 4500 but they are mostly noise (and only with slow CPU pipeline)

**Comment by mpatalberta** [comment]
There is a KDE enable to 20 meters in libfreenect2

**Comment by felja633** [comment]
To change the maxDepth you need to set the config-parameters in Freenect2Device::Config::Config. The default maxDepth is 4500.

It can be changed with setConfiguration(const Freenect2Device::Config &config) in the libfreenect2::Freenect2Device, see libfreenect.cpp.

The maximum depth is 18750, after that it will wrap around.

**Comment by xlz** [comment]
> The maximum depth is 18750

I think this should be the theoretical upper limit? I probably should put it in the doc the next time.

**Comment by ArkadiyEpanov** [comment]
> To change the maxDepth you need to set the config-parameters in Freenect2Device::Config::Config. The default maxDepth is 4500.
> 
> It can be changed with setConfiguration(const Freenect2Device::Config &config) in the libfreenect2::Freenect2Device, see libfreenect.cpp.
> 
> The maximum depth is 18750, after that it will wrap around.

Hello, is it possible to do this on python (pylibfreenect2) without recompiling the freenect2 library?
