### ISSUE TITLE
Getting the Depth of a Planar Surface

### ISSUE THREAD

**Issue by evancloutier** [OpenKinect/libfreenect2#790]
I'm using libfreenect2 with a Kinect v2 and am wondering if it is possible to retrieve the (mean - most likely) depth of a planar surface seen in my Kinect stream.

For example, let's say I'm tracking a point on a hand and retrieve the depth values for said point using the getPointXYZ method. Is there a way to retrieve the x and y coordinates for a constant depth value on the z-plane? This depth value would then be compared to the original point on the hand to calculate their difference in depth.

**Comment by xlz** [comment]
I don't follow your question. How do you get the planar surface? What is the z-plane?
