### ISSUE TITLE
Obtaining uncompressed images from Kinect

### ISSUE THREAD

**Issue by DM1089** [OpenKinect/libfreenect2#791]
I am trying to understand if Kinect for Windows v2 is suitable for my application. Is it possible to get the uncompressed images from the RGB camera and IR camera at 30fps? If so, at what resolution?Please send pointer to documentation on the APIs and raw format. Thanks.

**Comment by floe** [comment]
https://openkinect.github.io/libfreenect2/classlibfreenect2_1_1Frame.html

**Comment by xlz** [comment]
No data is compressed anyway. Yeah, see the doc for getting raw data.
