### ISSUE TITLE
How to update OpenGL from 3.0 to 3.1 (Cuz I got a problem: Failed to create opengl window)

### ISSUE THREAD

**Issue by Allen-jl** [OpenKinect/libfreenect2#794]
First, I ran:
aicrobo@ubuntu:~/libfreenect2/build$ ./bin/Protonect core
Version: 0.2.0
Environment variables: LOGFILE=<protonect.log>
Usage: ./bin/Protonect [-gpu=<id>] [gl | cl | clkde | cuda | cudakde | cpu] [<device serial>]
        [-noviewer] [-norgb | -nodepth] [-help] [-version]
        [-frames <number of frames to process>]
To pause and unpause: pkill -USR1 Protonect
Unknown argument: core
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 11 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @4:3 with serial 007657354647
[Info] [Freenect2Impl] found 1 devices
[Error] [OpenGLDepthPacketProcessorImpl] GLFW error 65543 The requested client API version is unavailable
[Error] [OpenGLDepthPacketProcessor] Failed to create opengl window.

And when I ran: glxinfo | grep OpenGL
aicrobo@ubuntu:~/libfreenect2/build$ glxinfo | grep OpenGL
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.5, 256 bits)
OpenGL version string: 3.0 Mesa 10.3.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:

According to https://github.com/OpenKinect/libfreenect2/wiki/Troubleshooting, it says "OpenGL version string" must be greater than 3.1. 
So how to update my old opengl version? THX

**Comment by xlz** [comment]
Install proper graphics drivers (which is a big mess of a topic to address, look up your vendor's doc).
