### ISSUE TITLE
problem including libusb in Qt

### ISSUE THREAD

**Issue by javadhabibi** [OpenKinect/libfreenect2#797]
hi,i want to use libusb in Qt 5.7 on win7. but i am confused what should be add to Qt? there is many files in libusb-1.0.21 folder: [here](https://freefr.dl.sourceforge.net/project/libusb/libusb-1.0/libusb-1.0.21/libusb-1.0.21.tar.bz2)
which of them should be used?
thanks.

**Comment by xlz** [comment]
Ask the question here https://github.com/libusb/libusb/issues
