### ISSUE TITLE
Linux version doesn't work with Intel USB3 controller

### ISSUE THREAD

**Issue by floe** [OpenKinect/libfreenect2#8]
This is more for documentations' sake - I currently have no idea if this bug is related to libfreenect2, libusbx or the Linux kernel, although I suspect the kernel. That being said, I was unable to get ISO transfers to work with this controller:

```
Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04)
```

On the other hand, the following controller works on two separate machines:

```
NEC Corporation uPD720200 USB 3.0 Host Controller (rev 04)
```

**Comment by vedanshu95** [comment]
@AmmarkoV  i have upgraded the kernel and got the libfreenect2 working in ubuntu 14.04. but i am having a problem. i can see the rgb camera but i am unable to see anything in ifrared and dept. 
![screenshot from 2015-05-15 11 44 14](https://cloud.githubusercontent.com/assets/12307323/7662760/82bf5288-fb15-11e4-912e-e7b1d4960088.png)
