### ISSUE TITLE
Registered rgb / depth

### ISSUE THREAD

**Issue by roliveiradoteu** [OpenKinect/libfreenect2#801]
Is it possible to change the format of the registered stream (rgb + depth) in order to avoid having the black borders as seen in the image? 

<a href="https://ibb.co/iyDfwF"><img src="https://preview.ibb.co/j0wNAa/snapshot1.png" alt="snapshot1" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>cloud image storage</a><br />

Thank you in advance!

**Comment by floe** [comment]
The black borders are there because the depth and RGB cameras have a different field of view. Of course, you can crop/resize it in your own code.

**Comment by xlz** [comment]
Question is answered.
