### ISSUE TITLE
can you help me 

### ISSUE THREAD

**Issue by ssw123** [OpenKinect/libfreenect2#803]
-- using tinythread as threading library
-- checking for module 'libusb-1.0>=1.0.20'
--   package 'libusb-1.0>=1.0.20' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  cmake_modules/FindLibUSB.cmake:21 (PKG_CHECK_MODULES)
  CMakeLists.txt:93 (FIND_PACKAGE)

-- checking for modules 'libva;libva-drm'
--   package 'libva' not found
--   package 'libva-drm' not found
-- Found Linux4Tegra 21.4.0
-- Linking with these libraries: 
 LibUSB_LIBRARY-NOTFOUND
 pthread
 dl
 /usr/lib/arm-linux-gnueabihf/libturbojpeg.so.0
 /usr/lib/arm-linux-gnueabihf/libglfw.so
 /usr/lib/arm-linux-gnueabihf/libGL.so
 /usr/lib/arm-linux-gnueabihf/libOpenCL.so
 /usr/local/cuda-6.5/lib/libcudart.so
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configurating examples
-- Using in-tree freenect2 target
-- checking for module 'libopenni2'
--   package 'libopenni2' not found
-- Could NOT find OpenNI2 (missing:  OpenNI2_LIBRARY_DIR OpenNI2_INCLUDE_DIRS) 
-- Feature list:
--   CUDA    yes
--   CXX11    disabled
--   Examples    yes
--   OpenCL    yes
--   OpenGL    yes
--   OpenNI2    no
--   TegraJPEG    yes
--   Threading    tinythread
--   TurboJPEG    yes
--   VAAPI    no
--   VideoToolbox    no (Apple only)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LibUSB_LIBRARY
    linked by target "freenect2" in directory /home/ubuntu/libfreenect2-master

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/libfreenect2-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/libfreenect2-master/build/CMakeFiles/CMakeError.log".

**Comment by floe** [comment]
Please don't double-post.
