### ISSUE TITLE
The rgb and ir camera intrinsic parameters is accurate or not? Should i calibration myself?

### ISSUE THREAD

**Issue by BlazingForests** [OpenKinect/libfreenect2#805]
Hi, because i want use kinect2 to measure the box dimensions, so i want the point cloud need as accurate as possible.

So, the camera intrinsic parameters comes from `getIrCameraParams()` and`getColorCameraParams()`

My question is is that intrinsic parameters accurate or not? Should i calibration myself?

THX
DD

**Comment by xlz** [comment]
> as accurate as possible

The built parameters are surely not as accurate as possible.

**Comment by BlazingForests** [comment]
@xlz thanks, so i think i should do the calibration myself.
