### ISSUE TITLE
Help to get driver working with OpenNI2 (Linux)

### ISSUE THREAD

**Issue by Rep8** [OpenKinect/libfreenect2#806]
I've got the libfreenect2 driver with multiple kinect v2's with the protonect viewing tool, however I cannot work out how to get OpenNI2 up and running.

I only get the device not found prompt when trying anything.
I compiled the libfreenect2 driver for openni2 (pretty sure I did it correctly), then copied the driver files to multiple openni2/drivers locations just to be sure.

Any help/suggestions would be appreciated.

**Comment by xlz** [comment]
What is your question?

**Comment by Rep8** [comment]
Sorry I was pretty broad.

I want to be able to get the NiViewer2 for openni2 running with kinect2. Then from that NITE working along it.

I've got the protonect viewer working but the NiViewer2 just returns unable to open device when it tries to load the drivers.

**Comment by xlz** [comment]
Log?

**Comment by Rep8** [comment]
![log](https://cloud.githubusercontent.com/assets/8611648/23844445/60593c3a-0816-11e7-95cc-c5802af25838.png)

**Comment by xlz** [comment]
Did you install libfreenect2.so.0.2? Where is it?

**Comment by Rep8** [comment]
Okay I got it working, completely misread the log. I have added those drivers to the specified folder.
Only issue is in the NiViewer2 program, I have the depth and color images but not the ir camera image, is this normal?

Thank you very much though.

**Comment by xlz** [comment]
I think IR channel is available but just not shown?
