### ISSUE TITLE
The right way to increasing USBFS buffer size permanently

### ISSUE THREAD

**Issue by BlazingForests** [OpenKinect/libfreenect2#807]
Hi

I am try to increase USBFS buffer size today. I saw this https://github.com/OpenKinect/libfreenect2/wiki/Troubleshooting#multiple-kinects-try-increasing-usbfs-buffer-size

But it's not working.

After search, I found the right way is
```
$ sudo sh -c 'echo 128 > /sys/module/usbcore/parameters/usbfs_memory_mb'
```

But this command just affect until the next reboot. If you want modify it permanently. You can follow below steps.

* Open `/etc/default/grub` file,Find and replace
```
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
```
with this
```
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash usbcore.usbfs_memory_mb=128"
```

* Update grub
```
$ sudo update-grub
```

* Reboot and check
```
$ cat /sys/module/usbcore/parameters/usbfs_memory_mb
```

THX
DD

**Comment by xlz** [comment]
`#` is the root prompt.

I don't use grub.

Thanks for the notice.
