### ISSUE TITLE
 invert/flip horizontally a point cloud

### ISSUE THREAD

**Issue by alexge233** [OpenKinect/libfreenect2#808]
Hi,

I know there is an issue on this, but I can't for the life of me figure out how to do it.
My point cloud is mirrored horizontally (left is right, right is left), is there some way to either stop this from happening, or rectify the points after I've acquired them? I'm using `getPointXYZ` on `depth` data.

**Comment by xlz** [comment]
Use something like `getPointXYZ(424 - x, y, z)`?

**Comment by doge-of-the-day** [comment]
I had a similar problem, my solution was to multiply the x coordinates with -1. 
After that the point cloud looked fine.

**Comment by alexge233** [comment]
Yeah, multiplying the x with -1 solved it nicely without miss-aligning coordinates in the global frame. Tons of thanks!!!
