### ISSUE TITLE
Use libfreenect2 without screen

### ISSUE THREAD

**Issue by peterpans01** [OpenKinect/libfreenect2#809]
Overview Description:
I need to run an application using libfreenect2 without screen. Libfreenect2 uses the GLFW which requires screen

Platform: Linux/Fedora.

Steps to Reproduce:
1. Unplug the screen
2. Reboot system 
3. Launch Protonect (through ssh) 

Actual Results:
         startx[1295]: libfreenectProcessAcquisition::init
         startx[1295]: libfreenectProcessAcquisition::init - glfwInit
         startx[1295]: libfreenectProcessAcquisition::init - with OpenGL
         startx[1295]: libfreenectProcessAcquisition::init - with OpenGL - pipeline
         startx[1295]: [Error] [OpenGLDepthPacketProcessorImpl] GLFW error 65544 No monitors found
         startx[1295]: [Error] [OpenGLDepthPacketProcessor] Failed to initialize GLFW.

Expected Results:
       Works like charm. I can receive the data from Kinect 2 and process on it.

Additional Information:
       Actually I just need to get the data from Kinect2. Is there a way to work around this problem? if you need more infos, just drop a comment.

Thanks in advance!

**Comment by xlz** [comment]
Don't use OpenGL pipeline then. Use OpenCL or CUDA.
