### ISSUE TITLE
libfreenect2 Nivewer Mac OS X sierra

### ISSUE THREAD

**Issue by tarekest1** [OpenKinect/libfreenect2#813]
I can run the Nivewer only with CPU (LIBFREENECT2_PIPELINE=cpu). When i try to debug the Nivewer putting  
LIBFREENECT2_PIPELINE value's to gl, or cl. I get a warning message telling that glutinit was called  one second Time. The debugguer indicates that gflw was pointing to null.

**Comment by xlz** [comment]
Need more information.

**Comment by xlz** [comment]
Not enough information.
