### ISSUE TITLE
v0.2 doesn't power off, v0.1 does

### ISSUE THREAD

**Issue by Leon99** [OpenKinect/libfreenect2#816]
Using VS2015 binaries from https://github.com/OpenKinect/libfreenect2/releases.
libusbK 3.0.7.0

protonect from v0.2 doesn't power off a Kinect on exit (white LED stays on), v0.1 does (this is expected behaviour). Logs show the same.

Any ideas?

**Comment by xlz** [comment]
Can't reproduce.
