### ISSUE TITLE
How to get the raw phase image

### ISSUE THREAD

**Issue by wangsen1312** [OpenKinect/libfreenect2#821]
The Kinect V2 should have 3*3 phase image for each depth image. How to get them?

I have tried to use the DumpPacketPipeline to get the "rawest" data and decode it myself , but the IR frame seems not right.

The code I used is:

      libfreenect2::Freenect2 freenect2;
      libfreenect2::Freenect2Device *dev = nullptr;
      libfreenect2::DumpPacketPipeline *pipeline = nullptr; 

	if (freenect2.enumerateDevices() == 0){
		cout << "no device connected!" << endl;
		return -1;
	}
	string serial = freenect2.getDefaultDeviceSerialNumber();
        int depthProcessor = Processor::cpu;
	if (depthProcessor == Processor::cpu)
	{
		if (!pipeline)
		pipeline = new libfreenect2::DumpPacketPipeline();
	}
	else{
		cout << "failure using other processor (OPENCL or CUDA)!" << endl;
		return -1;
	}

	if (pipeline){
		dev = freenect2.openDevice(serial, pipeline);//! [open]
	}
	else {
		dev = freenect2.openDevice(serial);
	}

        bool enable_rgb = false;
	bool enable_depth = true;

	int types = 0;
	if (enable_rgb){
		types |= libfreenect2::Frame::Color;
	}
	if (enable_depth){
		types |= libfreenect2::Frame::Ir | libfreenect2::Frame::Depth;
	}
	libfreenect2::SyncMultiFrameListener listener(types);

	libfreenect2::FrameMap frames;

	dev->setColorFrameListener(&listener);
	dev->setIrAndDepthFrameListener(&listener);

	dev->start();

	Mat depthmat, irmat;

	//! [loop start]
	while (!protonect_shutdown)
	{
		listener.waitForNewFrame(frames);

		libfreenect2::Frame *ir = frames[libfreenect2::Frame::Ir];
		ir->format = libfreenect2::Frame::Raw;
		libfreenect2::Frame *depth = frames[libfreenect2::Frame::Depth];
		depth->format = libfreenect2::Frame::Raw;  //hope it works

		cv::Mat(ir->height, ir->width, CV_32FC1, ir->data).copyTo(irmat);
		cv::Mat(depth->height, depth->width, CV_32FC1, depth->data).copyTo(depthmat);

		
		//! [loop end]
		listener.release(frames);
	}

Another solution maybe use the cpu_depth_packet_processor to process the depth packet such as the:
CpuDepthPacketProcessor::process(const DepthPacket &packet)
and hack it.
The main thing I want to know is how can I get the 'DepthPacket'

Someone can help me? Thank you very much

**Comment by xlz** [comment]
You did get `DepthPacket` at `depth->data`.

https://openkinect.github.io/libfreenect2/classlibfreenect2_1_1Frame.html#ab4e88c89b3b7ea1735996cc4def22d58a5bdc2d0b1113f3630fc502864541fc23

> Raw 	Raw bitstream. 'bytes_per_pixel' defines the number of bytes.

**Comment by wangsen1312** [comment]
@xlz   
Thank you for your replying.
from DumpPacketPipeline,  the raw IR and raw depth data have any difference?

**Comment by floe** [comment]
The IR/depth frames are calculated from the 9 raw phase images. There's no 1:1 relationship.

**Comment by wangsen1312** [comment]
@floe    Thank you for your replying.  
I have seen that the depth image are calculated from the 9 raw images, This is using the ToF principal. I don't know how the ordinary IR images come from? average?

**Comment by xlz** [comment]
The 'ordinary IR images' are also computed from the 9 raw images. You will need to read relevant algorithms to understand how it is computed. You can start from here https://github.com/OpenKinect/libfreenect2/blob/master/src/cpu_depth_packet_processor.cpp

**Comment by xlz** [comment]
Question is answered.

**Comment by HIMA-MB02** [comment]
Which version of OpenCV did you use?
