### ISSUE TITLE
How to save Mat structure 

### ISSUE THREAD

**Issue by wangsen1312** [OpenKinect/libfreenect2#824]
I want to know how to save the Mat structure to file?
such as the 
Mat<Vec<float, 9> >    m(424, 512); in
https://github.com/OpenKinect/libfreenect2/blob/master/src/cpu_depth_packet_processor.cpp#914

Thank you very much!

**Comment by xlz** [comment]
```
fwrite(m.buffer(), m.sizeInBytes(), 1, file);
```
