### ISSUE TITLE
Device not found! -- why? please...

### ISSUE THREAD

**Issue by limengze126** [OpenKinect/libfreenect2#825]
I tried to connect Kinect with Mac OS. I followed the instructions step by step and no error occurred. However, when I tried to run "bin/Protonect" it always said no device connected.

By the way, when I try to verify XBOX NUI Sensor is under USB 3.0, I surprisingly found out that there is no  Xbox Nui Sensor under NuiSensor Adaptor. (in system information).

Could you please help me with it?

Thanks a lot!
Best,
Mengze Li

**Comment by xlz** [comment]
Did you plug Kinect to the adaptor?

**Comment by limengze126** [comment]
Thank you for your reply! I plugged Kinect to the adaptor. Later, I tried to unplug the power plug and re-plug, and it works.

Best,
Mengze
On Apr 13, 2017, at 8:19 PM, Lingzhu Xiang <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you plug Kinect to the adaptor?
