### ISSUE TITLE
libfreenect2 on debian sid no data is being displayed. 

### ISSUE THREAD

**Issue by chanfr** [OpenKinect/libfreenect2#83]
Hi, 
Im using a kinect2 with libfreenect on debian sid x64 with a GeForce 8800 GTS.
My motherboard is a asus b85-plus 
usb:
USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI (rev 05)

I followed all the steps and the device is detected but no images are being displayed.
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 12 usb devices connected
[Freenect2Impl] found valid Kinect v2 @2:1 with serial 507363442542
[Freenect2Impl] found 1 devices
[Freenect2DeviceImpl] opening...
[Freenect2DeviceImpl] opened
[Freenect2DeviceImpl] starting...
[Freenect2DeviceImpl] ReadData0x14 response
92 bytes of raw data
0x0000:  00 00 12 00 00 00 00 00 01 00 00 00 43 c1 1f 41    ............C..A
0x0010:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x0020:  0a 21 33 55 c2 00 17 20 00 08 00 00 10 00 00 00    .!3U... ........
0x0030:  00 01 00 00 00 10 00 00 00 00 80 00 01 00 00 00    ................
0x0040:  31 33 00 00 00 08 0d 01 47 4d 53 33 35 32 2e 31    13......GMS352.1
0x0050:  58 00 00 00 00 00 00 00 00 00 00 00                X...........

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  7f 26 00 00                                        &..

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  7f 26 00 00                                        &..

[Freenect2DeviceImpl] enabling usb transfer submission...
[Freenect2DeviceImpl] submitting usb transfers...
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[TransferPool::submit] failed to submit transfer
[Freenect2DeviceImpl] started
device serial: 507363442542
device firmware: 2.3.3912.0.7
CREOOOOOOOO
[TurboJpegRgbPacketProcessor] avg. time: 16.7466ms -> ~59.7138Hz
[TurboJpegRgbPacketProcessor] avg. time: 16.5851ms -> ~60.2952Hz
[TurboJpegRgbPacketProcessor] avg. time: 16.6625ms -> ~60.015Hz
[TurboJpegRgbPacketProcessor] avg. time: 16.8561ms -> ~59.3259Hz
[TurboJpegRgbPacketProcessor] avg. time: 16.6779ms -> ~59.9597Hz
[TurboJpegRgbPacketProcessor] avg. time: 16.647ms -> ~60.0708Hz
[TurboJpegRgbPacketProcessor] avg. time: 16.5755ms -> ~60.33Hz

The Pronect seems to be block at     listener.waitForNewFrame(frames) while other theads is displaying the TurboJpeg info. Only a black window named OpenGLDepthPacketProcessor is displayed.

my opengl version:
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 3.3.0 NVIDIA 331.49
OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL version string: 3.3.0 NVIDIA 331.49
OpenGL shading language version string: 3.30 NVIDIA via Cg compiler

¿any idea?

**Comment by gnbl** [comment]
@chanfr 
> I've checked the libusb I were using and Pronect was linking to a non-patched libusb.
How did you test this? I'm trying to rule this out for https://github.com/OpenKinect/libfreenect2/issues/126
