### ISSUE TITLE
Assembler cannot create object files/'libusb.h' not found. Attached screenshots.

### ISSUE THREAD

**Issue by jessekirbs** [OpenKinect/libfreenect2#84]
Hello,

When I'm trying to install the drivers, I get close to completion and then receive a couple error messages which I've attached. Any help would be very helpful. I'm trying to get the Kinect v2 running on my iMac (Mavericks).
![screen shot 2014-11-06 at 12 38 52 pm](https://cloud.githubusercontent.com/assets/8700046/4943559/b467e9ea-65f5-11e4-8a12-02104634a6d8.png)
![screen shot 2014-11-06 at 12 39 51 pm](https://cloud.githubusercontent.com/assets/8700046/4943561/b7349970-65f5-11e4-988b-fe5444080b41.png)

**Comment by daniele8808** [comment]
Has anyone solved this problem? I'm in the same situations.
I tried to install libfreenect2 on my Mac and I clode to the end. I have the same string:

![schermata 2015-01-12 alle 22 39 01](https://cloud.githubusercontent.com/assets/6351044/5711565/d2f0dc24-9aab-11e4-8038-9f68a179bac5.png)

Can Anyone help Us?
I tried to write :
brew install autoconf automake libtool

but it told me that is already installed. The problem I think is before because when I wrote this command:

cmake CMakeLists.txt

I had and Error in thi string:

![schermata 2015-01-12 alle 22 41 53](https://cloud.githubusercontent.com/assets/6351044/5711631/45887bb6-9aac-11e4-87d3-4a25bc6f9059.png)

Can anyone help me?

**Comment by floe** [comment]
Is this still an issue? Did you run install_mac.sh before cmake?

**Comment by jessekirbs** [comment]
@floe Yes, unfortunately. Still an issue. I did run install_mac.sh before cmake (posted results below).  I tried reinstalling libusb, but still no luck. Any help would be greatly appreciated. I'd love to get this working. 

``JesseMBP:libfreenect2 jessekirberger$ sh ./depends/install_mac.sh
Cloning into '/Users/jessekirberger/libfreenect2/depends/libusb_src'...
remote: Counting objects: 10611, done.
remote: Total 10611 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (10611/10611), 2.38 MiB | 1.41 MiB/s, done.
Resolving deltas: 100% (7839/7839), done.
Checking connectivity... done.
Note: checking out 'v1.0.19'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at e11525c... libusb 1.0.19
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
./bootstrap.sh: line 16: aclocal: command not found
./install_deps.sh: line 17: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
Cloning into '/Users/jessekirberger/libfreenect2/depends/glfw_src'...
remote: Counting objects: 14494, done.
remote: Total 14494 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (14494/14494), 7.27 MiB | 2.53 MiB/s, done.
Resolving deltas: 100% (9075/9075), done.
Checking connectivity... done.
Note: checking out '3.0.4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at eab31f2... Added description of 3.0.4 release.
./install_deps.sh: line 33: cmake: command not found
make: *** No targets specified and no makefile found.  Stop.
./depends/install_mac.sh: line 14: wget: command not found
tar: Error opening archive: Failed to open 'libjpeg-turbo-1.3.1.tar.gz'
mv: rename libjpeg-turbo-1.3.1 to /Users/jessekirberger/libfreenect2/depends/libjpeg_turbo_src: No such file or directory
./depends/install_mac.sh: line 17: cd: /Users/jessekirberger/libfreenect2/depends/libjpeg_turbo_src: No such file or directory
cp: /config.guess: No such file or directory
cp: /config.sub: No such file or directory
./depends/install_mac.sh: line 22: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
./depends/install_mac.sh: line 26: cd: /System/Library/Frameworks/OpenCL.framework/Versions/A/Headers/: No such file or directory
Password:
sudo: wget: command not found``

**Comment by floe** [comment]
Your environment appears to be missing some crucial commands, notably aclocal, cmake and wget. I'm no Mac expert, so I don't exactly know how to install them, but you definitely need those first before you can actually compile the rest.

**Comment by jessekirbs** [comment]
@floe I don't believe these things were missing, but just to be safe I reinstalled autoconf, automake, cake, wget, nasm, and git. Still getting errors (posted below).

These errors after 'install_mac.sh'
```
cp: /config.guess: No such file or directory
cp: /config.sub: No such file or directory
./depends/install_mac.sh: line 26: cd: /System/Library/Frameworks/OpenCL.framework/Versions/A/Headers/: No such file or directory
```

**Comment by floe** [comment]
Hm, OK, I think I've noticed a minor bug: in install_mac.sh, there are two references to 
    LIBUSBX_SOURCE_DIR
which should actually be
    LIBUSB_SOURCE_DIR
That doesn't explain the cd /System/... error, but maybe it fixes part of your issues.

**Comment by jessekirbs** [comment]
@floe I think we're getting closer. Not sure if it's the change you made or that I added a folder called 'Headers' in /System/Library/Frameworks/OpenCL.framework/Versions/A and put the cl.hpp file in there.  The install_mac.sh seemed like it ran smoothly without any error this time, however when I run 'make && make install' I get the following error:

```
/Users/jessekirberger/Documents/Kinect/libfreenect2/examples/protonect/src/opencl_depth_packet_processor.cpp:43:10: fatal error: 
      'OpenCL/cl.hpp' file not found
#include <OpenCL/cl.hpp>
         ^
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/freenect2.dir/src/opencl_depth_packet_processor.cpp.o] Error 1
make[1]: *** [CMakeFiles/freenect2.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jessekirbs** [comment]
I'm going to close this issue, as I believe the original posted problem has been solved (not being able to locate libusb) but I will open another for this latest error about OpenCL.

**Comment by elliotwoods** [comment]
sorry to bring this one up again. i also get issue at the 
`/System/Library/Frameworks/OpenCL.framework/Versions/A/Headers/: No such file or directory`

I'm reinstalling xcode to right now to see if that brings the headers back into play. seems though that the framework doesn't come with headers in that location (some suggestions are that there is a version inside Xcode.app which does have headers. it may be necessary to point there somehow)

apologies to post on an old issue.
