### ISSUE TITLE
Registration 

### ISSUE THREAD

**Issue by tarekest1** [OpenKinect/libfreenect2#847]
I need to capture both Depth and RGB frames for an earlier offline registration. 
1- My first solution was to save frames in two binary files. The main issue was the volume of data to be saved especially for the RGB  binary file (because the size of RGB frame 1920x1080).  But also when i do an offline registration between depth and color frames I get something like this. 
![sample](https://cloud.githubusercontent.com/assets/13738467/25854072/0e853b08-34cf-11e7-84fb-c04ff00b1cbb.jpeg).

I can' understand why a got this black hole in the registration image whether the depth and rgn image are twice correctly displayed using imshow (OpenCV).

**Comment by floe** [comment]
Hm. Does it work for the live `protonect` view?

**Comment by tarekest1** [comment]
yes it seems worked correctly with protonect view.

**Comment by xlz** [comment]
Most likely this is a bug in your code. WIthout your code we can't tell anything.

**Comment by tarekest1** [comment]
is there any issue when converting data images to char* pointer from uchar*,  in order to save it in binary files. My registration works fine online but when i try to appy registration method in offline images i get a wrong result. i have checked the calibration parameters. it was the same.
