### ISSUE TITLE
How to adjust RGB-Depth registration performed by the driver?

### ISSUE THREAD

**Issue by mtee** [OpenKinect/libfreenect2#854]
I have compiled all the dependencies and the driver according to the instructions and everything runs fine, however the 'registered" depth and RGB are ![not totally aligned in Protonect](https://cloud.githubusercontent.com/assets/1214236/26191762/7f401598-3baf-11e7-8751-27695b0e7b03.png)

The same obviously also happens in all other programs that rely on registered frames from libfreenect2.
It is to expect that the factory calibration will not be perfect, but the registration seems to be off by just a few pixels in one direction. How do I proceed about fixing it? Is it possible without driver recompilation?

It might be a completely isolated issue, but the openni2 wrapper registration with the libfreenect2 is even worse than that:
![openni2registration](https://cloud.githubusercontent.com/assets/1214236/26192279/522d8246-3bb1-11e7-9052-bcba758029b5.png)

**Comment by floe** [comment]
I can't tell what the problem with the openni2 wrapper is right now.
That being said, the original registration looks just as expected - the "misalignment" you're seeing is simply the shadow your hand is casting in infrared (i.e. no depth data is available there).

**Comment by mtee** [comment]
The shadow is not the issue. A part of the hand has been registered to the depth pixels of the background. I have made a short video to better illustrate the problem:
http://gph.is/2qv3m2v
as you see, quite a few pixels of the contour of the red chair have been mapped to the wrong depths - those of the background wall.

**Comment by floe** [comment]
OK, misunderstood your question. I think what you're seeing is more or less the expected error for the factory calibration, it's only "good enough". If you perform your own calibration, e.g. with OpenCV and a chessboard pattern, then you will probably get better results.
