### ISSUE TITLE
NiTe 2.2 SimpleHandTracker keeps printing on console 

### ISSUE THREAD

**Issue by fsxskillz** [OpenKinect/libfreenect2#861]
Hi everyone, 

Version, Platform, and Hardware Bug Found:

2. 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. compiling libfreenect with openni2 support (as per readme)
2. grabbing NiTE2 (I got if from this repo)
3- placing libfreenect2/build/lib/libfreenect2-openni2.0.so in NiTE-Linux-x64-2.2/Samples/Bin/OpenNI2/Drivers
4 - Launching the UserViewer and the HandViewer works, but the both the simplehandtracker and simpleusertracker dont give any sample view

Actual Results: 
For the SimplaHandTracker and the SimpleUserTracker it keeps printing on the console without having any graphic result.

`[Info] [OpenGLDepthPacketProcessor] avg. time: 12.7669ms -> ~78.3274Hz
[Info] [TurboJpegRgbPacketProcessor] avg. time: 26.1085ms -> ~38.3017Hz
[Info] [OpenGLDepthPacketProcessor] avg. time: 12.0259ms -> ~83.1537Hz
[Info] [TurboJpegRgbPacketProcessor] avg. time: 20.1641ms -> ~49.5931Hz

but it doesn't help since i'm trying to have the skeleton tracking. 
I tried to see if something is missing in the code but i couldn't find it.
Do you know why it doesn't work ? 

Expected Results:
HandTracking and usable informations to process in order to deduce hand movement. 

Reproducibility: Every time

Additional Information:
I found a tutorial on NiTE 2.2 but all the links are dead, if someone have it, i would be thankful.

**Comment by Amorpheum** [comment]
I believe the samples of SimpleHandTracker and SimpleUserTracker are only meant to show console output, hence "Tracker".

UserViewer will give you the skeletal tracking. You will need to show your full body to the sensor. Also note that there is an initial calibration period that should not be take too long (anything more than 10s is too long).
