### ISSUE TITLE
How can i use skeleton tracking with libfreenect2?

### ISSUE THREAD

**Issue by Gudonggwan** [OpenKinect/libfreenect2#872]
I want use skeleton tracking with libfreenect2 but libfreenect2 can't use skeleton tracking alone

so i wonder libfreenect2 use OpenNI2 + Nite together 

Thank you.

**Comment by dimitrijevic** [comment]
I'd love to know this too, were you able to do my thing, and does OpenNI2 support Kinect V2?

**Comment by floe** [comment]
OpenNI2 wrapper is supported in the master branch; for everything else (NITE etc.), you'll have to look for other documentation.
