### ISSUE TITLE
jetson tx2  make error

### ISSUE THREAD

**Issue by koala99** [OpenKinect/libfreenect2#873]
when i make file，
the error occured
![res](https://user-images.githubusercontent.com/25686962/27822133-348888da-60d7-11e7-8f4e-5aeff8260145.png)

**Comment by MidoriYakumo** [comment]
interseting you can disable vaapi on nvidia boards cause you can use tegrajpeg

**Comment by xlz** [comment]
True, build it with `cmake -DENABLE_VAAPI=OFF` or something.

**Comment by RBEGamer** [comment]
this works for eg : `cmake .. -DENABLE_VAAPI=OFF -DCMAKE_INSTALL_PREFIX=$HOME/freenect2`

**Comment by leviresende** [comment]
Hey guys!
I'm using the JETSON TX 2 with the following configuration:
 L4T 28.2.1 [ JetPack 3.3 or 3.2.1 ]
 Board: t186ref
 Ubuntu 16.04.6 LTS
 Kernel Version: 4.4.38-tegra
 CUDA 9.0.252

And I'd like to connect it with a Kinect v2, however, I didn't have success. I've done everything that I read on the forums here on Github and on JetsonHacks, even tried to install as Kinect v1, but nothing. After all, I saw that it's not possible to connect a default board (TX2) with this device. Is it true?

By the way, which camera is it better to develop SLAM applications? ZED?

Thanks in advance.
