### ISSUE TITLE
How to get distance estimation [Depth info.] between the object and Kinect v2 

### ISSUE THREAD

**Issue by Abduoit** [OpenKinect/libfreenect2#880]
Hi, all and @xlz 

I am new for Kinect v2 and libfreenect2, I am using Ubuntu 16.04, and Kinect v2. I want to estimate the distance between the object and kinect v2. Now, I can obtain rgb, ir, and depth images from kinect v2.

I know that from the depth image we clearly notice that depth info. of the object is based on intensity of gray color [the most dense one is the closest to the kinect v2]. But I want I obtain the range of this gray color.

When I try these :-

```
roslaunch kinect2_bridge kinect2_bridge.launch
rostopic echo /kinect2/sd/image_depth
```

I get a lot of numbers and I do not know how to read it or convert it to millimeter or meter.

Any one can help ???????

**Comment by xlz** [comment]
Sure. The lost of numbers are pixels. You need to work it as images. Start with OpenCV and try something with image processing.
