### ISSUE TITLE
Kinect v2 as a webcam in Ubuntu 16.04, linux 

### ISSUE THREAD

**Issue by Abduoit** [OpenKinect/libfreenect2#881]
Hello, all 

The following simple python code is for detecting and tracking the object based on color by using webcam as a default.

This line `cap = cv2.VideoCapture(0)` is to capture the image from the webcam. 

My question is how can I use the same code but by using Kinect v2 (NOT webcam). ?

Any one can help with this, ??

```
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(1):

    # Take each frame
    _, frame = cap.read()

    # Convert BGR to HSV
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    # define range of blue color in HSV
    lower_blue = np.array([110,50,50])
    upper_blue = np.array([130,255,255])

    # Threshold the HSV image to get only blue colors
    mask = cv2.inRange(hsv, lower_blue, upper_blue)

    # Bitwise-AND mask and original image
    res = cv2.bitwise_and(frame,frame, mask= mask)

    cv2.imshow('Original',frame)
    cv2.imshow('mask',mask)
    cv2.imshow('Detect-Blue',res)
    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
```

**Comment by smie14353078** [comment]
i dont know where you get your python codes for kinect but i find it here
https://github.com/r9y9/pylibfreenect2/blob/master/examples/multiframe_listener.py
these open your kinect and i hope can help you
