### ISSUE TITLE
Kinect v2 with OpenNI and NiTE in an Ubuntu os

### ISSUE THREAD

**Issue by fma-1724** [OpenKinect/libfreenect2#884]
Hi!  I need to know if it is possible to use kinect v2 with OpenNI and NiTE to do the skeleton tracking in Ubuntu, i don't have the computer yet so i don't know the specific version of it.

None of the issues that i have look at give an specific answer to it, so can any of you tell me if it is possible and how to do it? or if there is already a post about it point me to it?

Thanks

**Comment by xlz** [comment]
It's possible. The hairy part is how to download NiTE. There's probably only pirated versions of it
