### ISSUE TITLE
bigdepth - undistorted frames depth deviation

### ISSUE THREAD

**Issue by alexkog** [OpenKinect/libfreenect2#888]
I'm trying to get the 3D coordinate of a pixel (cv::Point2f point2d) of the Kinect RGB frame (1920x1080).
For this purpose I'm using the bigdepth frame given by the Registration::apply function and then calculate the 3D point (as in getPointXYZ):

        libfreenect2::Frame * rgb = frames_[libfreenect2::Frame::Color];
        libfreenect2::Frame * depth = frames_[libfreenect2::Frame::Depth];
        int map_[512 * 424];
        registration_->apply(rgb, depth, &undistorted_, &registered_, true, &bigdepth, map_);

        libfreenect2::Freenect2Device * dev_ = 0;
        libfreenect2::Freenect2Device::ColorCameraParams cameraparams = dev_->getColorCameraParams();
        const float cx(cameraparams.cx), cy(cameraparams.cy);
        const float fx(1 / cameraparams.fx), fy(1 / cameraparams.fy);

        int c = int(point2d.x + 0.5), r = int(point2d.y + 0.5);
        float x, y, z;
        float *bigdepth_data = (float *)bigdepth.data;

        const float bad_point = std::numeric_limits<float>::quiet_NaN();
        const float depth_val = float(bigdepth_data[1920*(r+1)+c]) / 1000.0f;
        if (isnan(depth_val) || depth_val <= 0.001) {
            x = y = z = bad_point;
        } else {
            x = (c + 0.5 - cx) * fx * depth_val;
            y = (r + 0.5 - cy) * fy * depth_val;
            z = depth_val;
        }

If I compare this point (x,y,z) to the corresponding 3D point I get when I click on the PCL visualiser, there is an offset of the depth value of ~30cm. However, if I do the same process with the undistorted frame, I get the correct values comparing to PCL visualiser. 
Moreover, trying to compare the depth values of the bigdepth frame and the undistorted frame, as being outputted by the Registration::apply function, I don't see any direct correspondence between the depth values of these frames (i.e. if I search a value found in undistorted, I cannot find it in bigdepth).

Is there any other processing between undistorted and bigdepth frames apart from the x,y dimensional scale up?

**Comment by xlz** [comment]
`3D point I get when I click on the PCL visualiser` What might not be what you think it is.

`undistorted` uses the depth camera as reference frame. `bigdepth` uses the color camera as reference frame. They are of course different.
