### ISSUE TITLE
depth value

### ISSUE THREAD

**Issue by robotsoft** [OpenKinect/libfreenect2#889]
Hello,

What does depth.data and undistorted.data mean in void Registration::apply(const Frame *rgb, const Frame *depth, Frame *undistorted, Frame *registered, const bool enable_filter, Frame *bigdepth, int *color_depth_map)? It doesn't look like a real distance value in meter or millimeter.

**Comment by floe** [comment]
https://openkinect.github.io/libfreenect2/classlibfreenect2_1_1Registration.html#a8be3a548ff440e30f5e89a4b053e04fa - it's an array of `float` values in millimeters.
