### ISSUE TITLE
Program stuck on libfreenect2::Freenect2 freenect2; when creating dll.

### ISSUE THREAD

**Issue by augasur** [OpenKinect/libfreenect2#892]
Overview Description:

We are trying to create a dll of libfreenect2 for usage in C# but I have encountered a problem. When we use  same code in exe  it will work fine, but when we try to compile dll and try to reference it and use it with sample application program stops on libfreenect2::Freenect2 freenect2;. We do not get any error codes or exceptions.  

Steps to Reproduce:

I am using Windows 10, VS 2015

1. [Download ](https://drive.google.com/open?id=0B7BsaMq3lVCUb3hzdkR5MVExQ2c)project  and extract 
2. Run Dll_Tester_CPP.sln.  FreenectV2Wrapper is referenced to this project.
3.  Build and Run . You might need to copy referenced dlls to build directory
4. When you launch it, it should execute till `libfreenect2::Freenect2 freenect2;` and get stuck.

Could anyone point me to the right direction?

**Comment by xlz** [comment]
There is not enough information for an answer.
