### ISSUE TITLE
cmake error: Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)

### ISSUE THREAD

**Issue by timthegod** [OpenKinect/libfreenect2#897]
cmake error: Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
-
Greetings. I am not a native English speaker, so pardon me if there's any improper. 
I tried to built it on Visual Studio 2015(x64). I extracted TurboJPEG to depends/libjpeg-turbo64 as Readme said. I've also done every other procedures step by step. But when i tried to run cmake, it kept saying that "JPEG_LIBRARY" and "JPEG_INCLUDE_DIR" is missing. Here are the error messages:
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
-- Could NOT find TegraJPEG (missing: TegraJPEG_LIBRARIES TegraJPEG_INCLUDE_DIRS TegraJPEG_L4T_OK TegraJPEG_DRIVER_OK TegraJPEG_WORKS)

Should I install JPEG and TegraJPEG additionally? Or there are other ways to solve it?
I didn't see others with the same kinds of problems tho.
![error](https://user-images.githubusercontent.com/26105901/29739913-9bcb416c-8a7c-11e7-9d3d-6fa1a414cbc5.jpg)

**Comment by xlz** [comment]
README says this first: "extract it to c:\libjpeg-turbo64". This is the default setting of turbojpeg installer. So did you try this?
