### ISSUE TITLE
Docs lack values for environment variables

### ISSUE THREAD

**Issue by mediadog** [OpenKinect/libfreenect2#904]
The docs at:
https://openkinect.github.io/libfreenect2/index.html
List the environment variables, but do not explain what the legal values are and what they do.  This is all they say:

> LIBFREENECT2_LOGGER_LEVEL: The default logging level if not explicitly set by the code. LIBFREENECT2_PIPELINE: The default pipeline if not explicitly set by the code. LIBFREENECT2_RGB_TRANSFER_SIZE, LIBFREENECT2_RGB_TRANSFERS, LIBFREENECT2_IR_PACKETS, LIBFREENECT2_IR_TRANSFERS: Tuning the USB buffer sizes. Use only if you know what you are doing.

**Comment by xlz** [comment]
Okay, thanks for the concern. They are undocumented because they are not quite ready or appropriate for public use.
