### ISSUE TITLE
Depth frames too slow in Jetson TK1

### ISSUE THREAD

**Issue by DepSys4SmartHomes** [OpenKinect/libfreenect2#905]
I am running libfreenct2 on Jetson TK1. I am interested to get only depth data. The current frame rate is around 15-20 FPS. I would like to know how to reach ~60 FPS. I have the following set up:

1. I am using TurboJPEG instead of TegraJPEG. I am hoping it is not causing delays as I am not interested (and not listening) to RGB and IR images. 
2. I see that a majority of GPU cores are used to get and parse the depth frames (using ./tegrastats). As a result, there aren't much GPU cores left for other deep learning computation. Is that expected? Is there a way to limit the amount of GPU usage in the cuda_depth_packet_processor.cu or other places in the driver?

Thanks!

**Comment by xlz** [comment]
> I am using TurboJPEG instead of TegraJPEG. I am hoping it is not causing delays

It is causing delays.

> I see that a majority of GPU cores are used to get and parse the depth frames

TK1 is kind of weak for heavyweight compute. I don't expect TK1 GPU to be able to do anything else other than decoding depth frames You'd be looking for TX1 and later models for your application.
