### ISSUE TITLE
Calling frame listener in multithreaded programs 

### ISSUE THREAD

**Issue by walterwang** [OpenKinect/libfreenect2#910]
Appologize in advance that it's not really an issue, but others might run into the same problem with frame listener. I have an application that process some frames from the kinect and at the time it records a video of the Kinect. However, when I call the frame listener in a second thread, it is blocked? Is there an asynchronous version of frame listener or something that is non-blocking?

**Comment by xlz** [comment]
FrameListener is asynchronous. SyncMultiFrameListener::waitForNewFrame(FrameMap& frame, int milliseconds) is nonblocking I suppose.
