### ISSUE TITLE
OpenCl pipeline memory leak

### ISSUE THREAD

**Issue by IllyaHorzeev** [OpenKinect/libfreenect2#911]
Overview Description:

Hi I'm using libfreenect2 and have problem: 
1) i'm starting 4 kinects with opencl packet pipelines 
2)delete freenect2 object   and have memory leak about 100mb in each pipeline.
But when i use CPU packet pipeline and delete freenect2 object - all ok without memory leak

**Comment by xlz** [comment]
OpenCL does its own memory management things so this is expected. If you can pinpoint exact locations of leaks maybe we can fix it.

**Comment by xlz** [comment]
Reopen if reports are more specific.
