### ISSUE TITLE
CUDA and gcc5

### ISSUE THREAD

**Issue by normanhantke** [OpenKinect/libfreenect2#918]
Do I understand it correctly? CUDA is optional, but if I want to use gcc >= 5, I need CUDA >= 8?

I got it to work with Cuda 9, but I read in some other threads that you need at least Cuda 8...

**Comment by xlz** [comment]
CUDA's (limited) GCC compatibility is documented in its docs. You probably want to check Nvidia's website.  Our information may not reflect their latest status.
