### ISSUE TITLE
Noise in RGB data

### ISSUE THREAD

**Issue by munir01** [OpenKinect/libfreenect2#919]
I am trying to collect RGBD data by doing registration so that each RGB pixel corresponding to a depth pixel represents the RGB value of that depth pixel. I see that whenever a depth pixel has noise, the corresponding RGB pixel has noise as well. But without doing the registration, I can see pure RGB image without any noise. Is there a way to get RGBD mapped data where we will have correct RGB pixels even if the corresponding depth pixel is noisy? 

Here is a sample code I am using:

```
listener.waitForNewFrame(frames);
libfreenect2::Frame *rgb = frames[libfreenect2::Frame::Color];
libfreenect2::Frame *depth = frames[libfreenect2::Frame::Depth];

depth_image = cv::Mat(depth->height, depth->width, CV_32FC1, depth->data);

// # Mapping between depth & rgb image
registration->apply(rgb,depth,&undistorted,&registered); 
reg_image = cv::Mat(registered.height, registered.width, CV_8UC4, registered.data); 
```

Here is a sample RGB image and a depth image: [Link](https://github.com/DepSys4SmartHomes/Temp/blob/master/images/image-rgb.png)

Thanks!

**Comment by floe** [comment]
> Is there a way to get RGBD mapped data where we will have correct RGB pixels even if the corresponding depth pixel is noisy?

No, because you need the (noisy) depth value to determine which color pixel corresponds to the depth pixel. So the resulting RGBD image will always also be noisy, as it directly depends on the noisy depth values.
