### ISSUE TITLE
depthparser does not fire

### ISSUE THREAD

**Issue by saharshbishnoi** [OpenKinect/libfreenect2#92]
No Depth or ir data 

OpenGLDepthPacketProcessor::process is not called as libfreenect2::usb::TransferPool::DataRecievedCallback::onDataRecieved is not firing for depth or ir.

What could be causing this ?

Setup on ubuntu x64 as normal with the right usb 3 setup

**Comment by floe** [comment]
If you're getting RGB data, but only black windows on IR/Depth, then this is perhaps on an USB issue, but rather related to OpenGL. What's the output from Protonect?

**Comment by orenkislev** [comment]
Same for me. Camera output is there, but no IR/Depth. Dump of Protonect output:

[Freenect2Impl] enumerating devices...
[Freenect2Impl] 8 usb devices connected
[Freenect2Impl] found valid Kinect v2 @21:17 with serial 014549545147
[Freenect2Impl] found 1 devices
[Freenect2DeviceImpl] opening...
[Freenect2DeviceImpl] opened
[Freenect2DeviceImpl] starting...
[Freenect2DeviceImpl] ReadData0x14 response
92 bytes of raw data
0x0000:  00 00 12 00 00 00 00 00 01 00 00 00 43 c1 1f 41    ............C..A
0x0010:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x0020:  0a 21 33 55 ef 00 17 40 00 08 00 00 10 00 00 00    .!3U...@........
0x0030:  00 01 00 00 00 10 00 00 00 00 80 00 01 00 00 00    ................
0x0040:  31 33 00 00 00 01 08 04 47 4d 48 38 36 38 2e 31    13......GMH868.1
0x0050:  58 00 00 00 00 00 00 00 07 00 00 00                X...........

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  01 26 00 00                                        .&..

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  03 26 00 00                                        .&..

[Freenect2DeviceImpl] enabling usb transfer submission...
[Freenect2DeviceImpl] submitting usb transfers...
[Freenect2DeviceImpl] started
device serial: 014549545147
device firmware: 2.3.3913.0.7
[DepthPacketStreamParser::handleNewData] not all subsequences received 0
[DepthPacketStreamParser::handleNewData] not all subsequences received 896
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 991
[OpenGLDepthPacketProcessor] avg. time: 12.0469ms -> ~83.0089Hz
[TurboJpegRgbPacketProcessor] avg. time: 19.36ms -> ~51.6529Hz
[OpenGLDepthPacketProcessor] avg. time: 9.86257ms -> ~101.393Hz
[TurboJpegRgbPacketProcessor] avg. time: 19.4033ms -> ~51.5376Hz
[DepthPacketStreamParser::handleNewData] front buffer too short! subsequence number is 167780396
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 4096
[DepthPacketStreamParser::handleNewData] not all subsequences received 1022
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 991
[TurboJpegRgbPacketProcessor] avg. time: 18.7231ms -> ~53.4101Hz
[OpenGLDepthPacketProcessor] avg. time: 10.6825ms -> ~93.6111Hz
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 1007
[TurboJpegRgbPacketProcessor] avg. time: 18.6636ms -> ~53.5802Hz
[OpenGLDepthPacketProcessor] avg. time: 10.6546ms -> ~93.8566Hz
[TurboJpegRgbPacketProcessor] avg. time: 18.5582ms -> ~53.8846Hz
[OpenGLDepthPacketProcessor] avg. time: 10.2973ms -> ~97.1124Hz
[TurboJpegRgbPacketProcessor] avg. time: 17.3125ms -> ~57.7616Hz
[OpenGLDepthPacketProcessor] avg. time: 10.5464ms -> ~94.8187Hz
[TurboJpegRgbPacketProcessor] avg. time: 17.4225ms -> ~57.397Hz
[OpenGLDepthPacketProcessor] avg. time: 10.5147ms -> ~95.1053Hz
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 959

**Comment by PeterSmith255** [comment]
Protonect only shows the RGB with empty Ir and Depth. I would suggest this is as likely to be an issue with USB3 as it is to be with OpenGL or indeed for that matter OpenCL .

I solved my issue my issuing an ldd ~/libfreenect2/examples/protonect/bin/Protonect
and paying attention to the libfreenect2 path and finding the softlink pointing to the wrong location/version.

correcting this fixed the issue for me....meaning rgb, ir, and depth started to work with protonect....

Thanks for your help Floe, it is appreciated!
