### ISSUE TITLE
 Could NOT find LibUSB (missing: LibUSB_LIBRARIES LibUSB_INCLUDE_DIRS)

### ISSUE THREAD

**Issue by r-fujikura** [OpenKinect/libfreenect2#926]
Overview Description:
Hi, everyone.
I'm a college student in Japan.
I would like to implement elasticfusion, but I guess I have to use libfreenect2 to implement with Kinect v2.
So I have a  error.
I want you to tell me how to solve.

Version, Platform, and Hardware Bug Found:
Windows 10, cmake(3.10.0-rc4), visual studio 2015 community,kinect v2  

Actual Results:
C:\Users\t-takahashi\Desktop\libfreenect2-master\libfreenect2-master\build>cmake .. -G "Visual Studio 14 2015 Win64"
-- Selecting Windows SDK version 10.0.10240.0 to target Windows 10.0.15063.
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- using tinythread as threading library
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Performing Test LIBUSB_WITH_LIBUSBK
-- Performing Test LIBUSB_WITH_LIBUSBK - Success
-- Performing Test LIBUSB_WITH_USBDK
-- Performing Test LIBUSB_WITH_USBDK - Failed
CMake Warning at cmake_modules/FindLibUSB.cmake:55 (MESSAGE):
  UsbDk device driver is not found.  Fall back to libusbK.
Call Stack (most recent call first):
  CMakeLists.txt:93 (FIND_PACKAGE)

CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibUSB (missing: LibUSB_LIBRARIES LibUSB_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/FindLibUSB.cmake:102 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:93 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "C:/Users/t-takahashi/Desktop/libfreenect2-master/libfreenect2-master/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/t-takahashi/Desktop/libfreenect2-master/libfreenect2-master/build/CMakeFiles/CMakeError.log".

**Comment by floe** [comment]
Judging from your other issue, you have build errors with libusb. If you haven't yet successfully installed libusb, then it's obvious that CMake will not be able to find it, as the error message also says.

**Comment by r-fujikura** [comment]
Thank you very much for answering us carefully. I think that I have to put in the driver in the part described in Installation, is it enough to just install one of UsbDk and libusbK? In addition, libusb appears in the error message, and three names of drivers are coming out and it is confused. I am glad that you can teach the driver I should include. Thank you.

**Comment by ChiZhang0219** [comment]
I have the same problem and confused af.

**Comment by Peng154** [comment]
Anyone figure it out?this problem puzzles me for a very long time

**Comment by r-fujikura** [comment]
I think you should use UsbDk. Do you use  libusbK now ?

**Comment by Peng154** [comment]
emmmm, how to uninstall libusbK

**Comment by r-fujikura** [comment]
To uninstall the libusbK driver (and get back the official SDK driver, if installed):

Open "Device Manager"
Under "libusbK USB Devices" tree, right click the "Xbox NUI Sensor (Composite Parent)" device and select uninstall.
Important: Check the "Delete the driver software for this device." checkbox, then click OK.
If you already had the official SDK driver installed and you want to use it:

In Device Manager, in the Action menu, click "Scan for hardware changes."

This description is on Installation. (https://github.com/OpenKinect/libfreenect2)

**Comment by Peng154** [comment]
thanks, but i get the same error when i use the UsbDk.

**Comment by Peng154** [comment]
and my cmake error message is:
-- The C compiler identification is MSVC 19.0.23026.0
-- The CXX compiler identification is MSVC 19.0.23026.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- using tinythread as threading library
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Performing Test LIBUSB_WITH_LIBUSBK
-- Performing Test LIBUSB_WITH_LIBUSBK - Success
-- Performing Test LIBUSB_WITH_USBDK
-- Performing Test LIBUSB_WITH_USBDK - Success
CMake Error at C:/Program Files/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find LibUSB (missing: LibUSB_LIBRARIES)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/FindLibUSB.cmake:102 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:93 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "D:/kinect_driver/libfreenect2-master/build/CMakeFiles/CMakeOutput.log".

**Comment by Peng154** [comment]
and my cmake error message is:
-- The C compiler identification is MSVC 19.0.23026.0
-- The CXX compiler identification is MSVC 19.0.23026.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- using tinythread as threading library
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Performing Test LIBUSB_WITH_LIBUSBK
-- Performing Test LIBUSB_WITH_LIBUSBK - Success
-- Performing Test LIBUSB_WITH_USBDK
-- Performing Test LIBUSB_WITH_USBDK - Success
CMake Error at C:/Program Files/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find LibUSB (missing: LibUSB_LIBRARIES)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/FindLibUSB.cmake:102 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:93 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "D:/kinect_driver/libfreenect2-master/build/CMakeFiles/CMakeOutput.log".

**Comment by timohausmann** [comment]
> -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

this can be fixed via: `brew install pkgconfig` ( I also had to `brew link pkg-config`)

**Comment by livacengiz** [comment]
@timohausmann thanks for your help!

**Comment by livacengiz** [comment]
> > -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
> 
> With homebrew, this can be fixed via: `brew install pkgconfig` ( I also had to `brew link pkg-config`).
> This also resolved my libusb error.

thanks for your help!

**Comment by amadrzyk** [comment]
For me, running `brew install libusb` fixed this issue!

**Comment by weihohoho** [comment]
I am having the same problem again with VS2019.
May I confirm the install process of libusb. All you have to do is to extract the zipped files and leave them in the libusb directory. No other steps needed?

I am having the exact problem:
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Could NOT find LibUSB (missing: LibUSB_LIBRARIES)

Could anyone point out what to do on windows
