### ISSUE TITLE
Could not Import freenect2

### ISSUE THREAD

**Issue by sowrabhnayak** [OpenKinect/libfreenect2#928]
I have followed the steps for the installation of libfreenect2 as given in this link ( https://github.com/OpenKinect/libfree... Ubuntu 14.04.1) i have installed it at /home/user_name/ 
I have to import freenect2 just like this https://rjw57.github.io/freenect2-python/
But i'm not able to import freeenct2 and it gives me this error:

import freenect2 Traceback (most recent call last): File "<stdin>", line 1, in <module> ImportError: No module named freenect2

Or do i have any other option....

**Comment by totovr** [comment]
I think that is better to follow the original tutorial 

https://github.com/OpenKinect/libfreenect2/blob/master/README.md#linux

**Comment by ArmSorawis** [comment]
Have you already find way to solve this problem? If you knew just tell me please .

**Comment by totovr** [comment]
Follow the original tutorial and it will work
