### ISSUE TITLE
protonect.exe error

### ISSUE THREAD

**Issue by r-fujikura** [OpenKinect/libfreenect2#929]
Overview Description:
Hi, everyone.
I'm a college student in Japan.
I would like to implement elasticfusion, but I guess I have to use libfreenect2 to implement with Kinect v2.
So I have a error to use protonect.exe.
I want you to tell me how to solve.

Version, Platform, and Hardware Bug Found:
Windows 10, cmake(3.10.0-rc4), visual studio 2015 community,kinect v2

Actual Results:
Version: 0.2.0
Environment variables: LOGFILE=<protonect.log>
Usage: C:\Users\t-takahashi\Desktop\libfreenect2-master\libfreenect2-master\build\bin\Debug\Protonect.exe [-gpu=<id>] [gl | cl | clkde | cuda | cudakde | cpu] [<device serial>]
        [-noviewer] [-norgb | -nodepth] [-help] [-version]
        [-frames <number of frames to process>]
To pause and unpause: pkill -USR1 Protonect
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 9 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @22:2 with serial 511724142542
[Info] [Freenect2Impl] found 1 devices
[Info] [CudaDepthPacketProcessorImpl] device 0: GeForce GTX 970 @ 1253MHz Memory 4096MB
[Info] [CudaDepthPacketProcessorImpl] selected device 0
[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] transfer pool sizes rgb: 3*1048576 ir: 8*64*33792
[Info] [Freenect2DeviceImpl] opened
[Info] [Freenect2DeviceImpl] starting...
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Info] [Freenect2DeviceImpl] started
device serial: 511724142542
device firmware: 4.0.3916.0
The viewer is turned off. Received 100 frames. Ctrl-C to stop.
The viewer is turned off. Received 200 frames. Ctrl-C to stop.
The viewer is turned off. Received 300 frames. Ctrl-C to stop.
The viewer is turned off. Received 400 frames. Ctrl-C to stop.
The viewer is turned off. Received 500 frames. Ctrl-C to stop.
The viewer is turned off. Received 600 frames. Ctrl-C to stop.
The viewer is turned off. Received 700 frames. Ctrl-C to stop.
The viewer is turned off. Received 800 frames. Ctrl-C to stop.
The viewer is turned off. Received 900 frames. Ctrl-C to stop.
The viewer is turned off. Received 1000 frames. Ctrl-C to stop.

Expected Results:
If it is normal, I think that some viewers etc. reflecting the real world come out, but it does not come out
Reproducibility:

**Comment by xlz** [comment]
This is not an error. You should be able to use libfreenect2 with other applications all right.
