### ISSUE TITLE
Missing Packages, Warnings.

### ISSUE THREAD

**Issue by totovr** [OpenKinect/libfreenect2#932]
Mac OS Sierra, Installation 

I'm trying to set it in OS X but in the last point I get the next warning

![screen shot 2017-11-11 at 22 11 29](https://user-images.githubusercontent.com/15333235/32689765-87bd44ac-c72d-11e7-84b5-2240342800d3.png)

![screen shot 2017-11-11 at 22 42 55](https://user-images.githubusercontent.com/15333235/32689959-b7092506-c731-11e7-917a-1403a73f8a02.png)

**Comment by xlz** [comment]
The first warning "is for project developers." Ignore.

The compilation error says "The version ('90000') of the host compiler ('Apple clang') is not supported," which pretty much explained itself. You need to look up CUDA's support for Clang versions.
