### ISSUE TITLE
How to reproduce Euclidean coordinates (X,Y,Z) from undistorted depth?

### ISSUE THREAD

**Issue by djivani** [OpenKinect/libfreenect2#933]
I am converting the undistorted.data to cv::Mat of type CV_16UC1 so I can write each frame as an image to disk. How would I go about obtaining the Euclidean coordinates  (X,Y,Z) for each pixel (xi,yi) using the undistorted depth image, if I knew the IR Camera Parameters (cx,cy,fx,fy)?

**Comment by floe** [comment]
Have a look at how `registration->getPointXYZ()` is implemented, this should do what you want.

**Comment by xlz** [comment]
The above should be the answer.
