### ISSUE TITLE
convert Depth frame to RGB frame for video recording.

### ISSUE THREAD

**Issue by paulsoning** [OpenKinect/libfreenect2#938]
Hi,

I want to convert the depth frame into "gray color" so that I can "record" it with `libav`, but it looks a little bit funny.
My question is what exactly is in the frame data is it a float between 500-4500?
I use CL depth pipeline.

This is my output (and its like a tv with no reception, but I can see my contours):
![image](https://user-images.githubusercontent.com/11157695/33382209-634742ca-d520-11e7-8565-e5a0c60bb132.png)

**Comment by xlz** [comment]
http://openkinect.github.io/libfreenect2/classlibfreenect2_1_1Frame.html#a1d1cfd8ffb84e947f82999c682b666a7

> Depth | 512x424 float, unit: millimeter. Non-positive, NaN, and infinity are invalid or missing data.
