### ISSUE TITLE
Application Error 0x000007b when running Protonect.exe after libfreenect2 sucessful build

### ISSUE THREAD

**Issue by pauloguerraf** [OpenKinect/libfreenect2#939]
Hi, 

First of all thank you for your work on this library. I have successfully built libfreenect2 from source :
![buildsuccess](https://user-images.githubusercontent.com/1149371/33459844-8dc8bf18-d5f9-11e7-8644-3c6cb578a1cc.JPG)
![folderstructure](https://user-images.githubusercontent.com/1149371/33459961-0c5c9a16-d5fa-11e7-9ac0-e828bfa82193.JPG)

But unfortunately when I try to run Protonect.exe I get the following error:
![applicationerror](https://user-images.githubusercontent.com/1149371/33459878-b4cc753c-d5f9-11e7-987a-d710e4e5187e.JPG)

Any idea why is this could be happening?
I have tried your libfreenect2-0.2.0-libusbk-vs2015-x64 compiled release and it works correctly. Is there something I am missing when trying to build my version from scratch?

I am using the source code downloaded from your github master branch, running Windows 10

Thank you in advance for your help.

Best,

Paulo

**Comment by xlz** [comment]
You built from source using this script `make_release_msvc.cmd`. It is not documented and is used by the developers to make release, which means I can't answer why you had this problem. The error 0xc000007b means missing DLLs. Maybe you can figure it out yourself.

The documentation for building from source is in README.

**Comment by pauloguerraf** [comment]
I get the exact same error when using 
cmake .. -G "Visual Studio 14 2015 Win64"
and 
cmake --build . --config RelWithDebInfo --target install

![capture](https://user-images.githubusercontent.com/1149371/33485802-c68db412-d675-11e7-8336-d94ec1cdea99.JPG)
![capture2](https://user-images.githubusercontent.com/1149371/33485839-e354736a-d675-11e7-92d3-414de2c0b488.JPG)

Thank you
