### ISSUE TITLE
About "[Error] [Freenect2Impl] Your libusb does not support large iso buffer!"

### ISSUE THREAD

**Issue by Xbbei** [OpenKinect/libfreenect2#957]
Hi, I want to open the Kinect2 and FLIR A65 thermal camera in one app, use the libfreenect2 and OpenNI2 to drive the Kinect2 and eBus to drive the FLIR A65. I build my project without error. But when I want to connect the Kinect2, it will occur the error "[Error] [Freenect2Impl] Your libusb does not support large iso buffer!". So what's wrong with my libfreenect2? I open the Kinect2 and FLIR A65 successfully in different app in one PC. Another thing: Removing the about FLIR A65 codes but in the CMakeLists.txt still compile "EbusFlirInterface.cpp" that is my function that connect to FLIR A65, this error is still being. 

Thank you very much!
Sincerely,

**Comment by xlz** [comment]
Your libusb is too old. Nothing is wrong with your libfreenect2.
