### ISSUE TITLE
Protonect Viewer Hangs Up

### ISSUE THREAD

**Issue by vik0** [OpenKinect/libfreenect2#959]
Hi,

I have installed libfreenect2 and on running ./bin/Protonect I am getting a blank screen which hangs up.  How can I correct this? I have also installed openni2

Linux 16.04 64 bit 4.4.0-101-generic 
Quadro P5000

on running `LIBUSB_DEBUG=3 ./bin/Protonect`

Environment variables: LOGFILE=<protonect.log>
./bin/Protonect: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /home/user/s1/packages/libfreenect2/build/lib/libfreenect2.so.0.2)
./bin/Protonect: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /home/user/s1/packages/libfreenect2/build/lib/libfreenect2.so.0.2)
Version: 0.2.0
Environment variables: LOGFILE=<protonect.log>
Usage: ./bin/Protonect [-gpu=<id>] [gl | cl | clkde | cuda | cudakde | cpu] [<device serial>]
        [-noviewer] [-norgb | -nodepth] [-help] [-version]
        [-frames <number of frames to process>]
To pause and unpause: pkill -USR1 Protonect
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 15 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @6:5 with serial 500520242542
[Info] [Freenect2Impl] found 1 devices
[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] transfer pool sizes rgb: 20*16384 ir: 60*8*33792
[Info] [Freenect2DeviceImpl] opened
[Info] [Freenect2DeviceImpl] starting...
[Debug] [Freenect2DeviceImpl] status 0x090000: 9855
[Debug] [Freenect2DeviceImpl] status 0x090000: 9855
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Info] [Freenect2DeviceImpl] started
device serial: 500520242542
device firmware: 4.0.3914.0

Is it a problem with OpenCL?

I am attaching logs of 
1. `LIBUSB_DEBUG=3 ./bin/Protonect`
2. `dmesg`
3. `lsusb -t `
4. `lspci`

Thanks
[protonect_libusb_log.txt](https://github.com/OpenKinect/libfreenect2/files/1628923/protonect_libusb_log.txt)
[lsusb_log.txt](https://github.com/OpenKinect/libfreenect2/files/1628924/lsusb_log.txt)
[lspci_log.txt](https://github.com/OpenKinect/libfreenect2/files/1628925/lspci_log.txt)
[dmesg_log.txt](https://github.com/OpenKinect/libfreenect2/files/1628926/dmesg_log.txt)

**Comment by xlz** [comment]
> (Nvidia/Intel dual GPUs) After apt-get install cuda, use sudo prime-select intel to use Intel GPU for desktop.

Have you done this in README?
