### ISSUE TITLE
how to connect libfreenect2 with depthimage_to_laserscan

### ISSUE THREAD

**Issue by mohamedsemz** [OpenKinect/libfreenect2#964]
i want to convert kinect output to laserscan so i installed the libfreenect2 and the test program runs correctly when i searched i found depthimage_to_lascerscan package in ros so how can i connect the output from kinect to depthimage package ?

**Comment by xlz** [comment]
Sorry, this is not specific to libfreenect2. You are recommended to ask this question on a ROS user forum, https://answers.ros.org or mailing lists.
