### ISSUE TITLE
Cannot Install OpenNi2 Mac OS

### ISSUE THREAD

**Issue by Tenkir** [OpenKinect/libfreenect2#968]
Trying to install OpenNi2 on Mac OS 10.12.6. LibFreeNect2 works fine, and I can use Protonect to view the depth map. I'm able to get a feed into OpenFrameworks and access the device through there. When I try to install OpenNi2 however, I get this error:

```
Error: No available formula with the name "openni2"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
This similarly named formula was found:
totakke/openni2/openni2-freenectdriver
To install it, run:
  brew install totakke/openni2/openni2-freenectdriver
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

Seems openni2 is missing from Homebrew since the deprecation of the `homebrew/science` tap.

**Comment by xlz** [comment]
Maybe the instructions need an update? What is the current way to install openni2 with homebrew?

**Comment by Tenkir** [comment]
I don't believe there is one, at least based on what I've found.

**Comment by sushilei** [comment]
$ brew tap brewsci/science
and then
$ brew install openni2
