### ISSUE TITLE
OpenNI2 resolution documentation

### ISSUE THREAD

**Issue by eruffaldi** [OpenKinect/libfreenect2#972]
We have the following cases:

Unregistered: 
- color FULLHD
- depth native  512, or extended as 640

Registered:
- color 512
- depth native 512

Any other combination is wrong
Registration of depth over color for obtaining a fullhd depth is not supported

Version, Platform, and Hardware Bug Found:

1. `git log -1 --oneline`
f46fa65 (HEAD -> master, origin/master, origin/HEAD) usb: Select UsbDk with libusb_set_option
2. `uname -a`
Darwin I.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64
3. `lsusb -t`
not needed
4. `lspci -nn`
not needed

Steps to Reproduce:

1. 
2. 
3. 

Actual Results:

Expected Results:

Reproducibility:

Additional Information:

**Comment by xlz** [comment]
Yes they are indeed not supported, unfortunately.

**Comment by eruffaldi** [comment]
I just meant to add a way to highlight incompatible combinations. My students had bad CUDA or CPU memory errors due to this very reason. Oh yes, people are not reading the manuals

**Comment by xlz** [comment]
Supported resolutions:

Registration is controlled by ONI_DEVICE_PROPERTY_IMAGE_REGISTRATION.

IR stream is always unregistered 512x424 uint16.

* Registered, depth 640x480 uint16, color 512x424 RGB888
* Registered, depth 512x424 uint16, color 512x424 RGB888
* Unregistered, depth 640x480 uint16, color 1920x1080 RGB888

I don't have a good place to put this doc.
