### ISSUE TITLE
Bulk transfer failed

### ISSUE THREAD

**Issue by BrunoEduardoCSantos** [OpenKinect/libfreenect2#976]
Overview Description:

Steps to Reproduce:
1. ./Protonect 

Actual Results:
![image](https://user-images.githubusercontent.com/3111976/37612540-5d4ded5a-2b9d-11e8-98fb-14b99cc30599.png)
Expected Results:
Stream from Kinect

Additional Information: Ubuntu 16.04 in Oracle Virtual Box

Can anyone help?

**Comment by SirDifferential** [comment]
From the readme:
```
Requirements
...
Virtual machines likely do not work, because USB 3.0 isochronous transfer is quite delicate.
```

Try doing this without the Virtual Machine.
