### ISSUE TITLE
Help in Building libusb

### ISSUE THREAD

**Issue by kokleong9406** [OpenKinect/libfreenect2#979]
I am a programming idiot and I ran into this problem. Can anyone help me with regards to this?

<img width="819" alt="capture" src="https://user-images.githubusercontent.com/37173629/38069332-8fda2c8c-32ca-11e8-87be-a1eb1cad2c8f.PNG">

**Comment by kokleong9406** [comment]
I actually ran this in a Git CMD.

**Comment by SirDifferential** [comment]
I think the "System cannot find the path specified" is about msbuild.exe. Try to locate this and change the path to it as appropriate (in the libusb build script), if it's not at the dir shown in the screenshot.

You have Visual Studio 2015 installed, right?
