### ISSUE TITLE
freenect2.dll was not found error 

### ISSUE THREAD

**Issue by gregorsamsa183** [OpenKinect/libfreenect2#980]
I'm using libfreenect2 library with Windows 10. Even though I successfully build the solution and was able to run the Protonect demo, when I include the related directories on my VS15 application I get an error saying: freenect2.dll was not found. 

I can build my project successfully and this is the result when I try to run the program. I couldn't find any related issues on the internet. I even looked at the Project properties and copied extra libraries and include directories of the original libfreenect2.sln solution but it's still not working.

**Comment by SirDifferential** [comment]
The DLL is loaded upon the executable starting. You must put the DLL somewhere where it can be found - most commonly in the same directory as the executable. If you're starting the program through Visual Studio (or some other IDE) they may have a different working directory and the DLL may be placed somewhere else.

**Comment by SirDifferential** [comment]
You can use [Dependency Walker](http://www.dependencywalker.com/) to open the executable and see where this DLL is being searched. It should give an idea on where the DLL is expected to be.

**Comment by gregorsamsa183** [comment]
I'm already working with Ubuntu and everything is working fine by setting up the pylibfreenect2 library. For now, I won't be using VS.
