### ISSUE TITLE
How to reduce the resolution of colorframe from 1920*1080 to 640*480

### ISSUE THREAD

**Issue by getsumit123** [OpenKinect/libfreenect2#981]
Hello,
I am trying to reduce the resolution of Kinect V2 colorframe from 1920*1080 to 640*480
If anyone have any idea how to solve this problem to reduce the resolution.

Reason being when i connect Kinect V2 with Reference Target, there is massive packet drop which i suspect to be processing limitation of Reference Target.

**Comment by SirDifferential** [comment]
To my knowledge the color feed is always transmitted as full HD JPEG to the computer and this cannot be changed. I looked into something similar earlier in trying to reduce the bandwidth usage without our software, but I couldn't figure out a way to do this.

Maybe some people more familiar with the workings of the library can shed some light on if this really is the case?

**Comment by aenertia** [comment]
How does openni viewer do it? OpenNiviewer2 shows 2 substreams for the rgb device one at 1920x1080 and the other at 512x424 - which matches the 1st depth sensor streams... or is this just doing this with some copy to mat and resize magic?

**Comment by floe** [comment]
I think the OpenNI viewer just shows the depth-registered color stream, which is done in software?
