### ISSUE TITLE
Can i use Vmware ubuntu16.04 conect kinectv2？

### ISSUE THREAD

**Issue by salo120day** [OpenKinect/libfreenect2#985]
when i use libusb run the bin/Protonect，it show me the erro like
Protonect: "bulk transfer failed: LIBUSB_ERROR_TIMEOUT Operation timed out"

**Comment by floe** [comment]
As mentioned in the README, USB3 does not work well with virtual environments. You'll need to run Protonect directly on your host machine.

**Comment by salo120day** [comment]
@floe Thanks a lot,so if i use USB2 to run kinect v1 or other visual sensor in virtual environments,does it work?

**Comment by floe** [comment]
Yes, USB2 is usually pretty reliable, even in virtual hosts.

**Comment by salo120day** [comment]
@floe  ok,thanks,it help me a lot
