### ISSUE TITLE
No device connected

### ISSUE THREAD

**Issue by BerryOne** [OpenKinect/libfreenect2#998]
Overview Description:

Version, Platform, and Hardware Bug Found:

1. `git log -1 --oneline`
2. `uname -a`
3. `lsusb -t`
4. `lspci -nn`

Steps to Reproduce:

1. 
2. 
3. 

Actual Results:

Expected Results:

Reproducibility:

Additional Information:
I run the protonect.exe,but it shows no device connected.Is there some other problems,thanks!

EDIT: copied from other comment by @floe
```
Version: 0.2.0
Environment variables: LOGFILE=<protonect.log>
Usage: ./bin/Protonect [-gpu=] [gl | cl | cuda | cpu] []
[-noviewer] [-norgb | -nodepth] [-help] [-version]
[-frames ]
To pause and unpause: pkill -USR1 Protonect
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 4 usb devices connected
[Info] [Freenect2Impl] found 0 devices
no device connected!
```

**Comment by floe** [comment]
Did you connect your Kinect 2 to an USB3 port? It will not work otherwise.

**Comment by floe** [comment]
And please, don't spam other bug reports.

**Comment by BerryOne** [comment]
Thanks.I just want to say the bug reports show the same content！Sorry
